# Alfawise PE1004T
# Tasmota

# Switch ############################################################
switch:
  - platform: mqtt
    name: "Alfa03"
    state_topic: "alfa03/stat/RESULT"
    value_template: "{{ value_json.POWER }}"
    command_topic: "alfa03/cmnd/POWER"
    availability_topic: "alfa03/tele/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false
    json_attributes_topic: "alfa03/tele/STATE"

# Sensor ############################################################
#sensor:
#  - platform: mqtt
#    name: "Alfa03 Status"
#    state_topic: "alfa03/tele/STATE"
#    value_template: '{{ value_json["Wifi"]["RSSI"] }}'
#    unit_of_measurement: "%"
#    json_attributes_topic: "alfa03/tele/STATE"
##    json_attributes_template: "{{ value_json | tojson }}"
##    json_attributes:
##      - Uptime
##      - Heap
##      - LoadAvg
##      - SleepMode
##      - Sleep
##      - POWER
##      - Wifi

# Automations #######################################################
#automation:
#  - id: tv_board_off
#    alias: 'TV Board OFF'
#  #  initial_state: 'off'
#    trigger:
#      platform: state
#      entity_id: group.familie_wlan
#      to: 'not_home'
#    action:
#      service: switch.turn_off
#      entity_id: switch.alfa03

# Customize #########################################################
homeassistant:
  customize:
# Switch ##########
    switch.alfa03:
        friendly_name: "Häuschen"
        icon: mdi:home-lightbulb
#        icon: mdi:desktop-classic

# Sensor ##########
#    sensor.alfa03_status:
#      friendly_name: Alfa 03 Status
#      icon: mdi:information
#      unit_of_measurement: "%"