# Sonoff S20 2
# Tasmota

# Switch ############################################################
switch:
  - platform: mqtt
    name: "Sonoffs20 2"
    state_topic: "sonoffs20-2/stat/RESULT"
    value_template: "{{ value_json.POWER }}"
    command_topic: "sonoffs20-2/cmnd/POWER"
    availability_topic: "sonoffs20-2/tele/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false
    json_attributes_topic: "sonoffs20-2/tele/STATE"

# Sensor ############################################################
#sensor:
#  - platform: mqtt
#    name: "Sonoffs20 2 Status"
#    state_topic: "sonoffs20-2/tele/STATE"
#    value_template: '{{ value_json["Wifi"]["RSSI"] }}'
#    unit_of_measurement: "%"
#    json_attributes_topic: "sonoffs20-2/tele/STATE"

## Light #############################################################
#light:
#  - platform: switch
#    name: "SonoffS20 2"
#    entity_id: switch.sonoffs20_2

# Customize #########################################################
homeassistant:
  customize:
# Switch ##########
    switch.sonoffs20_2:
      friendly_name: Regenlicht
      icon: mdi:string-lights
#      friendly_name: Sonoff S20 2
#      icon: mdi:track-light
## Light ###########
#    light.sonoffs20_2:
#      friendly_name: Wandlicht
#      icon: mdi:track-light
# Sensor ##########
#    sensor.sonoffs20_2_status:
#      friendly_name: Sonoff S20 2 Status
#      icon: mdi:information
#      unit_of_measurement: "%"
