# Sonoff S26 2
# Sonoff-Tasmota

# Customize #########################################################
homeassistant:
  customize:
    # Switch ##########
    switch.sonoffs26_2:
      friendly_name: Küchenfenster
      icon: mdi:candle
