# Sonoff S20 2
# Sonoff-Tasmota

# Customize #########################################################
homeassistant:
  customize:
    # Switch ##########
    switch.sonoffs20_2:
      friendly_name: Garage
      icon: mdi:string-lights
