# Sonoff S20 1
# Tasmota

# Switch ############################################################
switch:
  - platform: mqtt
    name: "Sonoffs20 1"
    state_topic: "sonoffs20-1/stat/RESULT"
    value_template: "{{ value_json.POWER }}"
    command_topic: "sonoffs20-1/cmnd/POWER"
    availability_topic: "sonoffs20-1/tele/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false
    json_attributes_topic: "sonoffs20-1/tele/STATE"

# Sensor ############################################################
#sensor:
#  - platform: mqtt
#    name: "Sonoffs20 1 Status"
#    state_topic: "sonoffs20-1/tele/STATE"
#    value_template: '{{ value_json["Wifi"]["RSSI"] }}'
#    unit_of_measurement: "%"
#    json_attributes_topic: "sonoffs20-1/tele/STATE"

## Light #############################################################
#light:
#  - platform: switch
#    name: "SonoffS20 1"
#    entity_id: switch.sonoffs20_1

# Customize #########################################################
homeassistant:
  customize:
# Switch ##########
    switch.sonoffs20_1:
      friendly_name: Küchenfenster
      icon: mdi:candle
## Light ###########
#    light.sonoffs20_1:
#      friendly_name: Wandlicht
#      icon: mdi:track-light
# Sensor ##########
#    sensor.sonoffs20_1_status:
#      friendly_name: Sonoff S20 1 Status
#      icon: mdi:information
#      unit_of_measurement: "%"