# Sonoff S20 1
# Sonoff-Tasmota

# Customize #########################################################
homeassistant:
  customize:
    # Switch ##########
    switch.sonoffs20_1:
      friendly_name: Tanne
      icon: mdi:pine-tree
