# group.weihnachten_licht
group:
  weihnachten_licht:
    name: Weihnachten Licht
    entities:
      - switch.alfa01
      # - switch.alfa03
      - switch.sonoffs20_1
      - switch.sonoffs20_2
      # - switch.sonoffs26_1
      # - switch.sonoffs26_2

  weihnachten_licht_draussen:
    name: Weihnachten Licht draussen
    entities:
      # - switch.alfa01
      # - switch.alfa03
      # - switch.sonoffs20_1
      # - switch.sonoffs20_2
      # - switch.sonoffs26_1
      # - switch.sonoffs26_2

# Automations #######################################################
automation:
  - id: weihnachten_licht_an
    alias: Weihnachten Licht An
    trigger:
      # 15 minutes before sunset
      - platform: sun
        event: sunset
        offset: "-00:15:00"

    action:
      - service: switch.turn_on
        data:
          entity_id: group.weihnachten_licht

    # Anatolij Arbeit
  - id: weihnachten_licht_an_anatolij
    alias: Weihnachten Licht An Anatolij
    trigger:
      - platform: time
        at: "08:20:00"

    condition:
      condition: and
      conditions:
        # After 15 minutes after sunrise
        - condition: sun
          before: sunrise
          after_offset: "00:15:00"

        # Workdays
        - condition: time
          weekday:
            - mon
            - tue
            - wed
            - thu
            - fri

    action:
      - service: switch.turn_on
        data:
          entity_id: group.weihnachten_licht

  # Einschalten wenn Natalja hat Dienst
  - id: weihnachten_licht_an_natalja
    alias: Weihnachten Licht An Natalja
    trigger:
      - platform: time
        at: "06:45:00"

    condition:
      - condition: state
        entity_id: input_boolean.nataljas_night_shift
        state: 'on'

    action:
    - service: switch.turn_on
      data:
        entity_id: group.weihnachten_licht

  - id: weihnachten_licht_aus
    alias: Weihnachten Licht Aus
    trigger:
      - platform: time
        at: "00:00:00"
      - platform: time
        at: "09:30:00"
      - platform: sun
        event: sunrise
        offset: "00:15:00"

    action:
      - data:
          entity_id: group.weihnachten_licht
        service: switch.turn_off

  - id: weihnachten_licht_draussen_an
    alias: Weihnachten Licht Draussen An
    trigger:
      - platform: sun
        event: sunset
        offset: "00:20:00"

    action:
      - service: switch.turn_on
        data:
          entity_id: group.weihnachten_licht_draussen

  - id: weihnachten_licht_draussen_aus
    alias: Weihnachten Licht Draussen Aus
    trigger:
      - platform: time
        at: "23:00:00"

    action:
      - data:
          entity_id: group.weihnachten_licht_draussen
        service: switch.turn_off
