# group.weihnachten_licht
group:
  weihnachten_licht:
    name: Weihnachten Licht
    entities:
      - switch.alfa01
      - switch.sonoffs20_1
      # - switch.sonoffs20_2
      - switch.sonoffs26_2

  weihnachten_licht_draussen:
    name: Weihnachten Licht draussen
    entities:
      # - switch.alfa01
      # - switch.sonoffs20_1
      - switch.sonoffs20_2
      # - switch.sonoffs26_2

# Automations #######################################################
automation:
  # Weihnachten licht an am Abend
  - id: weihnachten_licht_an
    alias: Weihnachten - Licht An
    trigger:
      # 15 minutes before sunset
      - platform: sun
        event: sunset
        offset: "-00:15:00"

    condition:
      - condition: state
        entity_id: group.family_wlan
        alias: Is anybody home
        state: "home"

    action:
      - service: switch.turn_on
        data:
          entity_id: group.weihnachten_licht

  # Weihnachten licht an wenn jemand kommt
  - id: weihnachten_licht_an_wenn_jemand_kommt
    alias: Weihnachten - Licht An wenn jemand kommt
    trigger:
      - platform: state
        entity_id:
          - group.family_wlan
          - group.family
        from: "not_home"
        to: "home"
        for:
          hours: 0
          minutes: 3
          seconds: 0

    condition: "{{ state_attr('sun.sun', 'elevation') < 4 }}"

    action:
      - service: switch.turn_on
        data:
          entity_id: group.weihnachten_licht

    # Weihnachten licht an am Morgens
  - id: weihnachten_licht_an_anatolij
    # Anatolij Arbeit
    alias: Weihnachten - Licht An Anatolij
    trigger:
      - platform: time
        at: "08:20:00"

    condition:
      condition: and
      conditions:
        # After 15 minutes after sunrise
        - condition: sun
          before: sunrise
          after_offset: "00:15:00"

        # Workdays
        - condition: time
          weekday:
            - mon
            - tue
            - wed
            - thu
            - fri

    action:
      - service: switch.turn_on
        data:
          entity_id: group.weihnachten_licht

  # Einschalten wenn Natalja hat Dienst
  # - id: weihnachten_licht_an_natalja
  #   alias: Weihnachten - Licht An Natalja
  #   trigger:
  #     - platform: time
  #       at: "06:45:00"

  #   condition:
  #     - condition: state
  #       entity_id: input_boolean.nataljas_night_shift
  #       state: "on"

  #   action:
  #     - service: switch.turn_on
  #       data:
  #         entity_id: group.weihnachten_licht

  # Weihnachten licht aus
  - id: weihnachten_licht_aus
    alias: Weihnachten - Licht Aus
    trigger:
      - platform: time
        at:
          - "00:00:00"
          - "09:30:00"
      - platform: sun
        event: sunrise
        offset: "00:15:00"

      - platform: state
        entity_id:
          - group.family_wlan
          - group.family
        from: "home"
        to: "not_home"
        for:
          hours: 0
          minutes: 5
          seconds: 0

    action:
      - service: switch.turn_off
        data:
          entity_id: group.weihnachten_licht

  # Weihnachten licht draussen
  # Weihnachten licht draussen an
  - id: weihnachten_licht_draussen_an
    alias: Weihnachten - Licht Draussen An
    trigger:
      - platform: sun
        event: sunset
        offset: "00:20:00"

    action:
      - service: switch.turn_on
        data:
          entity_id: group.weihnachten_licht_draussen

  # Weihnachten licht draussen aus
  - id: weihnachten_licht_draussen_aus
    alias: Weihnachten - Licht Draussen Aus
    trigger:
      - platform: time
        at: "23:00:00"

    action:
      - service: switch.turn_off
        data:
          entity_id: group.weihnachten_licht_draussen
