# group.weihnachten_licht
# group:
#   weihnachten_licht:
#     name: Weihnachten Licht
#     entities:
#       - switch.alfa01
#       - switch.sonoffs20_1
#       # - switch.sonoffs20_2
#       - switch.sonoffs26_2

# weihnachten_licht_draussen:
#   name: Weihnachten Licht draussen
#   entities:
#     - switch.alfa01
#     - switch.sonoffs20_1
#     - switch.sonoffs26_2

# Automations #######################################################
automation:
  # Weihnachten licht an am Abend
  - id: weihnachten_licht_an
    alias: Weihnachten - Licht An
    triggers:
      # 15 minutes before sunset
      - trigger: sun
        event: sunset
        offset: "-00:15:00"

    conditions:
      - condition: state
        entity_id: group.family_wlan
        alias: Is anybody home
        state: "home"

    actions:
      - action: switch.turn_on
        data:
          entity_id: switch.weihnachten

  # Weihnachten licht an wenn jemand kommt
  - id: weihnachten_licht_an_wenn_jemand_kommt
    alias: Weihnachten - Licht An wenn jemand kommt
    triggers:
      - trigger: state
        entity_id:
          - group.family_wlan
          - group.family
        from: "not_home"
        to: "home"
        for:
          hours: 0
          minutes: 3
          seconds: 0

    conditions: "{{ state_attr('sun.sun', 'elevation') < 4 }}"

    actions:
      - action: switch.turn_on
        data:
          entity_id: switch.weihnachten

  # Weihnachten licht an am Morgens
  - id: weihnachten_licht_an_anatolij
    # Anatolij Arbeit
    alias: Weihnachten - Licht An Anatolij
    triggers:
      - trigger: time
        at: "08:20:00"

    conditions:
      condition: and
      conditions:
        # After 15 minutes after sunrise
        - condition: sun
          before: sunrise
          after_offset: "00:15:00"

        # Workdays
        - condition: time
          weekday:
            - mon
            - tue
            - wed
            - thu
            - fri

    actions:
      - action: switch.turn_on
        data:
          entity_id: switch.weihnachten

  # Einschalten wenn Natalja hat Dienst
  # - id: weihnachten_licht_an_natalja
  #   alias: Weihnachten - Licht An Natalja
  #   triggers:
  #     - trigger: time
  #       at: "06:45:00"

  #   conditions:
  #     - condition: state
  #       entity_id: input_boolean.nataljas_night_shift
  #       state: "on"

  #   actions:
  #     - action: switch.turn_on
  #       data:
  #         entity_id: switch.weihnachten

  # Weihnachten licht aus
  - id: weihnachten_licht_aus
    alias: Weihnachten - Licht Aus
    triggers:
      - trigger: time
        at:
          - "00:00:00"
          - "09:30:00"
      - trigger: sun
        event: sunrise
        offset: "00:15:00"

      - trigger: state
        entity_id:
          - group.family_wlan
          - group.family
        from: "home"
        to: "not_home"
        for:
          hours: 0
          minutes: 5
          seconds: 0

    actions:
      - action: switch.turn_off
        data:
          entity_id: switch.weihnachten

  # Weihnachten licht draussen

  # # Weihnachten licht draussen an
  # - id: weihnachten_licht_draussen_an
  #   alias: Weihnachten - Licht Draussen An
  #   triggers:
  #     - trigger: sun
  #       event: sunset
  #       offset: "00:20:00"

  #   actions:
  #     - action: switch.turn_on
  #       data:
  #         entity_id: switch.weihnachten_draussen

  # # Weihnachten licht draussen aus
  # - id: weihnachten_licht_draussen_aus
  #   alias: Weihnachten - Licht Draussen Aus
  #   triggers:
  #     - trigger: time
  #       at: "23:00:00"

  #   actions:
  #     - action: switch.turn_off
  #       data:
  #         entity_id: switch.weihnachten_draussen
