# Switches ##########################################################
switch:
  # Master control switch
  - platform: template
    switches:
      irrigation_watering:
        unique_id: irrigation_watering
        value_template: "{{ states('sensor.sonoffpow_02_energy_power') | float(0) > 100 }}"
        turn_on:
          service: switch.turn_on
          target:
            entity_id: switch.sonoffpow_02
        turn_off:
          service: switch.turn_off
          target:
            entity_id: switch.sonoffpow_02
        icon_template: "{{ 'mdi:water-pump' if is_state('switch.irrigation_watering', 'on') else 'mdi:water-pump-off' }}"

  # Groups
  - platform: group
    name: Irrigation - Switches Zone1
    unique_id: irrigation_switches_zone1
    all: true
    entities:
      - switch.irrigation_zone1_valve
      - switch.irrigation_pump
      - switch.irrigation_watering

  - platform: group
    name: Irrigation - Switches Zone2
    unique_id: irrigation_switches_zone2
    all: true
    entities:
      - switch.irrigation_zone2_valve
      - switch.irrigation_pump
      - switch.irrigation_watering

  - platform: group
    name: Irrigation - Switches Zone3
    unique_id: irrigation_switches_zone3
    all: true
    entities:
      - switch.irrigation_zone3_valve
      - switch.irrigation_pump
      - switch.irrigation_watering

  - platform: group
    name: Irrigation - Switches Pump
    unique_id: irrigation_switches_pump
    all: true
    entities:
      - switch.irrigation_pump
      - switch.irrigation_watering

# Sensors ###########################################################
template:
  - trigger:
      - platform: state
        entity_id:
          - switch.irrigation_switches_zone1
          - switch.irrigation_switches_zone2
          - switch.irrigation_switches_zone3
          - switch.irrigation_switches_pump
        from: "on"
        to: "off"
    sensor:
      - name: Irrigation last irrigated time
        unique_id: irrigation_last_irrigated_time
        state: >-
          {%- set date = as_timestamp(now()) -%}
          {%- set weekdays = ["Sonntag", "Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag"] -%}
          {%- set weekdays_short = ["So.", "Mo.", "Di.", "Mi.", "Do.", "Fr.", "Sa."] -%}
          {%- set months = ["Januar", "Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "Nowember", "Dezember"] -%}
          {%- set months_short = ["Jan", "Feb", "Mrz", "Apr", "Mai", "Jun", "Jul", "Aug", "Sep", "Okt", "Now", "Dez"] -%}
          {%- set w = date | timestamp_custom("%w") | int(0) -%}
          {%- set m = date | timestamp_custom("%m") | int(0) -%}
          {{ weekdays_short[w] }} {{ date | timestamp_custom('%d.%m.%Y %H:%M:%S', true) }}
        icon: mdi:clock-end
        attributes:
          datetime: "{{ now() }}"
          timestamp: "{{ as_timestamp(now()) }}"

  - sensor:
      # Water Consumption
      - name: Irrigation - Water Consumption Zone1
        unique_id: irrigation_water_consumption_zone1
        state: >-
          {{ (states('sensor.irrigation_watering_duration_zone1_yearly') | float(0)
          * states('input_number.os140_volume') | float(0) * 1.5) | round(2) }}
        device_class: water
        state_class: total_increasing
        unit_of_measurement: m³
        icon: mdi:water-outline
        attributes:
          cost: >-
            {{ (states('sensor.irrigation_water_consumption_zone1') | float(0)
            * states('input_number.water_price') | float(0)) | round(2) }}

      - name: Irrigation - Water Consumption Zone2
        unique_id: irrigation_water_consumption_zone2
        state: >-
          {{ (states('sensor.irrigation_watering_duration_zone2_yearly') | float(0)
          * states('input_number.os140_volume') | float(0) * 2) | round(2) }}
        device_class: water
        state_class: total_increasing
        unit_of_measurement: m³
        icon: mdi:water-outline
        attributes:
          cost: >-
            {{ (states('sensor.irrigation_water_consumption_zone2') | float(0)
            * states('input_number.water_price') | float(0)) | round(2) }}

      # 10 литров за 72 секунды = 500 литров/час = 0,5 m³/h
      - name: Irrigation - Water Consumption Zone3
        unique_id: irrigation_water_consumption_zone3
        state: >-
          {{ (states('sensor.irrigation_watering_duration_zone3_yearly') | float(0)
          * 0.5) | round(2) }}
        device_class: water
        state_class: total_increasing
        unit_of_measurement: m³
        icon: mdi:water-outline
        attributes:
          cost: >-
            {{ (states('sensor.irrigation_water_consumption_zone3') | float(0)
            * states('input_number.water_price') | float(0)) | round(2) }}

      - name: Irrigation - Water Consumption Pump
        unique_id: irrigation_water_consumption_pump
        state: >-
          {{ (states('sensor.irrigation_water_consumption_zone1') | float(0)
          + states('sensor.irrigation_water_consumption_zone2') | float(0)
          + states('sensor.irrigation_water_consumption_zone3') | float(0)) | round(2) }}
        device_class: water
        state_class: total_increasing
        unit_of_measurement: m³
        icon: mdi:water
        attributes:
          cost: >-
            {{ (states('sensor.irrigation_water_consumption_pump') | float(0)
            * states('input_number.water_price') | float(0)) | round(2) }}

      # - name: Irrigation - Watering duration
      #   unique_id: irrigation_watering_duration
      #   state: >-
      #     {% set t = states('sensor.irrigation_watering_duration_pump_yearly') | float(0) * 60 -%}
      #     {%- if t > 1440 -%}
      #       {{ '%0d Tg. %0.02d:%0.02d:%0.02d' | format(t // 1440, t % 1440 // 60, t % 60, t % 1 * 60) }}
      #     {%- else -%}
      #       {{ '%0.02d:%0.02d:%02d' | format(((t % 1440) // 60), t % 60, t % 1 * 60) }}
      #     {%- endif %}
      #   icon: mdi:clock
      #   attributes:
      #     pump_daily: >-
      #       {% set t = states('sensor.irrigation_watering_duration_pump_daily') | float(0) *60 %}
      #       {{ '%0.02d:%0.02d:%0.02d' | format(t // 60, t % 60, t % 1 * 60) }}
      #     pump_yearly: "{{ states('sensor.irrigation_watering_duration') }}"
      #     zone1_daily: >-
      #       {% set t = states('sensor.irrigation_watering_duration_zone1_daily') | float(0) *60 %}
      #       {{ '%0.02d:%0.02d:%0.02d' | format(t // 60, t % 60, t % 1 * 60) }}
      #     zone1_yearly: >-
      #       {% set t = states('sensor.irrigation_watering_duration_zone1_yearly') | float(0) * 60 -%}
      #       {%- if t > 1440 -%}
      #         {{ '%0d Tg. %0.02d:%0.02d:%0.02d' | format(t // 1440, t % 1440 // 60, t % 60, t % 1 * 60) }}
      #       {%- else -%}
      #         {{ '%0.02d:%0.02d:%02d' | format(((t % 1440) // 60), t % 60, t % 1 * 60) }}
      #       {%- endif %}
      #     zone2_daily: >-
      #       {% set t = states('sensor.irrigation_watering_duration_zone2_daily') | float(0) *60 %}
      #       {{ '%0.02d:%0.02d:%0.02d' | format(t // 60, t % 60, t % 1 * 60) }}
      #     zone2_yearly: >-
      #       {% set t = states('sensor.irrigation_watering_duration_zone2_yearly') | float(0) * 60 -%}
      #       {%- if t > 1440 -%}
      #         {{ '%0d Tg. %0.02d:%0.02d:%0.02d' | format(t // 1440, t % 1440 // 60, t % 60, t % 1 * 60) }}
      #       {%- else -%}
      #         {{ '%0.02d:%0.02d:%02d' | format(((t % 1440) // 60), t % 60, t % 1 * 60) }}
      #       {%- endif %}
      #     zone3_daily: >-
      #       {% set t = states('sensor.irrigation_watering_duration_zone3_daily') | float(0) *60 %}
      #       {{ '%0.02d:%0.02d:%0.02d' | format(t // 60, t % 60, t % 1 * 60) }}
      #     zone3_yearly: >-
      #       {% set t = states('sensor.irrigation_watering_duration_zone3_yearly') | float(0) * 60 -%}
      #       {%- if t > 1440 -%}
      #         {{ '%0d Tg. %0.02d:%0.02d:%0.02d' | format(t // 1440, t % 1440 // 60, t % 60, t % 1 * 60) }}
      #       {%- else -%}
      #         {{ '%0.02d:%0.02d:%02d' | format(((t % 1440) // 60), t % 60, t % 1 * 60) }}
      #       {%- endif %}

sensor:
  # Watering durations
  - platform: history_stats
    name: Irrigation - Watering Duration Zone1 Daily
    entity_id: switch.irrigation_switches_zone1
    state: "on"
    type: time
    start: "{{ today_at() }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: Irrigation - Watering Duration Zone2 Daily
    entity_id: switch.irrigation_switches_zone2
    state: "on"
    type: time
    start: "{{ today_at() }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: Irrigation - Watering Duration Zone3 Daily
    entity_id: switch.irrigation_switches_zone3
    state: "on"
    type: time
    start: "{{ today_at() }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: Irrigation - Watering Duration Pump Daily
    entity_id: switch.irrigation_switches_pump
    state: "on"
    type: time
    start: "{{ today_at() }}"
    end: "{{ now() }}"

# Utility meter #####################################################
utility_meter:
  irrigation_watering_duration_zone1_yearly:
    unique_id: irrigation_watering_duration_zone1_yearly
    source: sensor.irrigation_watering_duration_zone1_daily
    cycle: yearly

  irrigation_watering_duration_zone2_yearly:
    unique_id: irrigation_watering_duration_zone2_yearly
    source: sensor.irrigation_watering_duration_zone2_daily
    cycle: yearly

  irrigation_watering_duration_zone3_yearly:
    unique_id: irrigation_watering_duration_zone3_yearly
    source: sensor.irrigation_watering_duration_zone3_daily
    cycle: yearly

  irrigation_watering_duration_pump_yearly:
    unique_id: irrigation_watering_duration_pump_yearly
    source: sensor.irrigation_watering_duration_pump_daily
    cycle: yearly

# Automations #######################################################
automation:
  # Notify when valve and pump changed status
  - id: irrigation_notify
    alias: Irrigation - Notify
    mode: parallel

    trigger:
      - platform: state
        entity_id:
          - switch.irrigation_switches_zone1
          - switch.irrigation_switches_zone2
          - switch.irrigation_switches_zone3
          - switch.irrigation_switches_pump
        from: "on"
        to: "off"
        variables:
          action: "Ende"

      - platform: state
        entity_id:
          - switch.irrigation_switches_zone1
          - switch.irrigation_switches_zone2
          - switch.irrigation_switches_zone3
          - switch.irrigation_switches_pump
        from: "off"
        to: "on"
        variables:
          action: "Start"

    # condition:
    # - condition: template
    #   value_template: "{{ trigger.to_state.state != trigger.from_state.state }}"

    action:
      - service: notify.telegram_schick_home
        data:
          title: 💦 Bewässerung
          message: "{{ action }} *{{ trigger.from_state.attributes.friendly_name}}*"

# Customize #########################################################
homeassistant:
  customize:
    sensor.irrigation_ontime_zone1_daily:
      friendly_name: "Bewässerung Hinten (Heute)"
    sensor.irrigation_ontime_zone2_daily:
      friendly_name: "Bewässerung Vorne (Heute)"
    sensor.irrigation_ontime_zone3_daily:
      friendly_name: "Hahnoffnung (Heute)"
    sensor.irrigation_ontime_pump_daily:
      friendly_name: "Pumpennutzung (Heute)"

    sensor.irrigation_ontime_zone1:
      friendly_name: "Bewässerung Hinten"
    sensor.irrigation_ontime_zone2:
      friendly_name: "Bewässerung Vorne"
    sensor.irrigation_ontime_zone3:
      friendly_name: "Hahnoffnung"
    sensor.irrigation_ontime_pump:
      friendly_name: "Pumpennutzung"

    # Switches ##############
    # Master control switch
    switch.irrigation_watering:
      friendly_name: "Irrigation - Bewässerungschalter"
      icon: mdi:numeric-1-box-multiple

    # Groups of switches
    switch.irrigation_switches_zone1:
      friendly_name: "Irrigation - Hinterhofgruppe"
      icon: mdi:numeric-1-box-multiple
    switch.irrigation_switches_zone2:
      friendly_name: "Irrigation - Vorderhofgruppe"
      icon: mdi:numeric-2-box-multiple
    switch.irrigation_switches_zone3:
      friendly_name: "Irrigation - Hahngruppe"
      icon: mdi:faucet
    switch.irrigation_switches_pump:
      friendly_name: "Irrigation - Pumpengruppe"
      icon: mdi:pump

    # Sensors
    sensor.irrigation_last_irrigated_time:
      friendly_name: "Irrigation - Bewässerung beendet"

    # Water consumption
    sensor.irrigation_water_consumption_zone1:
      friendly_name: "Irrigation - Wasserverbrauch Hinterhof"
    sensor.irrigation_water_consumption_zone2:
      friendly_name: "Irrigation - Wasserverbrauch Vorderhof"
    sensor.irrigation_water_consumption_zone3:
      friendly_name: "Irrigation - Wasserverbrauch Hahn"
    sensor.irrigation_water_consumption_pump:
      friendly_name: "Irrigation - Wasserverbrauch Pumpe"

    sensor.irrigation_watering_duration:
      friendly_name: "Irrigation - Dauer Jährlich"

    # Watering duration
    sensor.irrigation_watering_duration_zone1_daily:
      friendly_name: "Irrigation - Dauer Hinterhof Täglich"
      icon: mdi:clock-outline
    sensor.irrigation_watering_duration_zone2_daily:
      friendly_name: "Irrigation - Dauer Vorderhof Täglich"
      icon: mdi:clock-outline
    sensor.irrigation_watering_duration_zone3_daily:
      friendly_name: "Irrigation - Dauer Hahn Täglich"
      icon: mdi:clock-outline
    sensor.irrigation_watering_duration_pump_daily:
      friendly_name: "Irrigation - Dauer Pumpe Täglich"
      icon: mdi:clock-outline

    sensor.irrigation_watering_duration_zone1_yearly:
      friendly_name: "Irrigation - Dauer Hinterhof Jährlich"
    sensor.irrigation_watering_duration_zone2_yearly:
      friendly_name: "Irrigation - Dauer Vorderhof Jährlich"
    sensor.irrigation_watering_duration_zone3_yearly:
      friendly_name: "Irrigation - Dauer Hahn Jährlich"
    sensor.irrigation_watering_duration_pump_yearly:
      friendly_name: "Irrigation - Dauer Pumpe Jährlich"

      # Recorder ##########################################################
# recorder:
#  exclude:
#  entities:
#  - sensor.irrigation_hs_zone1_daily
#  - sensor.irrigation_hs_zone2_daily
#  - sensor.irrigation_hs_zone3_daily
#  - sensor.irrigation_hs_pump_daily
#  - input_number.irrigation_ontime_zone1
#  - input_number.irrigation_ontime_zone2
#  - input_number.irrigation_ontime_zone3
#  - input_number.irrigation_ontime_pump
#  - automation.irrigation_set_start_time
#  - automation.irrigation_daily_to_total
#  - automation.irrigation_update_the_last_time_a_cycle_ended
#  - automation.irrigation_notify

## Logbook ###########################################################
# logbook:
#  exclude:
#  entities:
#  - group.irrigation_status_zone1
#  - group.irrigation_status_zone2
#  - group.irrigation_status_zone3
#  - sensor.irrigation_hs_zone1_daily
#  - sensor.irrigation_hs_zone2_daily
#  - sensor.irrigation_hs_zone3_daily
#  - sensor.irrigation_hs_pump_daily
#  - input_number.irrigation_ontime_zone1
#  - input_number.irrigation_ontime_zone2
#  - input_number.irrigation_ontime_zone3
#  - input_number.irrigation_ontime_pump
#  - automation.irrigation_set_start_time
#  - automation.irrigation_daily_to_total
#  - automation.irrigation_update_the_last_time_a_cycle_ended
#  - automation.irrigation_notify

