# Automations #######################################################
automation:
  # Отключение насоса, при отключении автоматизации полива
  - id: irrigation_failsafe_pump_control_switch
    alias: Irrigation - Failsafe Pump Control Switch
    description: "Отключение насоса, при отключении автоматизации полива"

    triggers:
      - trigger: state
        entity_id: input_boolean.irrigation_master_control_switch
        to: "off"

    actions:
      - action: switch.turn_off
        entity_id: switch.irrigation_pump

  # Smart pump control
  - id: irrigation_smart_pump
    alias: Irrigation - Smart Pump Control
    triggers:
      - trigger: state
        entity_id: switch.irrigation_valves
        to: "on"
        for: "00:00:01"
        id: valve_on
      - trigger: state
        entity_id: switch.irrigation_valves
        to: "off"
        for: "00:00:04"
        id: valve_off
      - trigger: time_pattern
        minutes: "/15"
        id: every15min

    actions:
      - choose:
          - conditions:
              - condition: trigger
                id: valve_on
              - condition: state
                entity_id: switch.irrigation_pump
                state: "off"
            sequence:
              - action: switch.turn_on
                target:
                  entity_id: switch.irrigation_pump
          - conditions:
              - condition: trigger
                id:
                  - valve_off
                  - every15min
              - condition: state
                entity_id: switch.irrigation_valves
                state: "off"
              - condition: state
                entity_id: switch.irrigation_zone3_valve
                state: "off"
            sequence:
              - action: switch.turn_off
                target:
                  entity_id: switch.irrigation_pump

  # Включение насоса для подкачки
  - id: irrigation_regular_pumping
    alias: Irrigation - Regular pumping
    description: "Регулярная подкачка воды"

    triggers:
      - trigger: time_pattern
        hours: "/4"
        minutes: "2"

    conditions:
      - condition: state
        entity_id: switch.irrigation_pump
        state: "off"

    actions:
      - action: switch.turn_on
        entity_id: switch.irrigation_pump
      - delay: 15
      - action: switch.turn_off
        entity_id: switch.irrigation_pump
