# Automations #######################################################
automation:
  #####################################################################
  # Master Control switch
  #
  # This turns on or off,
  #   All the Irrigation automations.
  #   All the automations related to Weather used in Irrigation.
  #
  #   i.e. all automations with a name beginning with either
  #        'Irrigation - ' or
  #        'Irrigation Weather - '
  #
  # Also checks when HA starts.
  #####################################################################
  - id: irrigation_master_control_switch
    alias: Irrigation - Master Control Switch
    triggers:
      - trigger: state
        entity_id: input_boolean.irrigation_master_control_switch

      - trigger: homeassistant
        event: start

    actions:
      # Stop both cycles ####################
      - action: input_boolean.turn_off
        data:
          entity_id:
            - input_boolean.irrigation_cycle1_manual_run
            - input_boolean.irrigation_cycle2_manual_run

      # Turn all Irrigation automations on or off (EXCEPT this one!)
      - action: >
          {% if is_state('input_boolean.irrigation_master_control_switch', 'on') %}
            automation.turn_on
          {% else %}
            automation.turn_off
          {% endif %}

        data:
          entity_id: >
            {% for item in states['automation'] if item.name.startswith('Irrigation - ') and
                                                  item.name.find('Master Control Switch') == -1 -%}
              {% if not loop.first %},{% endif %}{{ item.entity_id }}
            {%- endfor %}

      # Turn all Weather Irrigation automations on or off
      #      - action: >
      #          {% if is_state('input_boolean.irrigation_master_control_switch', 'on') %}
      #            automation.turn_on
      #          {% else %}
      #            automation.turn_off
      #          {% endif %}
      #        data:
      #          entity_id: >
      #            {% for item in states['automation'] if item.name.startswith('Irrigation Weather - ') -%}
      #              {% if not loop.first %},{% endif %}{{ item.entity_id }}
      #            {%- endfor %}

      # Turn off all pulsetimes on Tasmota
      - action: mqtt.publish
        data:
          topic: sonoff4ch/cmnd/pulsetime1
          payload: 0

      - action: mqtt.publish
        data:
          topic: sonoff4ch/cmnd/pulsetime2
          payload: 0

      - action: mqtt.publish
        data:
          topic: sonoff4ch/cmnd/pulsetime3
          payload: 0

      - action: mqtt.publish
        data:
          topic: sonoff4ch/cmnd/pulsetime4
          payload: 0
