#####################################################################
# Not that I don't trust my programming but...
#   1. Turn off valves and schedules when master control switch is off
#   2. Turn off all valves when HA starts
#   3. Don't allow more than one valve on at one time
#   4. Turn off valve 1 to 4 if it is on for longer than 59 minutes
# Better safe than sorry!
#####################################################################

# Automations #######################################################
automation:
  #######################################
  # Master Control Switch
  # Turn off valves and schedules when master control switch is off
  #######################################
  - id: irrigation_failsafe_master_control_switch
    alias: Irrigation - Failsafe Master Control Switch
    triggers:
      - trigger: state
        entity_id: input_boolean.irrigation_master_control_switch
        to: "off"

      - trigger: homeassistant
        event: start

    actions:
      - action: homeassistant.turn_off
        entity_id:
          - input_boolean.irrigation_cycle1_manual_run
          - input_boolean.irrigation_cycle2_manual_run
          - switch.irrigation_zone1_valve
          - switch.irrigation_zone2_valve
          - switch.irrigation_zone3_valve

  #######################################
  # Don't allow more than one valve on at one time.
  # and pump on when valve on
  # And
  # Turn off valve 1 to 3 if it is on for longer than 120 minutes.
  #######################################

  # Valve 1 ON
  - id: irrigation_failsafe_valve_1_on
    alias: Irrigation - Failsafe Valve 1 On
    triggers:
      - trigger: state
        entity_id:
          - switch.irrigation_zone1_valve
        to: "on"

    actions:
      - action: switch.turn_off
        entity_id:
          - switch.irrigation_zone2_valve
      #        - switch.irrigation_zone3_valve

      - wait_template: "{{ is_state('switch.irrigation_zone1_valve', 'off') }}"
        timeout: "02:00:15"

      - action: switch.turn_off
        entity_id:
          - switch.irrigation_zone1_valve

  # Valve 2 ON
  - id: irrigation_failsafe_valve_2_on
    alias: Irrigation - Failsafe Valve 2 On
    triggers:
      - trigger: state
        entity_id:
          - switch.irrigation_zone2_valve
        to: "on"

    actions:
      - action: switch.turn_off
        entity_id:
          - switch.irrigation_zone1_valve
      #        - switch.irrigation_zone3_valve

      - wait_template: "{{ is_state('switch.irrigation_zone2_valve', 'off') }}"
        timeout: "02:00:15"

      - action: switch.turn_off
        entity_id:
          - switch.irrigation_zone2_valve
## Valve 3 ON
#  - id: irrigation_failsafe_valve_3_on
#    alias: Irrigation Failsafe - Valve 3 On
#    triggers:
#    - trigger: state
#      entity_id:
#      - switch.irrigation_zone3_valve
#      to: 'on'
#
#    actions:
#    - action: homeassistant.turn_off
#      entity_id:
#        - switch.irrigation_zone1_valve
#        - switch.irrigation_zone2_valve
#
#    - wait_template: "{{ is_state('switch.irrigation_zone3_valve', 'off') }}"
#      timeout: '01:30:15'
#
#    - action: switch.turn_off
#      entity_id:
#        - switch.irrigation_zone3_valve
