# sudo hcitool lescan
# C4:7C:8D:67:BC:23
# sudo hciconfig hci0 down
# sudo hciconfig hci0 up
# sudo su
# crontab -e
# 0 * * * * timeout 15s hcitool lescan >/dev/null 2>&1

#sensor:
#  - platform: miflora
#    mac: 'C4:7C:8D:67:BC:23'
#    name: Flower 1
#    force_update: true
#    median: 3
#    monitored_conditions:
#      - moisture
#      - light
#      - temperature
#      - conductivity
#      - battery

plant:
  rasen:
    sensors:
      #      moisture: sensor.flower_1_moisture
      #      battery: sensor.flower_1_battery
      #      temperature: sensor.flower_1_temperature
      #      conductivity: sensor.flower_1_conductivity
      #      brightness: sensor.flower_1_light_intensity
      moisture: sensor.rasen_moisture
      battery: sensor.rasen_battery
      temperature: sensor.rasen_temperature
      conductivity: sensor.rasen_conductivity
      brightness: sensor.rasen_light
    min_battery: 15
    min_moisture: 15
    max_moisture: 60
    min_conductivity: 350
    max_conductivity: 2000
    min_temperature: 8
    max_temperature: 32
    min_brightness: 3700
    max_brightness: 20000
    check_days: 3

homeassistant:
  customize:
    plant.rasen:
      friendly_name: Rasen
    #      entity_picture: /local/images/rasen.png

    sensor.rasen_moisture:
      friendly_name: Bodenfeuchte (Rasen)
    sensor.rasen_light:
      friendly_name: Licht (Rasen)
    sensor.rasen_temperature:
      friendly_name: Temperatur (Rasen)
    sensor.rasen_conductivity:
      friendly_name: Fruchtbarkeit (Rasen)
    sensor.rasen_battery:
      friendly_name: Batterie (Rasen)
