# Sonoff 4CH Pro R2
# Tasmota integration
# Irrigation

# Template sensor ###########
template:
  - sensor:
      # States
      - name: Irrigation WiFi
        unique_id: irrigation_wifi
        state: "{{ states('sensor.sonoff4ch1_rssi') }}"
        unit_of_measurement: "%"
        icon: >-
          {% if states('sensor.sonoff4ch1_rssi')|float(0) > 80 -%}mdi:wifi-strength-4
          {% elif states('sensor.sonoff4ch1_rssi')|float(0) > 60 -%}mdi:wifi-strength-3
          {% elif states('sensor.sonoff4ch1_rssi')|float(0) > 40 -%}mdi:wifi-strength-2
          {% elif states('sensor.sonoff4ch1_rssi')|float(0) > 20 -%}mdi:wifi-strength-1
          {%- else -%}mdi:wifi-strength-outline
          {%- endif %}

# Customize #################
homeassistant:
  customize:
    sensor.irrigation_wifi:
      friendly_name: Irrigation - WLAN Stärke

    switch.irrigation_zone1_valve:
      friendly_name: Irrigation - Hinten Ventil
      icon: mdi:sprinkler-variant
    switch.irrigation_zone2_valve:
      friendly_name: Irrigation - Vorne Ventil
      icon: mdi:sprinkler-variant
    switch.irrigation_zone3_valve:
      friendly_name: Irrigation - Hahn
      icon: mdi:faucet
    switch.irrigation_zone4_valve:
      friendly_name: Irrigation - Pumpe
      icon: mdi:engine
