# Irrigation - Global variables and scripts

# Groups ############################################################
group:
  irrigation_switches:
    entities:
      - switch.zone1_valve
      - switch.zone2_valve
    #  - switch.zone3_valve

  irrigation_automations:
    entities:
      - automation.irrigation_cancel_a_manual_cycle
      - automation.irrigation_failsafe_master_control_switch
      - automation.irrigation_failsafe_pump_master_control_switch
      - automation.irrigation_failsafe_valve_1_on
      - automation.irrigation_failsafe_valve_2_on
    #  - automation.irrigation_failsafe_valve_3_on
      - automation.irrigation_master_control_switch
      - automation.irrigation_pump_off
      - automation.irrigation_pump_on
      - automation.irrigation_run_a_cycle_manually
      - automation.irrigation_run_cycle_1
      - automation.irrigation_run_cycle_2
      - automation.irrigation_set_next_run_time_when_schedule_enabled_or_time_changed
      - automation.irrigation_update_the_last_time_a_cycle_ended

# Input_Booleans ####################################################
input_boolean:
  irrigation_master_control_switch:
    name: Irrigation - Master Control Switch
    icon: mdi:sprinkler-variant

  cycle1_enable:
    name: Irrigation - Enable schedule
    icon: mdi:pipe
  cycle2_enable:
    name: Irrigation - Enable schedule
    icon: mdi:pipe

  cycle1_enable_saved_state:
    name: Irrigation - Save state of the cycle1
    icon: mdi:content-save
  cycle2_enable_saved_state:
    name: Irrigation - Save state of the cycle2
    icon: mdi:content-save

  cycle1_use_sensor_data:
    name: Irrigation - Use sensor data
    icon: mdi:thermometer-lines
  cycle2_use_sensor_data:
    name: Irrigation - Use sensor data
    icon: mdi:thermometer-lines

  cycle1_manual_run:
    name: Irrigation - Run morning cycle now
    icon: mdi:arrow-right-drop-circle
  cycle2_manual_run:
    name: Irrigation - Run afternoon cycle now
    icon: mdi:arrow-right-drop-circle

  cycle1_running:
    name: Irrigation - Cycle 1 running
    icon: mdi:run
  cycle2_running:
    name: Irrigation - Cycle 2 running
    icon: mdi:run

# Input_Texts #######################################################
input_text:
  current_zone:
    name: Irrigation - Current zone
    icon: mdi:select-marker

# Input_Selects ####################################################\
input_select:

  cycle1_watering_days:
    name: Irrigation - Morning cycle watering days
    options:
      - 'Täglich'
      - 'Alle 2 Tage'
      - 'Alle 3 Tage'
      - 'Einmal'
    icon: mdi:calendar

  cycle2_watering_days:
    name: Irrigation - Afternoon cycle watering days
    options:
      - 'Täglich'
      - 'Alle 2 Tage'
      - 'Alle 3 Tage'
      - 'Einmal'
    icon: mdi:calendar

  cycle1_schedule_time:
    name: Irrigation - Morning cycle schedule start time
    options:
      - '00:00'
      - '00:15'
      - '00:30'
      - '00:45'
      - '01:00'
      - '01:15'
      - '01:30'
      - '01:45'
      - '02:00'
      - '02:15'
      - '02:30'
      - '02:45'
      - '03:00'
      - '03:15'
      - '03:30'
      - '03:45'
      - '04:00'
      - '04:15'
      - '04:30'
      - '04:45'
      - '05:00'
      - '05:15'
      - '05:30'
      - '05:45'
      - '06:00'
      - '06:15'
      - '06:30'
      - '06:45'
      - '07:00'
      - '07:15'
      - '07:30'
      - '07:45'
      - '08:00'
      - '08:15'
      - '08:30'
      - '08:45'
      - '09:00'
      - '09:15'
      - '09:30'
      - '09:45'
      - '10:00'
      - '10:15'
      - '10:30'
      - '10:45'
      - '11:00'
      - '11:15'
      - '11:30'
      - '11:45'
      - '12:00'
      - '12:15'
      - '12:30'
      - '12:45'
      - '13:00'
      - '13:15'
      - '13:30'
      - '13:45'
      - '14:00'
      - '14:15'
      - '14:30'
      - '14:45'
      - '15:00'
      - '15:15'
      - '15:30'
      - '15:45'
      - '16:00'
      - '16:15'
      - '16:30'
      - '16:45'
      - '17:00'
      - '17:15'
      - '17:30'
      - '17:45'
      - '18:00'
      - '18:15'
      - '18:30'
      - '18:45'
      - '19:00'
      - '19:15'
      - '19:30'
      - '19:45'
      - '20:00'
      - '20:15'
      - '20:30'
      - '20:45'
      - '21:00'
      - '21:15'
      - '21:30'
      - '21:45'
      - '22:00'
      - '22:15'
      - '22:30'
      - '22:45'
      - '23:00'
      - '23:15'
      - '23:30'
      - '23:45'
    icon: mdi:alarm

  cycle2_schedule_time:
    name: Irrigation - Afternoon cycle schedule start time
    options:
      - '00:00'
      - '00:15'
      - '00:30'
      - '00:45'
      - '01:00'
      - '01:15'
      - '01:30'
      - '01:45'
      - '02:00'
      - '02:15'
      - '02:30'
      - '02:45'
      - '03:00'
      - '03:15'
      - '03:30'
      - '03:45'
      - '04:00'
      - '04:15'
      - '04:30'
      - '04:45'
      - '05:00'
      - '05:15'
      - '05:30'
      - '05:45'
      - '06:00'
      - '06:15'
      - '06:30'
      - '06:45'
      - '07:00'
      - '07:15'
      - '07:30'
      - '07:45'
      - '08:00'
      - '08:15'
      - '08:30'
      - '08:45'
      - '09:00'
      - '09:15'
      - '09:30'
      - '09:45'
      - '10:00'
      - '10:15'
      - '10:30'
      - '10:45'
      - '11:00'
      - '11:15'
      - '11:30'
      - '11:45'
      - '12:00'
      - '12:15'
      - '12:30'
      - '12:45'
      - '13:00'
      - '13:15'
      - '13:30'
      - '13:45'
      - '14:00'
      - '14:15'
      - '14:30'
      - '14:45'
      - '15:00'
      - '15:15'
      - '15:30'
      - '15:45'
      - '16:00'
      - '16:15'
      - '16:30'
      - '16:45'
      - '17:00'
      - '17:15'
      - '17:30'
      - '17:45'
      - '18:00'
      - '18:15'
      - '18:30'
      - '18:45'
      - '19:00'
      - '19:15'
      - '19:30'
      - '19:45'
      - '20:00'
      - '20:15'
      - '20:30'
      - '20:45'
      - '21:00'
      - '21:15'
      - '21:30'
      - '21:45'
      - '22:00'
      - '22:15'
      - '22:30'
      - '22:45'
      - '23:00'
      - '23:15'
      - '23:30'
      - '23:45'
    icon: mdi:alarm

# Input_Datetimes ###################################################
input_datetime:
  cycle1_next_run_time:
    name: Irrigation - Next run time of the cycle1
    has_date: true
    has_time: true
    icon: mdi:clock-out

  cycle2_next_run_time:
    name: Irrigation - Next run time of the cycle2
    has_date: true
    has_time: true
    icon: mdi:clock-out

# Input_Numbers #####################################################
input_number:
  cycle1_zone1_duration:
    name: Irrigation - Zone 1 duration
    min: 0
    max: 90
    step: 1
    icon: mdi:camera-timer
    unit_of_measurement: min
  cycle1_zone2_duration:
    name: Irrigation - Zone 2 duration
    min: 0
    max: 90
    step: 1
    icon: mdi:camera-timer
    unit_of_measurement: min

  cycle2_zone1_duration:
    name: Irrigation - Zone 1 duration
    min: 0
    max: 90
    step: 1
    icon: mdi:camera-timer
    unit_of_measurement: min
  cycle2_zone2_duration:
    name: Irrigation - Zone 2 duration
    min: 0
    max: 90
    step: 1
    icon: mdi:camera-timer
    unit_of_measurement: min

  # The temperature above which the irrigation will started
  cycle1_temperature_threshold:
    name: Irrigation - Temperature threshold
    min: 10
    max: 30
    icon: mdi:thermometer
    unit_of_measurement: "°C"
  cycle2_temperature_threshold:
    name: Irrigation - Temperature threshold
    min: 10
    max: 30
    icon: mdi:thermometer
    unit_of_measurement: "°C"

  # The moisture below which the irrigation will started
  zone1_moisture_threshold:
    name: Irrigation - Moisture threshold
    min: 5
    max: 30
    icon: mdi:water-percent
    unit_of_measurement: "%"
  zone2_moisture_threshold:
    name: Irrigation - Moisture threshold
    min: 5
    max: 30
    icon: mdi:water-percent
    unit_of_measurement: "%"

# Timers ############################################################
timer:
  zone_duration:
    name: Irrigation - Time remaining

# Template sensors ##################################################
template:
  - sensor:
    - name: Cycle1 next run time
      unique_id: cycle1_next_run_time
      state: >-
        {% if is_state('input_boolean.cycle1_enable', 'on') %}
          {%- set date = state_attr('input_datetime.cycle1_next_run_time', 'timestamp') %}
          {% set weekdays = ["Sonntag", "Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag"] %}
          {% set weekdays_short = ["So", "Mo", "Di", "Mi", "Do", "Fr", "Sa"] %}
          {% set months = ["Januar", "Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "Nowember", "Dezember"] %}
          {% set months_short = ["Jan", "Feb", "Mrz", "Apr", "Mai", "Jun", "Jul", "Aug", "Sep", "Okt", "Now", "Dez"] %}
          {% set w = date | timestamp_custom("%w") | int(0) %}
          {% set m = date | timestamp_custom("%m") | int(0) -%}
          {{ weekdays_short[w] }} {{ date | timestamp_custom('%d.%m.%Y %H:%M:%S', true) }}
        {% else %}
          -
        {% endif %}
      icon: mdi:clock-start

    - name: Cycle2 next run time
      unique_id: cycle2_next_run_time
      state: >-
        {% if is_state('input_boolean.cycle2_enable', 'on') %}
          {%- set date = state_attr('input_datetime.cycle2_next_run_time', 'timestamp') %}
          {% set weekdays = ["Sonntag", "Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag"] %}
          {% set weekdays_short = ["So", "Mo", "Di", "Mi", "Do", "Fr", "Sa"] %}
          {% set months = ["Januar", "Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "Nowember", "Dezember"] %}
          {% set months_short = ["Jan", "Feb", "Mrz", "Apr", "Mai", "Jun", "Jul", "Aug", "Sep", "Okt", "Now", "Dez"] %}
          {% set w = date | timestamp_custom("%w") | int(0) %}
          {% set m = date | timestamp_custom("%m") | int(0) -%}
          {{ weekdays_short[w] }} {{ date | timestamp_custom('%d.%m.%Y %H:%M:%S', true) }}
        {% else %}
          -
        {% endif %}
      icon: mdi:clock-start

    - name: Cycle running
      unique_id: cycle_running
      state: >-
        {% if is_state('input_boolean.cycle1_running', 'on') %}
          Morgen
        {% elif is_state('input_boolean.cycle2_running', 'on') %}
          Abend
        {% else %}
          -
        {% endif %}
      icon: >-
        {% if is_state('input_boolean.cycle1_running', 'on') or
              is_state('input_boolean.cycle2_running', 'on') %}
          mdi:water-pump
        {% else %}
          mdi:water-pump-off
        {% endif %}

    - name: Zone being watered
      unique_id: zone_being_watered
      state: "{{ states('input_text.current_zone') }}"
      icon: mdi:fountain

# Sensors ###########################################################
# sensor:
  # - platform: template
  #   sensors:

      # cycle1_next_run_time:
      #   friendly_name: "Next scheduled run time"
      #   value_template: >
      #     {% if is_state('input_boolean.cycle1_enable', 'on') %}
      #       {%- set date = state_attr('input_datetime.cycle1_next_run_time', 'timestamp') %}
      #       {% set weekdays = ["Sonntag", "Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag"] %}
      #       {% set weekdays_short = ["So", "Mo", "Di", "Mi", "Do", "Fr", "Sa"] %}
      #       {% set months = ["Januar", "Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "Nowember", "Dezember"] %}
      #       {% set months_short = ["Jan", "Feb", "Mrz", "Apr", "Mai", "Jun", "Jul", "Aug", "Sep", "Okt", "Now", "Dez"] %}
      #       {% set w = date | timestamp_custom("%w") | int(0) %}
      #       {% set m = date | timestamp_custom("%m") | int(0) -%}
      #       {{ weekdays_short[w] }} {{ date | timestamp_custom("%d") }} {{ months_short[m-1] }} um {{ date | timestamp_custom("%H:%M") }}
      #     {% else %}
      #       -
      #     {% endif %}
      #   icon_template: 'mdi:clock-start'

      # cycle2_next_run_time:
      #   friendly_name: "Next scheduled run time"
      #   value_template: >
      #     {% if is_state('input_boolean.cycle2_enable', 'on') %}
      #       {%- set date = state_attr('input_datetime.cycle2_next_run_time', 'timestamp') %}
      #       {% set weekdays = ["Sonntag", "Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag"] %}
      #       {% set weekdays_short = ["So", "Mo", "Di", "Mi", "Do", "Fr", "Sa"] %}
      #       {% set months = ["Januar", "Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "Nowember", "Dezember"] %}
      #       {% set months_short = ["Jan", "Feb", "Mrz", "Apr", "Mai", "Jun", "Jul", "Aug", "Sep", "Okt", "Now", "Dez"] %}
      #       {% set w = date | timestamp_custom("%w") | int(0) %}
      #       {% set m = date | timestamp_custom("%m") | int(0) -%}
      #       {{ weekdays_short[w] }} {{ date | timestamp_custom("%d") }} {{ months_short[m-1] }} um {{ date | timestamp_custom("%H:%M") }}
      #     {% else %}
      #       -
      #     {% endif %}
      #   icon_template: 'mdi:clock-start'

      # cycle_running:
      #   friendly_name: "Cycle Running"
      #   value_template: >
      #     {% if is_state('input_boolean.cycle1_running', 'on') %}
      #       Morgen
      #     {% elif is_state('input_boolean.cycle2_running', 'on') %}
      #       Abend
      #     {% else %}
      #       -
      #     {% endif %}
      #   icon_template: >
      #     {% if is_state('input_boolean.cycle1_running', 'on') or
      #           is_state('input_boolean.cycle2_running', 'on') %}
      #       mdi:water-pump
      #     {% else %}
      #       mdi:water-pump-off
      #     {% endif %}

      # zone_being_watered:
      #   friendly_name: "Zone being watered"
      #   value_template: "{{ states('input_text.current_zone') }}"
      #   icon_template: 'mdi:fountain'

homeassistant:
  customize:

    group.irrigation_switches:
      friendly_name: "Ventile"

    group.irrigation_automations:
      friendly_name: "Automatisierungen"

    # Input Boolean #################################################
    input_boolean.irrigation_master_control_switch:
      friendly_name: "Bewässerungsautomat"
      icon: mdi:sprinkler-variant

    input_boolean.cycle1_enable:
      friendly_name: Zeitplan aktivieren
      icon: mdi:calendar-multiple-check

    input_boolean.cycle2_enable:
      friendly_name: Zeitplan aktivieren
      icon: mdi:calendar-multiple-check

    input_boolean.cycle1_use_sensor_data:
      friendly_name: "Sensordaten verwenden"
      icon: mdi:thermometer-lines

    input_boolean.cycle2_use_sensor_data:
      friendly_name: "Sensordaten verwenden"
      icon: mdi:thermometer-lines

    input_boolean.cycle1_manual_run:
      friendly_name: "Morgenzyklus starten"
      icon: mdi:weather-sunset-up

    input_boolean.cycle2_manual_run:
      friendly_name: "Abendzyklus starten"
      icon: mdi:weather-sunset-down

    # Input Select ##################################################
    input_select.cycle1_watering_days:
      friendly_name: Bewässerungstage am Morgen

    input_select.cycle2_watering_days:
      friendly_name: Bewässerungstage am Abend

    input_select.cycle1_schedule_time:
      friendly_name: Startzeit des Morgenszyklus

    input_select.cycle2_schedule_time:
      friendly_name: Startzeit des Abendszyklus

    # Input Number ##################################################
    input_number.cycle1_zone1_duration:
      friendly_name: Hinten Dauer

    input_number.cycle1_zone2_duration:
      friendly_name: Vorne Dauer

    input_number.cycle2_zone1_duration:
      friendly_name: Hinten Dauer

    input_number.cycle2_zone2_duration:
      friendly_name: Vorne Dauer

    input_number.cycle1_temperature_threshold:
      friendly_name: Morgentemp. >=
      icon: mdi:thermometer

    input_number.cycle2_temperature_threshold:
      friendly_name: Abendtemp. >=
      icon: mdi:thermometer

    input_number.zone1_moisture_threshold:
      friendly_name: Bodenfeuchte vorne
      icon: mdi:water-percent

    input_number.zone2_moisture_threshold:
      friendly_name: Bodenfeuchte hinten
      icon: mdi:water-percent

    # Timer #########################################################
    timer.zone_duration:
      friendly_name: Verbleibende Zeit

    # Sensors #######################################################
    sensor.cycle1_next_run_time:
      friendly_name: "Nächste geplante Laufzeit"

    sensor.cycle2_next_run_time:
      friendly_name: "Nächste geplante Laufzeit"

    sensor.cycle_running:
      friendly_name: "Aktueller Zyklus"

    sensor.zone_being_watered:
      friendly_name: "Bewässerte Zone"
