# Automations #######################################################
automation:
  # Отключение насоса, при отключении автоматизации полива
  - id: irrigation_failsafe_pump_control_switch
    alias: Irrigation - Failsafe Pump Control Switch
    description: "Отключение насоса, при отключении автоматизации полива"

    triggers:
      - trigger: state
        entity_id: input_boolean.irrigation_master_control_switch
        to: "off"

    actions:
      - action: switch.turn_off
        entity_id: switch.irrigation_pump

  # Включение насоса, если открылся один из клапанов
  - id: irrigation_pump_on
    alias: Irrigation - Pump ON
    description: "Включение насоса, если открылся один из клапанов"

    triggers:
      - trigger: state
        entity_id: switch.irrigation_valves
        # entity_id: group.irrigation_switches
        to: "on"
        for: "00:00:01"

    conditions:
      - condition: state
        entity_id: switch.irrigation_pump
        state: "off"

    actions:
      - action: switch.turn_on
        entity_id: switch.irrigation_pump

  # Выключение насоса, если закрыты все клапаны с задержкой для смены зоны полива
  - id: irrigation_pump_off
    alias: Irrigation - Pump OFF
    description: "Выключение насоса, если закрыты все клапаны с задержкой для смены зоны полива"

    triggers:
      - trigger: state
        entity_id: switch.irrigation_valves
        # entity_id: group.irrigation_switches
        to: "off"
        for: "00:00:04"

      - trigger: time_pattern
        # This will match every 15 minutes
        minutes: "/15"

    conditions:
      - condition: and
        conditions:
          - condition: state
            entity_id: switch.irrigation_valves
            # entity_id: group.irrigation_switches
            state: "off"
          - condition: state
            entity_id: switch.irrigation_zone3_valve
            state: "off"

    actions:
      - action: switch.turn_off
        entity_id: switch.irrigation_pump

  # Включение насоса для подкачки
  - id: irrigation_regular_pumping
    alias: Irrigation - Regular pumping
    description: "Регулярная подкачка воды"

    triggers:
      - trigger: time_pattern
        hours: "/4"
        minutes: "2"

    conditions:
      - condition: state
        entity_id: switch.irrigation_pump
        state: "off"

    actions:
      - action: switch.turn_on
        entity_id: switch.irrigation_pump
      - delay: 15
      - action: switch.turn_off
        entity_id: switch.irrigation_pump
