# Irrigation - Global variables and scripts

# Switches ##########################################################
switch:
  - platform: template
    switches:
      irrigation:
        friendly_name: Irrigation - Bewässerungsautomat
        unique_id: irrigation_manual_switch
        value_template: "{{ is_state('input_boolean.irrigation_cycle1_manual_run', 'on') }}"
        icon_template: "{{ iif(is_state('input_boolean.irrigation_cycle1_manual_run', 'on'), 'mdi:fountain', 'mdi:water-pump-off') }}"
        turn_on:
          service: input_boolean.turn_on
          target:
            entity_id: input_boolean.irrigation_cycle1_manual_run
        turn_off:
          service: input_boolean.turn_off
          target:
            entity_id: input_boolean.irrigation_cycle1_manual_run

  - platform: group
    name: Irrigation - Valves
    unique_id: irrigation_valves
    entities:
      - switch.irrigation_zone1_valve
      - switch.irrigation_zone2_valve

# Groups ############################################################
group:
  # irrigation_switches:
  #   entities:
  #     - switch.irrigation_zone1_valve
  #     - switch.irrigation_zone2_valve
  #     # - switch.irrigation_zone3_valve

  irrigation_automations:
    name: "Irrigation - Automatisierungen"
    entities:
      # Irrigation
      - automation.irrigation_set_next_run_time_when_schedule_enabled_or_time_changed
      - automation.irrigation_run_cycle_1
      - automation.irrigation_run_cycle_2
      - automation.irrigation_run_a_cycle_manually
      - automation.irrigation_cancel_a_manual_cycle
      # - automation.irrigation_cancel_if_it_rains

      # Master Control
      - automation.irrigation_master_control_switch

      # Pump control
      - automation.irrigation_failsafe_pump_control_switch
      - automation.irrigation_pump_on
      - automation.irrigation_pump_off

      # Statistic
      # - automation.irrigation_set_start_end_time
      # - automation.irrigation_daily_to_total

      # Failsafe
      - automation.irrigation_failsafe_master_control_switch
      - automation.irrigation_failsafe_valve_1_on
      - automation.irrigation_failsafe_valve_2_on

# Input_Booleans ####################################################
input_boolean:
  irrigation_master_control_switch:
    name: Irrigation - Bewässerungsautomat
    icon: mdi:sprinkler-variant

  irrigation_cycle1_enable:
    name: Irrigation - Zeitplan aktivieren
    icon: mdi:calendar-multiple-check
  irrigation_cycle2_enable:
    name: Irrigation - Zeitplan aktivieren
    icon: mdi:calendar-multiple-check

  irrigation_cycle1_enable_saved_state:
    name: Irrigation - Speichern der Status des 1 Zyklus
    icon: mdi:content-save
  irrigation_cycle2_enable_saved_state:
    name: Irrigation - Speichern der Status des 2 Zyklus
    icon: mdi:content-save

  irrigation_cycle1_use_sensor_data:
    name: Irrigation - Sensordaten verwenden
    icon: mdi:thermometer-lines
  irrigation_cycle2_use_sensor_data:
    name: Irrigation - Sensordaten verwenden
    icon: mdi:thermometer-lines

  irrigation_cycle1_manual_run:
    name: Irrigation - Morgenzyklus starten
    icon: mdi:weather-sunset-up
  irrigation_cycle2_manual_run:
    name: Irrigation - Abendzyklus starten
    icon: mdi:weather-sunset-down

  irrigation_cycle1_running:
    name: Irrigation - Zyklus 1 läuft
    icon: mdi:run
  irrigation_cycle2_running:
    name: Irrigation - Zyklus 2 läuft
    icon: mdi:run

# Input_Texts #######################################################
input_text:
  irrigation_current_zone:
    name: Irrigation - Aktuelle Zone
    icon: mdi:select-marker

# Input_Selects ####################################################\
input_select:
  irrigation_cycle1_watering_days:
    name: Irrigation - Bewässerungstage am Morgen
    options:
      - "Täglich"
      - "Alle 2 Tage"
      - "Alle 3 Tage"
      - "Einmal"
    icon: mdi:calendar

  irrigation_cycle2_watering_days:
    name: Irrigation - Bewässerungstage am Abend
    options:
      - "Täglich"
      - "Alle 2 Tage"
      - "Alle 3 Tage"
      - "Einmal"
    icon: mdi:calendar

  irrigation_cycle1_schedule_time:
    name: Irrigation - Startzeit des Morgenszyklus
    options:
      - "00:00"
      - "00:15"
      - "00:30"
      - "00:45"
      - "01:00"
      - "01:15"
      - "01:30"
      - "01:45"
      - "02:00"
      - "02:15"
      - "02:30"
      - "02:45"
      - "03:00"
      - "03:15"
      - "03:30"
      - "03:45"
      - "04:00"
      - "04:15"
      - "04:30"
      - "04:45"
      - "05:00"
      - "05:15"
      - "05:30"
      - "05:45"
      - "06:00"
      - "06:15"
      - "06:30"
      - "06:45"
      - "07:00"
      - "07:15"
      - "07:30"
      - "07:45"
      - "08:00"
      - "08:15"
      - "08:30"
      - "08:45"
      - "09:00"
      - "09:15"
      - "09:30"
      - "09:45"
      - "10:00"
      - "10:15"
      - "10:30"
      - "10:45"
      - "11:00"
      - "11:15"
      - "11:30"
      - "11:45"
      - "12:00"
      - "12:15"
      - "12:30"
      - "12:45"
      - "13:00"
      - "13:15"
      - "13:30"
      - "13:45"
      - "14:00"
      - "14:15"
      - "14:30"
      - "14:45"
      - "15:00"
      - "15:15"
      - "15:30"
      - "15:45"
      - "16:00"
      - "16:15"
      - "16:30"
      - "16:45"
      - "17:00"
      - "17:15"
      - "17:30"
      - "17:45"
      - "18:00"
      - "18:15"
      - "18:30"
      - "18:45"
      - "19:00"
      - "19:15"
      - "19:30"
      - "19:45"
      - "20:00"
      - "20:15"
      - "20:30"
      - "20:45"
      - "21:00"
      - "21:15"
      - "21:30"
      - "21:45"
      - "22:00"
      - "22:15"
      - "22:30"
      - "22:45"
      - "23:00"
      - "23:15"
      - "23:30"
      - "23:45"
    icon: mdi:alarm

  irrigation_cycle2_schedule_time:
    name: Irrigation - Startzeit des Abendszyklus
    options:
      - "00:00"
      - "00:15"
      - "00:30"
      - "00:45"
      - "01:00"
      - "01:15"
      - "01:30"
      - "01:45"
      - "02:00"
      - "02:15"
      - "02:30"
      - "02:45"
      - "03:00"
      - "03:15"
      - "03:30"
      - "03:45"
      - "04:00"
      - "04:15"
      - "04:30"
      - "04:45"
      - "05:00"
      - "05:15"
      - "05:30"
      - "05:45"
      - "06:00"
      - "06:15"
      - "06:30"
      - "06:45"
      - "07:00"
      - "07:15"
      - "07:30"
      - "07:45"
      - "08:00"
      - "08:15"
      - "08:30"
      - "08:45"
      - "09:00"
      - "09:15"
      - "09:30"
      - "09:45"
      - "10:00"
      - "10:15"
      - "10:30"
      - "10:45"
      - "11:00"
      - "11:15"
      - "11:30"
      - "11:45"
      - "12:00"
      - "12:15"
      - "12:30"
      - "12:45"
      - "13:00"
      - "13:15"
      - "13:30"
      - "13:45"
      - "14:00"
      - "14:15"
      - "14:30"
      - "14:45"
      - "15:00"
      - "15:15"
      - "15:30"
      - "15:45"
      - "16:00"
      - "16:15"
      - "16:30"
      - "16:45"
      - "17:00"
      - "17:15"
      - "17:30"
      - "17:45"
      - "18:00"
      - "18:15"
      - "18:30"
      - "18:45"
      - "19:00"
      - "19:15"
      - "19:30"
      - "19:45"
      - "20:00"
      - "20:15"
      - "20:30"
      - "20:45"
      - "21:00"
      - "21:15"
      - "21:30"
      - "21:45"
      - "22:00"
      - "22:15"
      - "22:30"
      - "22:45"
      - "23:00"
      - "23:15"
      - "23:30"
      - "23:45"
    icon: mdi:alarm

# Input_Datetimes ###################################################
input_datetime:
  irrigation_cycle1_next_run_time:
    name: Irrigation - Geplanter Start am Morgen
    has_date: true
    has_time: true
    icon: mdi:clock-out

  irrigation_cycle2_next_run_time:
    name: Irrigation - Geplanter Start am Abend
    has_date: true
    has_time: true
    icon: mdi:clock-out

# Input_Numbers #####################################################
input_number:
  irrigation_cycle1_zone1_duration:
    name: Irrigation - Hinter Dauer am Morgen
    min: 0
    max: 90
    step: 1
    icon: mdi:camera-timer
    unit_of_measurement: min
  irrigation_cycle1_zone2_duration:
    name: Irrigation - Vorne Dauer am Morgen
    min: 0
    max: 90
    step: 1
    icon: mdi:camera-timer
    unit_of_measurement: min

  irrigation_cycle2_zone1_duration:
    name: Irrigation - Hinter Dauer am Abend
    min: 0
    max: 90
    step: 1
    icon: mdi:camera-timer
    unit_of_measurement: min
  irrigation_cycle2_zone2_duration:
    name: Irrigation - Vorne Dauer am Abend
    min: 0
    max: 90
    step: 1
    icon: mdi:camera-timer
    unit_of_measurement: min

  # The temperature above which the irrigation will started
  irrigation_cycle1_temperature_threshold:
    name: Irrigation - Morgenstemp. >=
    min: 10
    max: 30
    icon: mdi:thermometer
    unit_of_measurement: "°C"
  irrigation_cycle2_temperature_threshold:
    name: Irrigation - Abendtemp. >=
    min: 10
    max: 30
    icon: mdi:thermometer
    unit_of_measurement: "°C"

  # The moisture below which the irrigation will started
  irrigation_zone1_moisture_threshold:
    name: Irrigation - Bodenfeuchte vorne
    min: 5
    max: 45
    icon: mdi:water-percent
    unit_of_measurement: "%"
  irrigation_zone2_moisture_threshold:
    name: Irrigation - Bodenfeuchte hinten
    min: 5
    max: 45
    icon: mdi:water-percent
    unit_of_measurement: "%"

# Timers ############################################################
timer:
  irrigation_zone_duration:
    name: Irrigation - Verbleibende Zeit

# Template sensors ##################################################
template:
  - sensor:
      - name: Irrigation Cycle1 next run time
        unique_id: irrigation_cycle1_next_run_time
        state: >-
          {% if is_state('input_boolean.irrigation_cycle1_enable', 'on') %}
            {%- set date = state_attr('input_datetime.irrigation_cycle1_next_run_time', 'timestamp') %}
            {% set weekdays = ["Sonntag", "Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag"] %}
            {% set weekdays_short = ["So", "Mo", "Di", "Mi", "Do", "Fr", "Sa"] %}
            {% set months = ["Januar", "Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "Nowember", "Dezember"] %}
            {% set months_short = ["Jan", "Feb", "Mrz", "Apr", "Mai", "Jun", "Jul", "Aug", "Sep", "Okt", "Now", "Dez"] %}
            {% set w = date | timestamp_custom("%w") | int(0) %}
            {% set m = date | timestamp_custom("%m") | int(0) -%}
            {{ weekdays_short[w] }} {{ date | timestamp_custom('%d.%m.%Y %H:%M:%S', true) }}
          {% else %}
            -
          {% endif %}
        icon: mdi:clock-start

      - name: Irrigation Cycle2 next run time
        unique_id: irrigation_cycle2_next_run_time
        state: >-
          {% if is_state('input_boolean.irrigation_cycle2_enable', 'on') %}
            {%- set date = state_attr('input_datetime.irrigation_cycle2_next_run_time', 'timestamp') %}
            {% set weekdays = ["Sonntag", "Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag"] %}
            {% set weekdays_short = ["So", "Mo", "Di", "Mi", "Do", "Fr", "Sa"] %}
            {% set months = ["Januar", "Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "Nowember", "Dezember"] %}
            {% set months_short = ["Jan", "Feb", "Mrz", "Apr", "Mai", "Jun", "Jul", "Aug", "Sep", "Okt", "Now", "Dez"] %}
            {% set w = date | timestamp_custom("%w") | int(0) %}
            {% set m = date | timestamp_custom("%m") | int(0) -%}
            {{ weekdays_short[w] }} {{ date | timestamp_custom('%d.%m.%Y %H:%M:%S', true) }}
          {% else %}
            -
          {% endif %}
        icon: mdi:clock-start

      - name: Irrigation Cycle running
        unique_id: irrigation_cycle_running
        state: >-
          {% if is_state('input_boolean.irrigation_cycle1_running', 'on') %}
            Morgen
          {% elif is_state('input_boolean.irrigation_cycle2_running', 'on') %}
            Abend
          {% else %}
            -
          {% endif %}
        icon: >-
          {% if is_state('input_boolean.irrigation_cycle1_running', 'on') or
                is_state('input_boolean.irrigation_cycle2_running', 'on') %}
            mdi:water-pump
          {% else %}
            mdi:water-pump-off
          {% endif %}

      - name: Irrigation Zone being watered
        unique_id: irrigation_zone_being_watered
        state: "{{ states('input_text.irrigation_current_zone') }}"
        icon: mdi:fountain

homeassistant:
  customize:
    # group.irrigation_switches:
    #   friendly_name: "Ventile"

    # group.irrigation_automations:
    #   friendly_name: "Automatisierungen"

    # Input Boolean #################################################
    # input_boolean.irrigation_master_control_switch:
    #   friendly_name: "Bewässerungsautomat"
    #   icon: mdi:sprinkler-variant

    # input_boolean.irrigation_cycle1_enable:
    #   friendly_name: Irrigation - Zeitplan aktivieren
    #   icon: mdi:calendar-multiple-check

    # input_boolean.irrigation_cycle2_enable:
    #   friendly_name: Irrigation - Zeitplan aktivieren
    #   icon: mdi:calendar-multiple-check

    # input_boolean.irrigation_cycle1_use_sensor_data:
    #   friendly_name: "Sensordaten verwenden"
    #   icon: mdi:thermometer-lines

    # input_boolean.irrigation_cycle2_use_sensor_data:
    #   friendly_name: "Sensordaten verwenden"
    #   icon: mdi:thermometer-lines

    # input_boolean.irrigation_cycle1_manual_run:
    #   friendly_name: "Morgenzyklus starten"
    #   icon: mdi:weather-sunset-up

    # input_boolean.irrigation_cycle2_manual_run:
    #   friendly_name: "Abendzyklus starten"
    #   icon: mdi:weather-sunset-down

    # Input Select ##################################################
    # input_select.irrigation_cycle1_watering_days:
    #   friendly_name: Bewässerungstage am Morgen

    # input_select.irrigation_cycle2_watering_days:
    #   friendly_name: Bewässerungstage am Abend

    # input_select.irrigation_cycle1_schedule_time:
    #   friendly_name: Startzeit des Morgenszyklus

    # input_select.irrigation_cycle2_schedule_time:
    #   friendly_name: Startzeit des Abendszyklus

    # Input Number ##################################################
    # input_number.irrigation_cycle1_zone1_duration:
    #   friendly_name: Hinten Dauer

    # input_number.irrigation_cycle1_zone2_duration:
    #   friendly_name: Vorne Dauer

    # input_number.irrigation_cycle2_zone1_duration:
    #   friendly_name: Hinten Dauer

    # input_number.irrigation_cycle2_zone2_duration:
    #   friendly_name: Vorne Dauer

    # input_number.irrigation_cycle1_temperature_threshold:
    #   friendly_name: Morgentemp. >=
    #   icon: mdi:thermometer

    # input_number.irrigation_cycle2_temperature_threshold:
    #   friendly_name: Abendtemp. >=
    #   icon: mdi:thermometer

    # input_number.irrigation_zone1_moisture_threshold:
    #   friendly_name: Bodenfeuchte vorne
    #   icon: mdi:water-percent

    # input_number.irrigation_zone2_moisture_threshold:
    #   friendly_name: Bodenfeuchte hinten
    #   icon: mdi:water-percent

    # Timer #########################################################
    # timer.irrigation_zone_duration:
    #   friendly_name: Verbleibende Zeit

    # Sensors #######################################################
    sensor.irrigation_cycle1_next_run_time:
      friendly_name: "Irrigation - Geplanter Start am Morgen"

    sensor.irrigation_cycle2_next_run_time:
      friendly_name: "Irrigation - Geplanter Start am Abend"

    sensor.irrigation_cycle_running:
      friendly_name: "Irrigation - Aktueller Zyklus"

    sensor.irrigation_zone_being_watered:
      friendly_name: "Irrigation - Bewässerte Zone"

    switch.irrigation_valves:
      friendly_name: "Irrigation - Ventile"
