# Android IP Webcamera package
# Samsung SM-G925X

# Component #########################################################
android_ip_webcam:
  - name: CamGarage
    host: !secret cams6_ip
    port: !secret cams6_port
    username: !secret cams6_user
    password: !secret cams6_pass
#    scan_interval: Default is 10 seconds. Defines the update interval of the phone.
    motion_sensor: enable
    sensors:
      - audio_connections
      - battery_level
      - battery_temp
      - battery_voltage
      - light
      - motion
      - pressure
      - proximity
      - sound
      - video_connections
    switches:
      - exposure_lock
      - ffc
      - focus
      - gps_active
      - night_vision
      - overlay
      - torch
      - whitebalance_lock
      - video_recording

# Automation ########################################################
automation:
# Aufnahme ########
#  - id: camgaragerecording
#    alias: Camera Garage Recording
#    trigger:
#    - platform: time_pattern
#      minutes: "/5"
#    - platform: state
#      entity_id: switch.camgarage_video_recording
#      to: "off"
#    condition:
#    - condition: state
#      entity_id: switch.camgarage_video_recording
#      state: "off"
#    action:
#    - service: switch.turn_on
#      data:
#        entity_id: switch.camgarage_video_recording

# Nachtmodus ######
  - id: camgaragenighton
    alias: Camera Garage Night On
    trigger:
    - platform: numeric_state
      entity_id: sensor.camgarage_light_level
      below: "5"
    condition:
    - condition: state
      entity_id: switch.camgarage_night_vision
      state: "off"
    action:
    - service: switch.turn_on
      data:
        entity_id: switch.camgarage_night_vision

  - id: camgaragenightoff
    alias: Camera Garage Night Off
    trigger:
    - platform: numeric_state
      entity_id: sensor.camgarage_light_level
      above: "5"
    condition:
    - condition: state
      entity_id: switch.camgarage_night_vision
      state: "on"
    action:
    - service: switch.turn_off
      data:
        entity_id: switch.camgarage_night_vision


# Groups ############################################################
group:
# Switches ########
  camgarage_switch:
    name: Kamera Garage Switch
# Deprecated    control: hidden
    entities:
      - switch.camgarage_exposure_lock
      - switch.camgarage_focus
      - switch.camgarage_frontfacing_camera
      - switch.camgarage_gps_active
      - switch.camgarage_night_vision
      - switch.camgarage_overlay
      - switch.camgarage_torch
      - switch.camgarage_video_recording
      - switch.camgarage_white_balance_lock

# Sensors #########
  camgarage_sensor:
    name: Kamera Garage Sensor
    entities:
      - binary_sensor.camgarage_motion_active
      - sensor.camgarage_motion
      - sensor.camgarage_sound
      - sensor.camgarage_pressure
      - sensor.camgarage_proximity
      - sensor.camgarage_light_level
      - sensor.camgarage_battery_level
      - sensor.camgarage_battery_temperature
      - sensor.camgarage_battery_voltage
      - sensor.camgarage_audio_connections
      - sensor.camgarage_video_connections

# Customize #########################################################
homeassistant:
  customize:
# Switches ########
    switch.camgarage_torch:
      friendly_name: Licht
    switch.camgarage_video_recording:
      friendly_name: Videoaufnahme
    switch.camgarage_night_vision:
      friendly_name: Nachtmodus
    switch.camgarage_overlay:
      friendly_name: Beschriftung
    switch.camgarage_frontfacing_camera:
      friendly_name: Frontkamera
    switch.camgarage_focus:
      friendly_name: Fokus
    switch.camgarage_exposure_lock:
      friendly_name: Belichtungsperre
    switch.camgarage_white_balance_lock:
      friendly_name: Weißabgleichsperre
    switch.camgarage_gps_active:
      friendly_name: GPS Aktiviert

# Sensors #########
    sensor.camgarage_battery_level:
      friendly_name: Akkuladestand
    sensor.camgarage_battery_temperature:
      friendly_name: Akkutemperature
      unit_of_measurement: "°C"
    sensor.camgarage_battery_voltage:
      friendly_name: Akkuspannung
    binary_sensor.camgarage_motion_active:
      friendly_name: Bewegung erkannt
    sensor.camgarage_motion:
      friendly_name: Bewegung
    sensor.camgarage_light_level:
      friendly_name: Lichtstärke
    sensor.camgarage_proximity:
      friendly_name: Annäherung
    sensor.camgarage_sound:
      friendly_name: Geräusch
    sensor.camgarage_video_connections:
      friendly_name: Videoverbindungen
      unit_of_measurement: ""
    sensor.camgarage_audio_connections:
      friendly_name: Audioverbindungen
      unit_of_measurement: ""
    sensor.camgarage_pressure:
      friendly_name: Druck

# Binary Sensor #####################################################
#binary_sensor:
#  - platform: rest
#    name: Kitchen Motion
#    sensor_class: motion
#    resource: http://IP:8080/sensors.json?sense=motion_active
#    value_template: "{{ value_json.motion_active.data[0][1][0] | round(0) }}"

#media_player:
#  - platform: vlc
#    name: speaker
#
#camera:
#  - platform: ffmpeg
#    input: https://192.168.2.210:8080/audio.wav
#
#  - platform: generic
#    name: CamGarage ulaw
#    username: !secret cams6_user
#    password: !secret cams6_pass
#    still_image_url: http://192.168.2.210:8080/shot.jpg
#    stream_source: rtsp://192.168.2.210:8080/h264_ulaw.sdp
#
#  - platform: generic
#    name: CamGarage pcm
#    username: !secret cams6_user
#    password: !secret cams6_pass
#    verify_ssl: false
#    still_image_url: https://192.168.2.210:8080/shot.jpg
#    stream_source: https://192.168.2.210:8080/audio.wav
#
#  - platform: mjpeg
#    name: CamGarage mjpeg
#    username: !secret cams6_user
#    password: !secret cams6_pass
#    mjpeg_url: http://192.168.2.210:8080/video
#
#  - platform: onvif
#    name: CamGarage onvif
#    username: !secret cams6_user
#    password: !secret cams6_pass
#    host: 192.168.2.210
#    port: 8080
