# Automations and scripts for covers

# Cover #############################################################
cover:
  - platform: group
    unique_id: rolladen
    name: rolladen
    entities:
      - cover.rollade_1
      - cover.rollade_2
      - cover.rollade_3
      - cover.rollade_4

# Input Text ########################################################
input_text:
  rolladen_last_action:
    name: Rolladen - Last action
    initial: opening
    icon: mdi:window-shutter-open
  rollade_1_last_action:
    name: Rolladen 1 - Last action
    initial: opening
    icon: mdi:window-shutter-open
  rollade_2_last_action:
    name: Rolladen 2 - Last action
    initial: opening
    icon: mdi:window-shutter-open
  rollade_3_last_action:
    name: Rolladen 3 - Last action
    initial: opening
    icon: mdi:window-shutter-open
  rollade_4_last_action:
    name: Rolladen 4 - Last action
    initial: opening
    icon: mdi:window-shutter-open

  markise_last_action:
    name: Markise - Last action
    initial: opening
    icon: mdi:storefront-outline
  seitenmarkise_last_action:
    name: Seitenmarkise - Last action
    initial: opening
    icon: mdi:storefront-outline

# Automation ########################################################
automation:
  # Rolladen group last action
  - id: set_rolladen_last_action
    alias: Rolladen - Set last action
    mode: parallel
    triggers:
      - trigger: state
        entity_id:
          - cover.rolladen
          - cover.rollade_4
          - cover.rollade_3
          - cover.rollade_1
          - cover.rollade_2
          - cover.markise
          - cover.seitenmarkise

    conditions:
      - condition: or
        conditions:
          - "{{ trigger.from_state.state == 'opening' }}"
          - "{{ trigger.from_state.state == 'closing' }}"

    actions:
      - action: input_text.set_value
        target:
          entity_id: input_text.{{ trigger.to_state.object_id }}_last_action
        data:
          value: "{{ trigger.from_state.state }}"

# Scripts ###########################################################
script:
  #######################################
  # Script to control covers with one button.
  # Open -> Stop -> Close -> Stop -> Open
  # Parameters:
  #   entity_id: full cover entity ID (with 'cover.' prefix)
  #######################################
  cover_one_button:
    alias: Cover - One button control
    mode: parallel
    fields:
      entity_id:
        description: Full cover entity ID with 'cover.' prefix
        example: "cover.rolladen"
    sequence:
      - variables:
          input_text_entity: >
            input_text.{{ entity_id.replace('cover.', '') }}_last_action
      - action: >
          {% set cover_state = states(entity_id) %}
          {% if cover_state in ['opening', 'closing'] %}
            cover.stop_cover
          {% elif is_state(input_text_entity, 'closing')  %}
            cover.open_cover
          {% elif is_state(input_text_entity, 'opening')  %}
            cover.close_cover
          {% else %}
            cover.stop_cover
          {% endif %}
        target:
          entity_id: "{{ entity_id }}"

  #######################################
  # Script to control covers with two buttons.
  # If cover is moving, stop it. Otherwise execute the requested action.
  # Parameters:
  #   entity_id: full cover entity ID (with 'cover.' prefix)
  #   mode: 'open' or 'close'
  #######################################
  cover_start_stop:
    alias: Cover - Two buttons control
    mode: parallel
    fields:
      entity_id:
        description: Full cover entity ID with 'cover.' prefix
        example: "cover.rolladen"
      mode:
        description: Action to perform
        example: "open"
        selector:
          select:
            options:
              - "open"
              - "close"
    sequence:
      - action: >
          {% if states(entity_id) in ['opening', 'closing'] %}
            cover.stop_cover
          {% elif mode == 'open' %}
            cover.open_cover
          {% elif mode == 'close' %}
            cover.close_cover
          {% else %}
            cover.stop_cover
          {% endif %}
        target:
          entity_id: "{{ entity_id }}"

  #######################################
  # Bulk cover control script
  # Parameters:
  #   covers: list of full cover entity IDs
  #   action: 'open', 'close', or 'stop'
  #######################################
  # covers_bulk_control:
  #   alias: Covers - Bulk Control
  #   mode: parallel
  #   fields:
  #     covers:
  #       description: List of cover entities with full entity IDs
  #       example: "cover.rolladen, cover.markise"
  #     action:
  #       description: Action to perform
  #       example: "open"
  #       selector:
  #         select:
  #           options:
  #             - "open"
  #             - "close"
  #             - "stop"
  #   sequence:
  #     - repeat:
  #         for_each: "{{ covers }}"
  #         sequence:
  #           - action: >
  #               {% if action == 'open' %}
  #                 cover.open_cover
  #               {% elif action == 'close' %}
  #                 cover.close_cover
  #               {% else %}
  #                 cover.stop_cover
  #               {% endif %}
  #             target:
  #               entity_id: "{{ repeat.item }}"

# Customize #########################################################
homeassistant:
  customize:
    cover.rolladen:
      friendly_name: Rolladen
