# Garage
# Smartthings integration

# Sensor ##############################
sensor:
  - platform: history_stats
    name: Trockner Betriebszeit Heute
    entity_id: sensor.trockner_dryer_machine_state
    state: "run"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: Trockner Betriebszeit Monat
    entity_id: sensor.trockner_dryer_machine_state
    state: "run"
    type: time
    end: "{{ now() }}"
    duration:
      days: 30

  - platform: history_stats
    name: Trockner Betriebszeit Jahr
    entity_id: sensor.trockner_dryer_machine_state
    state: "run"
    type: time
    end: "{{ now() }}"
    duration:
      days: 365

  - platform: history_stats
    name: Trockner Betriebszeit
    entity_id: sensor.trockner_dryer_machine_state
    state: "run"
    type: time
    start: "{{ 0 }}"
    end: "{{ now() }}"

# utility_meter:
#   trockner_energy_daily:
#     unique_id: trockner_energy_daily
#     source: sensor.trockner_power
#     name: Trockner Energy Daily
#     cycle: daily
#   trockner_energy_monthly:
#     unique_id: trockner_energy_monthly
#     source: sensor.trockner_power
#     name: Trockner Energy Monthly
#     cycle: monthly
#   trockner_energy_yearly:
#     unique_id: trockner_energy_yearly
#     source: sensor.trockner_power
#     name: Trockner Energy Yearly
#     cycle: yearly

homeassistant:
  customize:
    sensor.trockner_betriebszeit_heute:
      icon: mdi:calendar-clock

    sensor.trockner_betriebszeit_monat:
      icon: mdi:calendar-clock

    sensor.trockner_betriebszeit_jahr:
      icon: mdi:calendar-clock

    sensor.trockner_power:
      friendly_name: Leistung (Trockner)

    # sensor.trockner_energy:
    #   friendly_name: Verbrauch (Trockner)
    # sensor.trockner_energy_daily:
    #   friendly_name: Verbrauch Heute (Trockner)
    # sensor.trockner_energy_monthly:
    #   friendly_name: Verbrauch Monatlich (Trockner)
    # sensor.trockner_energy_yearly:
    #   friendly_name: Verbrauch Jährlich (Trockner)
