# FritzBox 7490

# Recorder ##########################################################
recorder:
  exclude:
    entities:
      - sensor.fb_uptime
      - sensor.fb_rate_up
      - sensor.fb_rate_down

# Logbook ###########################################################
logbook:
  exclude:
    entities:
      - sensor.fb_uptime
      - sensor.fb_rate_up
      - sensor.fb_rate_down

#- Sensor ---------------------------------------
sensor:
  - platform: fritzbox_netmonitor
    name: fritz_box
    host: !secret fritz_ip
#--- TEMLPATES ----------------------------------
  - platform: template
    sensors:
#      fb_wan:
#        friendly_name: "FB WAN"
#        icon_template: mdi:wan
#        value_template: "{{ state_attr('sensor.fritz_box','wan_access_type') }}"
#      fb_linked:
#        friendly_name: "FB Leitung"
#        icon_template: mdi:network-outline
#        value_template: "{{ state_attr('sensor.fritz_box','is_linked') }}"
#      fb_connected:
#        friendly_name: "FB Internet"
#        icon_template: mdi:wan
#        value_template: "{{ state_attr('sensor.fritz_box','is_connected') }}"
      fb_ip:
        friendly_name: "FB External IP"
        icon_template: mdi:ip-network-outline
        value_template: "{{ state_attr('sensor.fritz_box','external_ip') }}"
      fb_uptime:
        friendly_name: "FB Betriebszeit"
        icon_template: mdi:progress-clock
        value_template: "{{ '%0.02d:%0.02d:%0.02d' | format(state_attr('sensor.fritz_box','uptime') // 3600, state_attr('sensor.fritz_box','uptime') // 60 % 60, state_attr('sensor.fritz_box','uptime') % 60) }}"

      fb_sent_mb:
        friendly_name: "FB Gesendet"
        icon_template: mdi:upload
        unit_of_measurement: "MB"
        value_template: "{{ (state_attr('sensor.fritz_box','bytes_sent') | float / 1048576) | round(1) }}"
      fb_received_mb:
        friendly_name: "FB Empfangen"
        icon_template: mdi:download
        unit_of_measurement: "MB"
        value_template: "{{ (state_attr('sensor.fritz_box','bytes_received') | float / 1048576) | round(1) }}"

      fb_transm_up:
        friendly_name: "FB Up Speed"
        icon_template: mdi:progress-upload
        unit_of_measurement: "kB/s"
        value_template: "{{ (state_attr('sensor.fritz_box','transmission_rate_up') | float / 1024) | round(1) }}"
      fb_transm_down:
        friendly_name: "FB Down Speed"
        icon_template: mdi:progress-download
        unit_of_measurement: "kB/s"
        value_template: "{{ (state_attr('sensor.fritz_box','transmission_rate_down') | float / 1024) | round(1) }}"

      fb_rate_up:
        friendly_name: "FB Max Upload"
        icon_template: mdi:upload-network-outline
        value_template: "{{ (state_attr('sensor.fritz_box','max_byte_rate_up') | float / 1048576) | round(3) }} MB/s ({{ (state_attr('sensor.fritz_box','max_byte_rate_up') | float * 8 / 1048576) | round(3) }} MBit/s)"
      fb_rate_down:
        friendly_name: "FB Max Download"
        icon_template: mdi:download-network-outline
        value_template: "{{ (state_attr('sensor.fritz_box','max_byte_rate_down') | float / 1048576)|round(3) }} MB/s ({{ (state_attr('sensor.fritz_box','max_byte_rate_down') | float * 8 / 1048576) | round(3) }} MBit/s)"

# Customize #########################################################
#homeassistant:
#  customize:
#    sensor.internetgatewaydevicev2_fritz_box_7490_bytes_received:
#      friendly_name: "FB Empfangen, bytes"
#      icon: mdi:download
#    sensor.internetgatewaydevicev2_fritz_box_7490_bytes_sent:
#      friendly_name: "FB Gesendet, bytes"
#      icon: mdi:upload
#    sensor.internetgatewaydevicev2_fritz_box_7490_kbyte_sec_received:
#      friendly_name: "FB Empfang, kB/s"
#      icon: mdi:progress-download
#    sensor.internetgatewaydevicev2_fritz_box_7490_packets_received:
#      friendly_name: "FB Empfangen, packets"
#      icon: mdi:download
#    sensor.internetgatewaydevicev2_fritz_box_7490_packets_sec_received:
#      friendly_name: "FB Empfang, packets/s"
#      icon: mdi:progress-download
#    sensor.internetgatewaydevicev2_fritz_box_7490_kbyte_sec_sent:
#      friendly_name: "FB Gesendet, kB/s"
#      icon: mdi:progress-upload
#    sensor.internetgatewaydevicev2_fritz_box_7490_packets_sec_sent:
#      friendly_name: "FB Gesendet, packets/s"
#      icon: mdi:progress-upload
#    sensor.internetgatewaydevicev2_fritz_box_7490_packets_sent:
#      friendly_name: "FB Gesendet, packets"
#      icon: mdi:upload
#    sensor.fritzbox_7490_bytes_received:
#      friendly_name: FB Empfangen, bytes
#      icon: mdi:download
#    sensor.fritzbox_7490_bytes_sent:
#      icon: mdi:upload
#    sensor.fritzbox_7490_kbytesec_received:
#      icon: mdi:progress-download
#    sensor.fritzbox_7490_packetssec_received:
#      icon: mdi:progress-download
#    sensor.fritzbox_7490_packetssec_sent:
#      icon: mdi:progress-upload
#    sensor.fritzbox_7490_kbytesec_sent:
#      icon: mdi:progress-upload
#    sensor.fritzbox_7490_packets_received:
#      icon: mdi:download
#    sensor.fritzbox_7490_packets_sent:
#      icon: mdi:upload