# IFTTT Service
# https://ifttt.com/

# IFTTT #############################################################
ifttt:
  key: !secret ifttt_key
# 0.107.2 Пока в основном конфиге


# Automation ########################################################
automation:
  - id: ifttt_webhook
    alias: IFTTT Webhook
    trigger:
    - platform: event
      event_type: ifttt_webhook_received
      event_data:
        action: call_service
    action:
    - service: "{{ trigger.event.data.service }}"
      data:
        entity_id: "{{ trigger.event.data.entity_id }}"

  - id: ifttt_webhook_option
    alias: IFTTT Webhook Option
    trigger:
    - platform: event
      event_type: ifttt_webhook_received
      event_data:
        action: call_option
    action:
    - service: "{{ trigger.event.data.service }}"
      data:
        entity_id: "{{ trigger.event.data.entity_id }}"
        option: "{{ trigger.event.data.option }}"
