# NUC Monitor

# Recorder ##########################################################
recorder:
  exclude:
    entities:
      - sensor.load_15m
      # - sensor.last_boot_local

# Logbook ###########################################################
logbook:
  exclude:
    entities:
      - sensor.load_15m
      # - sensor.last_boot_local

# Template sensor ###################################################
template:
  - sensor:
      # States ################
      - name: CPU load
        unique_id: cpu_load
        state: "{{ (states('sensor.load_15m') | float(0) ) | round(2) }}"
        icon: mdi:memory
        unit_of_measurement: " "

      - name: "Last boot local"
        unique_id: last_boot_local
        state: "{{ as_timestamp(states('sensor.last_boot')) | timestamp_custom('%d.%m.%Y %H:%M') }}"
        icon: mdi:clock-start
        unit_of_measurement: " "

sensor:
  # Command Line
  # - platform: command_line
  #   name: CPU Temp
  #   command: "/bin/cat /sys/class/thermal/thermal_zone0/temp"
  #   unit_of_measurement: "°C"
  #   value_template: "{{ value | multiply(0.001) | round(1) }}"

  # - platform: cpuspeed

  # Raspberry Pi Power Supply Checker
  # - platform: rpi_power
  #   text_state: true

  # System Monitor
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      # - type: disk_use
      #   arg: /
      - type: disk_free
        arg: /
      - type: memory_use_percent
      # - type: memory_use
      - type: memory_free
      - type: swap_use_percent
      # - type: swap_use
      - type: swap_free
      # - type: load_1m
      # - type: load_5m
      - type: load_15m
      - type: network_in
        arg: ens33
      - type: network_out
        arg: ens33
      - type: throughput_network_in
        arg: ens33
      - type: throughput_network_out
        arg: ens33
      # - type: packets_in
      #   arg: ens33
      # - type: packets_out
      #   arg: ens33
      - type: ipv4_address
        arg: ens33
      - type: ipv6_address
        arg: ens33
      - type: processor_use
      # - type: process
      #   arg: octave-cli
      # - type: processor_temperature
      - type: last_boot

# Customize #########################################################
homeassistant:
  customize:
    # Sensor ##########
    sensor.processor_use:
      friendly_name: "CPU use"
    sensor.load_1m:
      unit_of_measurement: ""

    sensor.cpu_load:
      friendly_name: "CPU Load 15m"

    sensor.last_boot_local:
      friendly_name: "Letzter Start"
