# Pi-hole ###########################################################
#pi_hole:
#  host: !secret pihole_host
#  ssl: false
#  verify_ssl: false

# Customize #########################################################
homeassistant:
  customize:
# Sensor ##########
    sensor.pi_hole_ads_blocked_today:
      unit_of_measurement: " "
    sensor.pi_hole_dns_unique_clients:
      unit_of_measurement: " "
    sensor.pi_hole_seen_clients:
      unit_of_measurement: " "
    sensor.pi_hole_dns_unique_domains:
      unit_of_measurement: " "
    sensor.pi_hole_domains_blocked:
      unit_of_measurement: " "
    sensor.pi_hole_dns_queries_cached:
      unit_of_measurement: " "
    sensor.pi_hole_dns_queries_forwarded:
      unit_of_measurement: " "
    sensor.pi_hole_dns_queries_today:
      unit_of_measurement: " "
