# Radio

# Recorder ##########################################################
# recorder:
#   exclude:
#     entities:
#       - input_number.radio_volume
#       - input_select.radio_station
#       - input_select.radio_player
#       # - group.radio
#       - automation.radio_stop
#       - automation.radio_stream
#       - automation.radio_volume
#       - script.radio
#       - script.radio_stop

# Logbook ###########################################################
# logbook:
#   exclude:
#     entities:
#       - input_number.radio_volume
#       - input_select.radio_station
#       - input_select.radio_player
#       # - group.radio
#       - automation.radio_stop
#       - automation.radio_stream
#       - automation.radio_volume
#       - script.radio
#       - script.radio_stop

# Input Numbers #####################################################
# moved to UI
input_number:
  radio_volume:
    name: Lautstärke
    icon: mdi:volume-high
    min: 0
    max: 1
    step: 0.05

# Input Selects #####################################################
input_select:
  radio_station:
    name: "Radio:"
    options:
      - Stop
      - Europa Plus
      - Русское радио
      - Comedy Radio
      - Авторадио
      - Deep House
      - Tropical House
      - Trans House Deep
      - Lo-fi Chillhop
      - Office Lounge
      - Relax Natur
      - Relax FM
      - Relax Gold
      - New Age
      - Pink Floyd
      - Enigma
      - Mainstream
      - Маруся ФМ
      - Sex
    initial: Stop
    icon: mdi:radio

  radio_player:
    name: "Lautsprecher:"
    options:
      - Nest Mini
      - Sound Blaster
      - Home Mini Flur
      - Home Mini Kristina
      - Garten
      - Überall
      - Erdgeschoss
    initial: Nest Mini
    icon: mdi:speaker-wireless

# Automations #######################################################
automation:
  # Stops the radio #
  - id: radio_stop
    alias: Radio - Stop
    trigger:
      - platform: state
        entity_id: input_select.radio_station
        to: "Stop"
    action:
      action: script.radio_stop

  # Streaming the radio
  # home_group определяем в Google Home APP
  - id: radio_stream
    alias: Radio - Stream
    trigger:
      - platform: state
        entity_id: input_select.radio_station
      - platform: state
        entity_id: input_select.radio_player
    action:
      - action: media_player.turn_off
        target:
          entity_id: >-
            {% set entities = {
              'Garten':'media_player.googlehome9539',
              'Nest Mini':'media_player.nest_mini',
              'Sound Blaster':'media_player.soundblaster',
              'Home Mini Flur':'media_player.flur',
              'Home Mini Kristina':'media_player.kristina',
              'Überall':'media_player.home_group',
              'Erdgeschoss':'media_player.erdgeschoss',
              }
            %}
            {{ iif(trigger.from_state in entities, entities[trigger.from_state], 'media_player.nest_mini') }}
      # - action: notify.persistent_notification
      #   data:
      #     message: "{{ trigger.from_state }}"
      - action: script.radio

  # Set radio volume
  - id: radio_volume
    alias: Radio - Volume
    trigger:
      platform: state
      entity_id: input_number.radio_volume
    action:
      action: media_player.volume_set
      data:
        entity_id: >
          {% set entities = {
            'Garten':'media_player.googlehome9539',
            'Nest Mini':'media_player.nest_mini',
            'Sound Blaster':'media_player.soundblaster',
            'Home Mini Flur':'media_player.flur',
            'Home Mini Kristina':'media_player.kristina',
            'Überall':'media_player.home_group',
            'Erdgeschoss':'media_player.erdgeschoss',
            }
          %}
          {% set state = states('input_select.radio_player') %}
          {{ iif(state in entities, entities[state], 'media_player.nest_mini') }}
        volume_level: "{{ states('input_number.radio_volume') }}"

# Scripts ###########################################################
script:
  # Plays the radio
  radio:
    alias: Radio - Wiedergabe
    description: "Turns on the radio"
    icon: mdi:play
    sequence:
      #      - action: media_player.volume_set
      #        data:
      #          entity_id: media_player.google_home
      #          volume_level: "0.25"
      #      - action: media_player.volume_set
      #        data:
      #          entity_id: media_player.soundblaster
      #          volume_level: "0.25"
      #      - action: media_player.volume_set
      #        data:
      #          entity_id: media_player.flur
      #          volume_level: "0.25"
      #      - action: media_player.volume_set
      #        data:
      #          entity_id: media_player.kristina
      #          volume_level: "0.25"
      #      - action: media_extractor.play_media
      - action: media_player.play_media
        target:
          entity_id: >-
            {% set entities = {
              'Garten':'media_player.googlehome9539',
              'Nest Mini':'media_player.nest_mini',
              'Sound Blaster':'media_player.soundblaster',
              'Home Mini Flur':'media_player.flur',
              'Home Mini Kristina':'media_player.kristina',
              'Überall':'media_player.home_group',
              'Erdgeschoss':'media_player.erdgeschoss',
              'Yandex Station':'media_player.yandex_station_lb0000000000002397130000767dab00',
              }
            %}
            {% set state = states('input_select.radio_player') %}
            {{ iif(state in entities, entities[state], 'media_player.nest_mini') }}
        data:
          media_content_type: "music"
          media_content_id: >-
            {% set stations = {
              'Europa Plus':'http://ep256.hostingradio.ru:8052/europaplus256.mp3',
              'Русское радио':'https://rusradio.hostingradio.ru/rusradio96.aacp',
              'Comedy Radio':'https://pub0202.101.ru:8443/stream/air/aac/64/202',
              'Авторадио':'https://pub0202.101.ru:8443/stream/air/aac/64/100',
              'Deep House':'https://pub0101.101.ru/stream/trust/mp3/128/173',
              'Tropical House':'https://pub0201.101.ru/stream/pro/aac/64/364',
              'Trans House Deep':'https://pub0302.101.ru:8443/stream/personal/aacp/64/1691459',
              'Lo-fi Chillhop':'https://pub0201.101.ru/stream/pro/aac/64/358',
              'Office Lounge':'https://pub0201.101.ru/stream/pro/aac/64/30',
              'Relax Natur':'https://pub0101.101.ru/stream/trust/mp3/128/263',
              'Relax FM':'https://pub0202.101.ru:8443/stream/air/aac/64/200',
              'Relax Gold':'https://pub0201.101.ru/stream/trust/mp3/128/266',
              'New Age':'https://pub0101.101.ru/stream/pro/aac/64/120',
              'Pink Floyd':'https://pub0202.101.ru:8443/stream/pro/aac/64/53',
              'Enigma':'https://pub0201.101.ru/stream/pro/aac/64/175',
              'Mainstream':'https://pub0201.101.ru/stream/pro/aac/64/87',
              'Маруся ФМ':'http://radio-holding.ru:9000/marusya_aac_64',
              'Sex':'https://pub0202.101.ru:8443/stream/pro/aac/64/27',
              }
            %}
            {% set state = states('input_select.radio_station') %}
            {{ iif(state in stations, stations[state], 'Stop') }}

  radio_stop:
    alias: Radio - Stop
    description: "Turns off the radio"
    icon: mdi:stop
    sequence:
      # - action: media_player.volume_set
      #   data:
      #     entity_id: media_player.nest_mini
      #     volume_level: "0.25"
      # - action: media_player.volume_set
      #   data:
      #     entity_id: media_player.google_home
      #     volume_level: "0.25"
      # - action: media_player.volume_set
      #   data:
      #     entity_id: media_player.soundblaster
      #     volume_level: "0.25"
      # - action: media_player.volume_set
      #   data:
      #     entity_id: media_player.flur
      #     volume_level: "0.25"
      # - action: media_player.volume_set
      #   data:
      #     entity_id: media_player.kristina
      #     volume_level: "0.25"
      - action: media_player.turn_off
        target:
          entity_id: >-
            {% set entities = {
              'Garten':'media_player.googlehome9539',
              'Nest Mini':'media_player.nest_mini',
              'Sound Blaster':'media_player.soundblaster',
              'Home Mini Flur':'media_player.flur',
              'Home Mini Kristina':'media_player.kristina',
              'Überall':'media_player.home_group',
              'Erdgeschoss':'media_player.erdgeschoss',
              }
            %}
            {% set state = states('input_select.radio_player') %}
            {{ iif(state in entities, entities[state], 'media_player.nest_mini') }}

# Customize #########################################################
# homeassistant:
#   customize:
#     # Groups ##########
#     group.radio:
#       friendly_name: Radio
#     # script.radio:
#     #   friendly_name: Play
#     # script.radio_stop:
#     #   friendly_name: Stop
