# Samsung SCX-4726FD

# Recorder ##########################################################
recorder:
  exclude:
    entities:
      - sensor.samsung_scx_472x_series_192_168_2_200
      - ensor.samsung_scx_472x_series_192_168_2_200_tray_1

# Logbook ###########################################################
logbook:
  exclude:
    entities:
      - sensor.samsung_scx_472x_series_192_168_2_200
      - ensor.samsung_scx_472x_series_192_168_2_200_tray_1

# Sensor ############################################################
sensor:
  - platform: template
    sensors:
      samsung_scx_472x_series_192_168_2_200_cnt:
        value_template: "{{ (state_attr('sensor.samsung_scx_472x_series_192_168_2_200_toner_black','cnt') | float) | round(0) }}"
        friendly_name: "Drucker Ausdrucke"
        unit_of_measurement: " "

# Customize #########################################################
homeassistant:
  customize:
    sensor.samsung_scx_472x_series_192_168_2_200:
      friendly_name: "Status Drucker"
      icon: mdi:printer

    sensor.samsung_scx_472x_series_192_168_2_200_toner_black:
      friendly_name: "Toner Verbleibend"
      icon: mdi:ticket-percent

    sensor.samsung_scx_472x_series_192_168_2_200_tray_1:
      friendly_name: "Papiereinzug Status"
      icon: mdi:inbox-arrow-up

    sensor.samsung_scx_472x_series_192_168_2_200_cnt:
      friendly_name: "Ausdrucke Drucker"
      icon: mdi:file-document-box-multiple-outline
      unit_of_measurement: " "

