# Shelly Rollade Terrasse
# https://www.home-assistant.io/integrations/shelly/

# Sensor ############################################################
utility_meter:
  shelly_rollade_4_d:
    unique_id: shelly_rollade_4_d
    source: sensor.shellyswitch25_10d315_energy
    cycle: daily

  shelly_rollade_4_m:
    unique_id: shelly_rollade_4_m
    source: sensor.shellyswitch25_10d315_energy
    cycle: monthly

  shelly_rollade_4_y:
    unique_id: shelly_rollade_4_y
    source: sensor.shellyswitch25_10d315_energy
    cycle: yearly

# Automation ########################################################
automation:
  - id: telegram_rollade_4
    alias: "Telegram - Rollade Terrasse"
    mode: restart
    trigger:
      - platform: event
        event_type: telegram_command
        event_data:
          command: "/rollade_4"

      - platform: event
        event_type: telegram_callback
        event_data:
          command: "/rollade_4"

    action:
      - service: script.cover_one_button
        data:
          entity_id: shellyswitch25_10d315

      - wait_for_trigger:
          - platform: state
            entity_id: cover.shellyswitch25_10d315
        timeout: "00:00:02"
        continue_on_timeout: true

      - service: script.telegram_callback
        data:
          target: "{{ trigger.event.data.chat_id }}"
          message_id: "{{ trigger.event.data.message.message_id if trigger.event.event_type == 'telegram_callback' else 1000 }}"
          message: "🏡 {{ state_attr('cover.shellyswitch25_10d315', 'friendly_name') }} - {{ states('cover.shellyswitch25_10d315') }}"

# Customize #########################################################
homeassistant:
  customize:
    cover.shellyswitch25_10d315:
      friendly_name: Rollade Terrasse
    sensor.shellyswitch25_10d315_power:
      friendly_name: Leistung (Rollade Terrasse)
      icon: mdi:gauge
    sensor.shellyswitch25_10d315_energy:
      friendly_name: Verbrauch (Rollade Terrasse)
    binary_sensor.shellyswitch25_10d315_overheating:
      friendly_name: Überhitzen (Rollade Terrasse)
      icon: mdi:thermometer-alert
