# Shelly Rollade 1
# https://www.home-assistant.io/integrations/shelly/


utility_meter:
  shelly_rollade_1_d:
    source: sensor.shellyswitch25_f37a8c_energy
    cycle: daily

  shelly_rollade_1_m:
    source: sensor.shellyswitch25_f37a8c_energy
    cycle: monthly

  shelly_rollade_1_y:
    source: sensor.shellyswitch25_f37a8c_energy
    cycle: yearly

# Input Text ########################################################
input_text:
  shellyswitch25_f37a8c_last_state:
    initial: opening

# Automation ########################################################
automation:
- id: set_rollade_1_last_state
  alias: Set rollade 1 last state
  mode: single
  trigger:
  - platform: state
    entity_id: cover.shellyswitch25_f37a8c

  action:
  - service: input_text.set_value
    target:
      entity_id: input_text.shellyswitch25_f37a8c_last_state
    data:
      value: "{{ trigger.from_state.state }}"

- id: telegram_rollade_1
  alias: "Telegram Rollade 1"
  mode: parallel
  trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: "/rollade_1"

  - platform: event
    event_type: telegram_callback
    event_data:
      command: "/rollade_1"

  action:
  - service: script.cover_one_button
    data:
      entity: shellyswitch25_f37a8c

  - wait_for_trigger:
    - platform: state
      entity_id: cover.shellyswitch25_f37a8c
    timeout: 5
    continue_on_timeout: true

  - service: telegram_bot.send_message
    data:
      target: "{{ trigger.event.data.user_id }}"
      message: "🏡 {{ state_attr('cover.shellyswitch25_f37a8c', 'friendly_name') }} ist {{ states('cover.shellyswitch25_f37a8c') }}"

# Customize #########################################################
homeassistant:
  customize:
    cover.shellyswitch25_f37a8c:
      friendly_name: Rollade 1
    sensor.shellyswitch25_f37a8c_power:
      friendly_name: Leistung (Rollade 1)
      icon: mdi:gauge
    sensor.shellyswitch25_f37a8c_energy:
      friendly_name: Verbrauch Total (Rollade 1)
    binary_sensor.shellyswitch25_f37a8c_overheating:
      friendly_name: Überhitzen (Rollade 1)
      icon: mdi:thermometer-alert
