# Shelly integration
# https://www.home-assistant.io/integrations/shelly/

cover:
  - platform: group
    name: rolladen
    entities:
      - cover.shellyswitch25_f37a8c
      - cover.shellyswitch25_f37b28
      - cover.shellyswitch25_10eaa4
      - cover.shellyswitch25_10d315

# Customize #########################################################
homeassistant:
  customize:
    cover.rolladen:
      friendly_name: Rolladen
