# Shelly Kueche
# https://www.home-assistant.io/integrations/shelly/

# Sensor ############################################################
utility_meter:
  shelly_kueche_d:
    source: sensor.shellyswitch25_10a36d_channel_1_energy
    cycle: daily

  shelly_kueche_m:
    source: sensor.shellyswitch25_10a36d_channel_1_energy
    cycle: monthly

  shelly_kueche_y:
    source: sensor.shellyswitch25_10a36d_channel_1_energy
    cycle: yearly

  shelly_essecke_d:
    source: sensor.shellyswitch25_10a36d_channel_2_energy
    cycle: daily

  shelly_essecke_m:
    source: sensor.shellyswitch25_10a36d_channel_2_energy
    cycle: monthly

  shelly_essecke_y:
    source: sensor.shellyswitch25_10a36d_channel_2_energy
    cycle: yearly

# Automation ########################################################
automation:
  - id: telegram_kueche
    alias: "Telegram - Kueche"
    mode: parallel
    trigger:
      - platform: event
        event_type: telegram_command
        event_data:
          command: "/kuechenlicht"
      - platform: event
        event_type: telegram_callback
        event_data:
          command: "/kuechenlicht"

      - platform: event
        event_type: telegram_command
        event_data:
          command: "/essecke"
      - platform: event
        event_type: telegram_callback
        event_data:
          command: "/essecke"

    action:
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ trigger.event.data.command == '/kuechenlicht' }}"
            sequence:
              - service: light.toggle
                data:
                  entity_id: light.shellyswitch25_10a36d_channel_1

              - wait_for_trigger:
                  - platform: state
                    entity_id: light.shellyswitch25_10a36d_channel_1
                continue_on_timeout: true
                timeout: "00:00:01"

              - service: script.telegram_callback
                data:
                  target: "{{ trigger.event.data.chat_id }}"
                  message_id: "{{ trigger.event.data.message.message_id if trigger.event.event_type == 'telegram_callback' else 1000 }}"
                  message: "💡 {{ state_attr('light.shellyswitch25_10a36d_channel_1', 'friendly_name') }} - {{ states('light.shellyswitch25_10a36d_channel_1') }}"

          - conditions:
              - condition: template
                value_template: "{{ trigger.event.data.command == '/essecke' }}"
            sequence:
              - service: light.toggle
                data:
                  entity_id: light.shellyswitch25_10a36d_channel_2

              - wait_for_trigger:
                  - platform: state
                    entity_id: light.shellyswitch25_10a36d_channel_2
                continue_on_timeout: true
                timeout: "00:00:01"

              - service: script.telegram_callback
                data:
                  target: "{{ trigger.event.data.chat_id }}"
                  message_id: "{{ trigger.event.data.message.message_id if trigger.event.event_type == 'telegram_callback' else 1000 }}"
                  message: "💡 {{ state_attr('light.shellyswitch25_10a36d_channel_2', 'friendly_name') }} - {{ states('light.shellyswitch25_10a36d_channel_2') }}"

# Customize #########################################################
homeassistant:
  customize:
    light.shellyswitch25_10a36d_channel_1:
      friendly_name: Küche
      icon: mdi:dome-light

    light.shellyswitch25_10a36d_channel_2:
      friendly_name: Essecke
      icon: mdi:string-lights

    sensor.shellyswitch25_10a36d_channel_1_energy_spent:
      friendly_name: Verbrauch (Küche), kWh

    sensor.shellyswitch25_10a36d_channel_1_power:
      friendly_name: Leistung (Küche)
      icon: mdi:gauge
    sensor.shellyswitch25_10a36d_channel_1_energy:
      friendly_name: Verbrauch Total (Küche)
    sensor.shelly_kueche_d:
      friendly_name: Verbrauch Heute (Küche)
      icon: mdi:lightning-bolt
    sensor.shelly_kueche_m:
      friendly_name: Verbrauch im Monat (Küche)
      icon: mdi:lightning-bolt
    sensor.shelly_kueche_y:
      friendly_name: Verbrauch im Jahr (Küche)
      icon: mdi:lightning-bolt

    binary_sensor.shellyswitch25_10a36d_channel_1_overpowering:
      friendly_name: Überspannung (Küche)
      icon: mdi:flash-alert

    sensor.shellyswitch25_10a36d_channel_2_power:
      friendly_name: Leistung (Essecke)
      icon: mdi:gauge
    sensor.shellyswitch25_10a36d_channel_2_energy:
      friendly_name: Verbrauch Total (Essecke)
    sensor.shelly_essecke_d:
      friendly_name: Verbrauch Heute (Essecke)
      icon: mdi:lightning-bolt
    sensor.shelly_essecke_m:
      friendly_name: Verbrauch im Monat (Essecke)
      icon: mdi:lightning-bolt
    sensor.shelly_essecke_y:
      friendly_name: Verbrauch im Jahr (Essecke)
      icon: mdi:lightning-bolt

    binary_sensor.shellyswitch25_10a36d_channel_2_overpowering:
      friendly_name: Überspannung (Essecke)
      icon: mdi:flash-alert

    binary_sensor.shellyswitch25_10a36d_overheating:
      friendly_name: Überhitzen (Küche)
      icon: mdi:thermometer-alert
