# Shelly Rollade Terrasse
# https://www.home-assistant.io/integrations/shelly/

# Sensor ############################################################
utility_meter:
  shelly_rollade_4_d:
    unique_id: shelly_rollade_4_d
    source: sensor.rollade_4_energy
    cycle: daily

  shelly_rollade_4_m:
    unique_id: shelly_rollade_4_m
    source: sensor.rollade_4_energy
    cycle: monthly

  shelly_rollade_4_y:
    unique_id: shelly_rollade_4_y
    source: sensor.rollade_4_energy
    cycle: yearly

# Automation ########################################################
automation:
  - id: telegram_rollade_4
    alias: "Telegram - Rollade Terrasse"
    mode: restart
    triggers:
      - trigger: event
        event_type: telegram_command
        event_data:
          command: "/rollade_4"

      - trigger: event
        event_type: telegram_callback
        event_data:
          command: "/rollade_4"

    actions:
      - action: script.cover_one_button
        data:
          entity_id: rollade_4

      - wait_for_trigger:
          - trigger: state
            entity_id: cover.rollade_4
        timeout: "00:00:02"
        continue_on_timeout: true

      - action: script.telegram_callback
        data:
          target: "{{ trigger.event.data.chat_id }}"
          message_id: "{{ trigger.event.data.message.message_id if trigger.event.event_type == 'telegram_callback' else 1000 }}"
          message: "🏡 {{ state_attr('cover.rollade_4', 'friendly_name') }} - {{ states('cover.rollade_4') }}"

# Customize #########################################################
homeassistant:
  customize:
    cover.rollade_4:
      friendly_name: Rollade Terrasse
    sensor.rollade_4_power:
      friendly_name: Leistung (Rollade Terrasse)
      icon: mdi:gauge
    sensor.rollade_4_energy:
      friendly_name: Verbrauch (Rollade Terrasse)
    binary_sensor.rollade_4_overheating:
      friendly_name: Überhitzen (Rollade Terrasse)
      icon: mdi:thermometer-alert
