# Shelly integration
# https://www.home-assistant.io/integrations/shelly/

cover:
  - platform: group
    name: rolladen
    entities:
      - cover.shellyswitch25_f37a8c
      - cover.shellyswitch25_f37b28
      - cover.shellyswitch25_10eaa4
      - cover.shellyswitch25_10d315

light:
  - platform: switch
    name: shellyswitch25_10c7c3_channel_1
    entity_id: switch.shellyswitch25_10c7c3_channel_1

utility_meter:
#######################################
#  shelly_kuchenlicht_d:
#    source: sensor.shellyswitch25_10a36d_channel_1_energy
#    cycle: daily
#
#  shelly_kuchenlicht_m:
#    source: sensor.shellyswitch25_10a36d_channel_1_energy
#    cycle: monthly
#
#  shelly_kuchenlicht_y:
#    source: sensor.shellyswitch25_10a36d_channel_1_energy
#    cycle: yearly
########################################
#  shelly_essecke_d:
#    source: sensor.shellyswitch25_10a36d_channel_2_energy
#    cycle: daily
#
#  shelly_essecke_m:
#    source: sensor.shellyswitch25_10a36d_channel_2_energy
#    cycle: monthly
#
#  shelly_essecke_y:
#    source: sensor.shellyswitch25_10a36d_channel_2_energy
#    cycle: yearly
########################################
  shelly_wohnlicht_d:
    source: sensor.shellyswitch25_10c7c3_channel_1_energy
    cycle: daily

  shelly_wohnlicht_m:
    source: sensor.shellyswitch25_10c7c3_channel_1_energy
    cycle: monthly

  shelly_wohnlicht_y:
    source: sensor.shellyswitch25_10c7c3_channel_1_energy
    cycle: yearly

homeassistant:
  customize:
    cover.shellyswitch25_f37a8c:
      friendly_name: Rollade 1
    sensor.shellyswitch25_f37a8c_power:
      friendly_name: Leistung (Rollade 1)
      icon: mdi:gauge
    sensor.shellyswitch25_f37a8c_energy:
      friendly_name: Verbrauch Total (Rollade 1)
    binary_sensor.shellyswitch25_f37a8c_overheating:
      friendly_name: Überhitzen (Rollade 1)
      icon: mdi:thermometer-alert

    cover.shellyswitch25_f37b28:
      friendly_name: Rollade 2
    sensor.shellyswitch25_f37b28_power:
      friendly_name: Leistung (Rollade 2)
      icon: mdi:gauge
    sensor.shellyswitch25_f37b28_energy:
      friendly_name: Verbrauch Total (Rollade 2)
    binary_sensor.shellyswitch25_f37b28_overheating:
      friendly_name: Überhitzen (Rollade 2)
      icon: mdi:thermometer-alert

    cover.shellyswitch25_10eaa4:
      friendly_name: Rollade 3
    sensor.shellyswitch25_10eaa4_power:
      friendly_name: Leistung (Rollade 3)
      icon: mdi:gauge
    sensor.shellyswitch25_10eaa4_energy:
      friendly_name: Verbrauch Total (Rollade 3)
    binary_sensor.shellyswitch25_10eaa4_overheating:
      friendly_name: Überhitzen (Rollade 3)
      icon: mdi:thermometer-alert

    cover.shellyswitch25_10d315:
      friendly_name: Rollade hinten
    sensor.shellyswitch25_10d315_power:
      friendly_name: Leistung (Rollade Hinten)
      icon: mdi:gauge
    sensor.shellyswitch25_10d315_energy:
      friendly_name: Verbrauch Total (Rollade Hinten)
    binary_sensor.shellyswitch25_10d315_overheating:
      friendly_name: Überhitzen (Rollade Hinten)
      icon: mdi:thermometer-alert

#    switch.shellyswitch25_10a36d_1:
#      friendly_name: Küchenlicht
#    sensor.shellyswitch25_10a36d_channel_1_power:
#      friendly_name: Leistung (Küchenlicht)
#      icon: mdi:gauge
#    sensor.shellyswitch25_10a36d_channel_1_energy:
#      friendly_name: Verbrauch Total (Küchenlicht)
#    sensor.shelly_kuchenlicht_d:
#      friendly_name: Verbrauch pro Tag (Küchenlicht)
#    sensor.shelly_kuchenlicht_m:
#      friendly_name: Verbrauch pro Monat (Küchenlicht)
#    sensor.shelly_kuchenlicht_y:
#      friendly_name: Verbrauch pro Jahr (Küchenlicht)
#    binary_sensor.shellyswitch25_10a36d_channel_1_overpowering:
#      friendly_name: Überspannung (Wohnlicht)
#      icon: mdi:flash-alert
#
#    switch.shellyswitch25_10a36d_2:
#      friendly_name: Essecke Licht
#    sensor.shellyswitch25_10a36d_channel_2_power:
#      friendly_name: Leistung (Essecke)
#      icon: mdi:gauge
#    sensor.shellyswitch25_10a36d_2_channel_1_energy:
#      friendly_name: Verbrauch Total (Essecke)
#    sensor.shelly_essecke_d:
#      friendly_name: Verbrauch pro Tag (Essecke)
#    sensor.shelly_essecke_m:
#      friendly_name: Verbrauch pro Monat (Essecke)
#    sensor.shelly_essecke_y:
#      friendly_name: Verbrauch pro Jahr (Essecke)
#    binary_sensor.shellyswitch25_10a36d_channel_1_overpowering:
#      friendly_name: Überspannung (Wohnlicht)
#      icon: mdi:flash-alert
#    binary_sensor.shellyswitch25_10a36d_overheating:
#      friendly_name: Überhitzen (Wohnlicht)
#      icon: mdi:thermometer-alert

    light.shellyswitch25_10c7c3_channel_1:
      friendly_name: Wohnlicht
      icon: mdi:vanity-light
    sensor.shellyswitch25_10c7c3_channel_1_power:
      friendly_name: Leistung (Wohnlicht)
      icon: mdi:gauge
    sensor.shellyswitch25_10c7c3_channel_1_energy:
      friendly_name: Verbrauch Total (Wohnlicht)
    sensor.shelly_wohnlicht_d:
      friendly_name: Verbrauch pro Tag (Wohnlicht)
    sensor.shelly_wohnlicht_m:
      friendly_name: Verbrauch pro Monat (Wohnlicht)
    sensor.shelly_wohnlicht_y:
      friendly_name: Verbrauch pro Jahr (Wohnlicht)
    binary_sensor.shellyswitch25_10c7c3_channel_1_overpowering:
      friendly_name: Überspannung (Wohnlicht)
      icon: mdi:flash-alert
    binary_sensor.shellyswitch25_10c7c3_overheating:
      friendly_name: Überhitzen (Wohnlicht)
      icon: mdi:thermometer-alert

#    switch.shellyswitch25_10c7c3_2:
#      friendly_name: Flur Licht
#    sensor.shellyswitch25_10c7c3_channel_2_power:
#      friendly_name: Flur Energie
#    sensor.shellyswitch25_10c7c3_channel_2_energy:
#      friendly_name: Verbrauch Total (Flur)
    binary_sensor.shellyswitch25_10c7c3_channel_2_overpowering:
      friendly_name: Überspannung (Wohnlicht 2)
      icon: mdi:flash-alert

    cover.rolladen:
      friendly_name: Rolladen
