# Shelly Rollade 3
# https://www.home-assistant.io/integrations/shelly/

# Sensor ############################################################
utility_meter:
  shelly_rollade_3_d:
    unique_id: shelly_rollade_3_d
    source: sensor.shellyswitch25_10eaa4_energy
    cycle: daily

  shelly_rollade_3_m:
    unique_id: shelly_rollade_3_m
    source: sensor.shellyswitch25_10eaa4_energy
    cycle: monthly

  shelly_rollade_3_y:
    unique_id: shelly_rollade_3_y
    source: sensor.shellyswitch25_10eaa4_energy
    cycle: yearly

# Automation ########################################################
automation:
  - id: telegram_rollade_3
    alias: "Telegram - Rollade 3"
    mode: restart
    trigger:
      - platform: event
        event_type: telegram_command
        event_data:
          command: "/rollade_3"

      - platform: event
        event_type: telegram_callback
        event_data:
          command: "/rollade_3"

    action:
      - service: script.cover_one_button
        data:
          entity_id: shellyswitch25_10eaa4

      - wait_for_trigger:
          - platform: state
            entity_id: cover.shellyswitch25_10eaa4
        timeout: "00:00:02"
        continue_on_timeout: true

      - service: script.telegram_callback
        data:
          target: "{{ trigger.event.data.chat_id }}"
          message_id: "{{ trigger.event.data.message.message_id if trigger.event.event_type == 'telegram_callback' else 1000 }}"
          message: "🏡 {{ state_attr('cover.shellyswitch25_10eaa4', 'friendly_name') }} - {{ states('cover.shellyswitch25_10eaa4') }}"

# Customize #########################################################
homeassistant:
  customize:
    cover.shellyswitch25_10eaa4:
      friendly_name: Rollade 3
    sensor.shellyswitch25_10eaa4_power:
      friendly_name: Leistung (Rollade 3)
      icon: mdi:gauge
    sensor.shellyswitch25_10eaa4_energy:
      friendly_name: Verbrauch (Rollade 3)
    binary_sensor.shellyswitch25_10eaa4_overheating:
      friendly_name: Überhitzen (Rollade 3)
      icon: mdi:thermometer-alert
