# Shelly Rollade 2
# https://www.home-assistant.io/integrations/shelly/


utility_meter:
  shelly_rollade_2_d:
    source: sensor.shellyswitch25_f37b28_energy
    cycle: daily

  shelly_rollade_2_m:
    source: sensor.shellyswitch25_f37b28_energy
    cycle: monthly

  shelly_rollade_2_y:
    source: sensor.shellyswitch25_f37b28_energy
    cycle: yearly

# Automation ########################################################
automation:
- id: telegram_rollade_2
  alias: "Telegram Rollade 2"
  mode: parallel
  trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: "/rollade_2"

  - platform: event
    event_type: telegram_callback
    event_data:
      command: "/rollade_2"

  action:
  - service: script.cover_one_button
    data:
      entity: shellyswitch25_f37b28

  - wait_for_trigger:
    - platform: state
      entity_id: cover.shellyswitch25_f37b28
    timeout: 5
    continue_on_timeout: true

  - service: telegram_bot.send_message
    data:
      target: "{{ trigger.event.data.user_id }}"
      message: "🏡 {{ state_attr('cover.shellyswitch25_f37b28', 'friendly_name') }} ist {{ states('cover.shellyswitch25_f37b28') }}"

# Customize #########################################################
homeassistant:
  customize:
    cover.shellyswitch25_f37b28:
      friendly_name: Rollade 2
    sensor.shellyswitch25_f37b28_power:
      friendly_name: Leistung (Rollade 2)
      icon: mdi:gauge
    sensor.shellyswitch25_f37b28_energy:
      friendly_name: Verbrauch Total (Rollade 2)
    binary_sensor.shellyswitch25_f37b28_overheating:
      friendly_name: Überhitzen (Rollade 2)
      icon: mdi:thermometer-alert
