# Shelly Rollade hinten
# https://www.home-assistant.io/integrations/shelly/

# Sensor ############################################################
utility_meter:
  shelly_rollade_hinten_d:
    source: sensor.shellyswitch25_10d315_energy
    cycle: daily

  shelly_rollade_hinten_m:
    source: sensor.shellyswitch25_10d315_energy
    cycle: monthly

  shelly_rollade_hinten_y:
    source: sensor.shellyswitch25_10d315_energy
    cycle: yearly

# Automation ########################################################
automation:
  - id: telegram_rollade_hinten
    alias: "Telegram - Rollade hinten"
    mode: parallel
    trigger:
      - platform: event
        event_type: telegram_command
        event_data:
          command: "/rollade_hinten"

      - platform: event
        event_type: telegram_callback
        event_data:
          command: "/rollade_hinten"

    action:
      - service: script.cover_one_button
        data:
          entity_id: shellyswitch25_10d315

      - wait_for_trigger:
          - platform: state
            entity_id: cover.shellyswitch25_10d315
        timeout: 5
        continue_on_timeout: true

      - service: telegram_bot.send_message
        data:
          target: "{{ trigger.event.data.user_id }}"
          message: "🏡 {{ state_attr('cover.shellyswitch25_10d315', 'friendly_name') }} ist {{ states('cover.shellyswitch25_10d315') }}"

# Customize #########################################################
homeassistant:
  customize:
    cover.shellyswitch25_10d315:
      friendly_name: Rollade hinten
    sensor.shellyswitch25_10d315_power:
      friendly_name: Leistung (Rollade Hinten)
      icon: mdi:gauge
    sensor.shellyswitch25_10d315_energy:
      friendly_name: Verbrauch Total (Rollade Hinten)
    binary_sensor.shellyswitch25_10d315_overheating:
      friendly_name: Überhitzen (Rollade Hinten)
      icon: mdi:thermometer-alert
