# Sonoff POW R2
# Sonoff-Tasmota 6.6.0

# Switch ############################################################
switch:
  - platform: mqtt
    name: "SonoffPow 01"
    state_topic: "sonoffpow-01/stat/RESULT"
    value_template: "{{ value_json.POWER }}"
    command_topic: "sonoffpow-01/cmnd/POWER"
    availability_topic: "sonoffpow-01/tele/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false

# Light #############################################################
light:
  - platform: switch
    name: "SonoffPow 01"
    entity_id: switch.sonoffpow_01

# Sensor ############################################################
sensor:
  - platform: mqtt
    name: "SonoffPow 01 Energy TotalStartTime"
    state_topic: "sonoffpow-01/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["TotalStartTime"] }}'
  - platform: mqtt
    name: "SonoffPow 01 Energy Total"
    state_topic: "sonoffpow-01/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Total"] }}'
#  - platform: mqtt
#    name: "SonoffPow 01 Energy Yesterday"
#    state_topic: "sonoffpow-01/tele/SENSOR"
#    value_template: '{{ value_json["ENERGY"]["Yesterday"] }}'
  - platform: mqtt
    name: "SonoffPow 01 Energy Today"
    state_topic: "sonoffpow-01/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Today"] }}'
#  - platform: mqtt
#    name: "SonoffPow 01 Energy Period"
#    state_topic: "sonoffpow-01/tele/SENSOR"
#    value_template: '{{ value_json["ENERGY"]["Period"] }}'
  - platform: mqtt
    name: "SonoffPow 01 Energy Power"
    state_topic: "sonoffpow-01/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Power"] }}'
#  - platform: mqtt
#    name: "SonoffPow 01 Energy ApparentPower"
#    state_topic: "sonoffpow-01/tele/SENSOR"
#    value_template: '{{ value_json["ENERGY"]["ApparentPower"] }}'
#  - platform: mqtt
#    name: "SonoffPow 01 Energy ReactivePower"
#    state_topic: "sonoffpow-01/tele/SENSOR"
#    value_template: '{{ value_json["ENERGY"]["ReactivePower"] }}'
#  - platform: mqtt
#    name: "SonoffPow 01 Energy Factor"
#    state_topic: "sonoffpow-01/tele/SENSOR"
#    value_template: '{{ value_json["ENERGY"]["Factor"] }}'
#  - platform: mqtt
#    name: "SonoffPow 01 Energy Voltage"
#    state_topic: "sonoffpow-01/tele/SENSOR"
#    value_template: '{{ value_json["ENERGY"]["Voltage"] }}'
#  - platform: mqtt
#    name: "SonoffPow 01 Energy Current"
#    state_topic: "sonoffpow-01/tele/SENSOR"
#    value_template: '{{ value_json["ENERGY"]["Current"] }}'

  - platform: mqtt
    name: "SonoffPow 01 Status"
    state_topic: "sonoffpow-01/tele/STATE"
    value_template: '{{ value_json["Wifi"]["RSSI"] }}'
    unit_of_measurement: "%"
    json_attributes_topic: "sonoffpow-01/tele/STATE"

utility_meter:
  sonoffpow_01_energy_d:
    source: sensor.sonoffpow_01_energy_total
    cycle: daily

  sonoffpow_01_energy_m:
    source: sensor.sonoffpow_01_energy_total
    cycle: monthly

  sonoffpow_01_energy_y:
    source: sensor.sonoffpow_01_energy_total
    cycle: yearly

# Group #############################################################
#group:
#  sonoffpow_01:
#    name: "Wandlicht"
#    entities:
#      - switch.sonoffpow_01
#      - light.sonoffpow_01
#      - sensor.sonoffpow_01_status
#      - sensor.sonoffpow_01_energy_voltage
#      - sensor.sonoffpow_01_energy_current
#      - sensor.sonoffpow_01_energy_power
#      - sensor.sonoffpow_01_energy_apparentpower
#      - sensor.sonoffpow_01_energy_reactivepower
#      - sensor.sonoffpow_01_energy_factor
#      - sensor.sonoffpow_01_energy_totalstarttime
#      - sensor.sonoffpow_01_energy_total
#      - sensor.sonoffpow_01_energy_today
#      - sensor.sonoffpow_01_energy_yesterday

automation:
- id: telegram_sonoffpow_01
  alias: "Telegram sonoffpow_01"
  mode: parallel
  trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: "/wandlicht"

  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/wandlicht'

  action:
    - service: light.toggle
      data:
        entity_id: light.sonoffpow_01

    - wait_for_trigger:
      - platform: state
        entity_id: light.sonoffpow_01
      timeout: 5
      continue_on_timeout: true

    - service: telegram_bot.send_message
      data:
        target: "{{ trigger.event.data.user_id }}"
        message: "💡 {{ state_attr('light.sonoffpow_01', 'friendly_name') }} ist {{ states('light.sonoffpow_01') }}"

#  Service ist {{ trigger.event }}"

# Customize #########################################################
homeassistant:
  customize:
# Switch ##########
    switch.sonoffpow_01:
      friendly_name: Wandlicht
      icon: mdi:wall-sconce-flat
#      icon: mdi:track-light
# Light ###########
    light.sonoffpow_01:
      friendly_name: Wandlicht
      icon: mdi:wall-sconce-flat
#      icon: mdi:track-light
# Sensor ##########
#    sensor.sonoffpow_01_energy_voltage:
#      friendly_name: Spannung (Wandlicht)
#      icon: mdi:power-plug
#      unit_of_measurement: "V"
#    sensor.sonoffpow_01_energy_current:
#      friendly_name: Stromstärke (Wandlicht)
#      icon: mdi:current-ac
#      unit_of_measurement: "A"
#    sensor.sonoffpow_01_energy_factor:
#      friendly_name: Leistungsfaktor (Wandlicht)
#      icon: mdi:margin
#      unit_of_measurement: "%"
    sensor.sonoffpow_01_energy_power:
      friendly_name: Leistung (Wandlicht)
      icon: mdi:gauge
      unit_of_measurement: "W"
#    sensor.sonoffpow_01_energy_apparentpower:
#      friendly_name: Scheinleistung (Wandlicht)
#      icon: mdi:resistor
#      unit_of_measurement: "VA"
#    sensor.sonoffpow_01_energy_reactivepower:
#      friendly_name: Blindleistung (Wandlicht)
#      icon: mdi:chart-bell-curve
#      unit_of_measurement: "VAr"

    sensor.sonoffpow_01_energy_today:
      friendly_name: Verbrauch Heute (Wandlicht)
      icon: mdi:chart-areaspline
      unit_of_measurement: "kWh"
    sensor.sonoffpow_01_energy_total:
      friendly_name: Verbrauch Total (Wandlicht)
      icon: mdi:chart-areaspline
      unit_of_measurement: "kWh"
#    sensor.sonoffpow_01_energy_yesterday:
#      friendly_name: Verbrauch Gestern (Wandlicht)
#      icon: mdi:chart-areaspline
#      unit_of_measurement: "kWh"
    sensor.sonoffpow_01_energy_totalstarttime:
      friendly_name: "Seit"
      icon: mdi:calendar-clock
      device_class: "timestamp"

    sensor.sonoffpow_01_status:
      friendly_name: Status (Wandlicht)
      icon: mdi:information
      unit_of_measurement: "%"

    sensor.sonoffpow_01_energy_d:
      friendly_name: Verbrauch pro Tag (Wandlicht)

    sensor.sonoffpow_01_energy_m:
      friendly_name: Verbrauch pro Monat (Wandlicht)

    sensor.sonoffpow_01_energy_y:
      friendly_name: Verbrauch pro Jahr (Wandlicht)

#history_graph:
#  sonoffpow_01_graph_d:
#    entities:
#      - sensor.sonoffpow_01_energy_d
#      - sensor.sonoffpow_01_energy_daily
#    hours_to_show: 240
#
#  sonoffpow_01_graph_m:
#    entities:
#      - sensor.sonoffpow_01_energy_m
#      - sensor.sonoffpow_01_energy_monthly
#    hours_to_show: 8760
#
#  sonoffpow_01_graph_y:
#    entities:
#      - sensor.sonoffpow_01_energy_y
#      - sensor.sonoffpow_01_energy_yearly
#    hours_to_show: 8760

#  - platform: sql
#    queries:
#    - name: SonoffPOW 01 Durchschnitt Energie in der letzte Monat
#      query: >
#        SELECT ROUND(AVG(avg_per_day),2) 'value'
#          FROM (
#          SELECT AVG(state) AS avg_per_day
#          FROM states
#          WHERE entity_id = 'sensor.sonoffpow_01_energy_yesterday'
#          AND state != 'unknown'
#          AND state != ''
#          AND created > datetime('now', '-1 month')
#          GROUP BY DATE(created)
#        ) avgs;
#      column: 'value'
#      unit_of_measurement: kWh
#
#  - platform: sql
#    queries:
#    - name: SonoffPOW 01 Gesamt Energie in der letzte Monat
#      query: >
#        SELECT ROUND(SUM(max_per_day),2) 'value'
#        FROM (
#          SELECT MAX(state) AS max_per_day
#          FROM states
#          WHERE entity_id = 'sensor.sonoffpow_01_energy_yesterday'
#          AND state != 'unknown'
#          AND state != ''
#          AND created > datetime('now', '-1 month')
#          GROUP BY DATE(created)
#        ) sums;
#      column: 'value'
#      unit_of_measurement: kWh

#  - platform: integration
#    source: sensor.sonoffpow_01_energy_power
#    name: SonoffPOW 01 Power In
##    unit_prefix: k
##    round: 2
#
#  - platform: integration
#    source: sensor.sonoffpow_01_energy_power
#    name: SonoffPOW 01 Energy K
#    unit_prefix: k
##    round: 2

#utility_meter:
#  sonoffpow_01_power_daily:
#    source: sensor.sonoffpow_01_power_in
#    cycle: daily
#
#  sonoffpow_01_power_monthly:
#    source: sensor.sonoffpow_01_power_in
#    cycle: monthly
#
#  sonoffpow_01_power_yearly:
#    source: sensor.sonoffpow_01_power_in
#    cycle: yearly
#
#  sonoffpow_01_energy_d:
#    source: sensor.sonoffpow_01_energy_k
#    cycle: daily
#
#  sonoffpow_01_energy_m:
#    source: sensor.sonoffpow_01_energy_k
#    cycle: monthly
#
#  sonoffpow_01_energy_y:
#    source: sensor.sonoffpow_01_energy_k
#    cycle: yearly

#  sonoffpow_01_energy_daily:
#    source: sensor.sonoffpow_01_energy_power
#    cycle: daily
#  sonoffpow_01_energy_monthly:
#    source: sensor.sonoffpow_01_energy_power
#    cycle: monthly
#
#  sonoffpow_01_energy_yearly:
#    source: yearly.sonoffpow_01_energy_power
#    cycle: monthly
#
