# Sonoff POW R2
# Sonoff-Tasmota 6.6.0

# Switch ############################################################
switch:
  - platform: mqtt
    name: "SonoffPow 03"
    state_topic: "sonoffpow-03/stat/RESULT"
    value_template: "{{ value_json.POWER }}"
    command_topic: "sonoffpow-03/cmnd/POWER"
    availability_topic: "sonoffpow-03/tele/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false

# Light #############################################################
light:
  - platform: switch
    name: "SonoffPow 03"
    entity_id: switch.sonoffpow_03

# Sensor ############################################################
sensor:
  - platform: mqtt
    name: "SonoffPow 03 Energy TotalStartTime"
    state_topic: "sonoffpow-03/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["TotalStartTime"] }}'
  - platform: mqtt
    name: "SonoffPow 03 Energy Total"
    state_topic: "sonoffpow-03/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Total"] }}'
#  - platform: mqtt
#    name: "SonoffPow 03 Energy Yesterday"
#    state_topic: "sonoffpow-03/tele/SENSOR"
#    value_template: '{{ value_json["ENERGY"]["Yesterday"] }}'
  - platform: mqtt
    name: "SonoffPow 03 Energy Today"
    state_topic: "sonoffpow-03/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Today"] }}'
#  - platform: mqtt
#    name: "SonoffPow 03 Energy Period"
#    state_topic: "sonoffpow-03/tele/SENSOR"
#    value_template: '{{ value_json["ENERGY"]["Period"] }}'
  - platform: mqtt
    name: "SonoffPow 03 Energy Power"
    state_topic: "sonoffpow-03/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Power"] }}'
#  - platform: mqtt
#    name: "SonoffPow 03 Energy ApparentPower"
#    state_topic: "sonoffpow-03/tele/SENSOR"
#    value_template: '{{ value_json["ENERGY"]["ApparentPower"] }}'
#  - platform: mqtt
#    name: "SonoffPow 03 Energy ReactivePower"
#    state_topic: "sonoffpow-03/tele/SENSOR"
#    value_template: '{{ value_json["ENERGY"]["ReactivePower"] }}'
#  - platform: mqtt
#    name: "SonoffPow 03 Energy Factor"
#    state_topic: "sonoffpow-03/tele/SENSOR"
#    value_template: '{{ value_json["ENERGY"]["Factor"] }}'
#  - platform: mqtt
#    name: "SonoffPow 03 Energy Voltage"
#    state_topic: "sonoffpow-03/tele/SENSOR"
#    value_template: '{{ value_json["ENERGY"]["Voltage"] }}'
#  - platform: mqtt
#    name: "SonoffPow 03 Energy Current"
#    state_topic: "sonoffpow-03/tele/SENSOR"
#    value_template: '{{ value_json["ENERGY"]["Current"] }}'

  - platform: mqtt
    name: "SonoffPow 03 Status"
    state_topic: "sonoffpow-03/tele/STATE"
    value_template: '{{ value_json["Wifi"]["RSSI"] }}'
    unit_of_measurement: "%"
    json_attributes_topic: "sonoffpow-03/tele/STATE"

utility_meter:
  sonoffpow_03_energy_d:
    source: sensor.sonoffpow_03_energy_total
    cycle: daily

  sonoffpow_03_energy_m:
    source: sensor.sonoffpow_03_energy_total
    cycle: monthly

  sonoffpow_03_energy_y:
    source: sensor.sonoffpow_03_energy_total
    cycle: yearly

# Group #############################################################
#group:
#  sonoffpow_03:
#    name: "Küchenlicht"
#    entities:
#      - switch.sonoffpow_03
##      - light.sonoffpow_03
#      - sensor.sonoffpow_03_status
#      - sensor.sonoffpow_03_energy_voltage
#      - sensor.sonoffpow_03_energy_current
#      - sensor.sonoffpow_03_energy_power
#      - sensor.sonoffpow_03_energy_apparentpower
#      - sensor.sonoffpow_03_energy_reactivepower
#      - sensor.sonoffpow_03_energy_factor
#      - sensor.sonoffpow_03_energy_totalstarttime
#      - sensor.sonoffpow_03_energy_total
#      - sensor.sonoffpow_03_energy_today
#      - sensor.sonoffpow_03_energy_yesterday

automation:
- id: telegram_sonoffpow_03
  alias: "Telegram sonoffpow_03"
  mode: parallel
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: "/kuechenlicht"

  action:
    - service: light.toggle
      data:
        entity_id: light.sonoffpow_03

    - wait_for_trigger:
      - platform: state
        entity_id: light.sonoffpow_03
      timeout: 5
      continue_on_timeout: true

    - service: telegram_bot.send_message
      data:
        target: "{{ trigger.event.data.user_id }}"
        message: "{{ state_attr('light.sonoffpow_03', 'friendly_name') }} ist {{ states('light.sonoffpow_03') }}"

# Customize #########################################################
homeassistant:
  customize:
# Switch ##########
    switch.sonoffpow_03:
      friendly_name: Küchenlicht
      icon: mdi:dome-light
# Light ###########
    light.sonoffpow_03:
      friendly_name: Küchenlicht
      icon: mdi:dome-light
# Sensor ##########
#    sensor.sonoffpow_03_energy_voltage:
#      friendly_name: Spannung (Küchenlicht)
#      icon: mdi:power-plug
#      unit_of_measurement: "V"
#    sensor.sonoffpow_03_energy_current:
#      friendly_name: Stromstärke (Küchenlicht)
#      icon: mdi:current-ac
#      unit_of_measurement: "A"
#    sensor.sonoffpow_03_energy_factor:
#      friendly_name: Leistungsfaktor (Küchenlicht)
#      icon: mdi:margin
#      unit_of_measurement: "%"
    sensor.sonoffpow_03_energy_power:
      friendly_name: Leistung (Küchenlicht)
      icon: mdi:gauge
      unit_of_measurement: "W"
#    sensor.sonoffpow_03_energy_apparentpower:
#      friendly_name: Scheinleistung (Küchenlicht)
#      icon: mdi:resistor
#      unit_of_measurement: "VA"
#    sensor.sonoffpow_03_energy_reactivepower:
#      friendly_name: Blindleistung (Küchenlicht)
#      icon: mdi:chart-bell-curve
#      unit_of_measurement: "VAr"

    sensor.sonoffpow_03_energy_today:
      friendly_name: Verbrauch Heute (Küchenlicht)
      icon: mdi:chart-areaspline
      unit_of_measurement: "kWh"
    sensor.sonoffpow_03_energy_total:
      friendly_name: Verbrauch Total (Küchenlicht)
      icon: mdi:chart-areaspline
      unit_of_measurement: "kWh"
#    sensor.sonoffpow_03_energy_yesterday:
#      friendly_name: Verbrauch Gestern (Küchenlicht)
#      icon: mdi:chart-areaspline
#      unit_of_measurement: "kWh"
    sensor.sonoffpow_03_energy_totalstarttime:
      friendly_name: "Seit"
      icon: mdi:calendar-clock
      device_class: "timestamp"

    sensor.sonoffpow_03_status:
      friendly_name: Status (Küchenlicht)
      icon: mdi:information
      unit_of_measurement: "%"

    sensor.sonoffpow_03_energy_d:
      friendly_name: Verbrauch pro Tag (Küchenlicht)

    sensor.sonoffpow_03_energy_m:
      friendly_name: Verbrauch pro Monat (Küchenlicht)

    sensor.sonoffpow_03_energy_y:
      friendly_name: Verbrauch pro Jahr (Küchenlicht)

#  - platform: sql
#    queries:
#    - name: SonoffPOW 03 Durchschnitt Energie in der letzte Monat
#      query: >
#        SELECT ROUND(AVG(avg_per_day),2) 'value'
#          FROM (
#          SELECT AVG(state) AS avg_per_day
#          FROM states
#          WHERE entity_id = 'sensor.sonoffpow_03_energy_yesterday'
#          AND state != 'unknown'
#          AND state != ''
#          AND created > datetime('now', '-1 month')
#          GROUP BY DATE(created)
#        ) avgs;
#      column: 'value'
#      unit_of_measurement: kWh
#
#  - platform: sql
#    queries:
#    - name: SonoffPOW 03 Gesamt Energie in der letzte Monat
#      query: >
#        SELECT ROUND(SUM(max_per_day),2) 'value'
#        FROM (
#          SELECT MAX(state) AS max_per_day
#          FROM states
#          WHERE entity_id = 'sensor.sonoffpow_03_energy_yesterday'
#          AND state != 'unknown'
#          AND state != ''
#          AND created > datetime('now', '-1 month')
#          GROUP BY DATE(created)
#        ) sums;
#      column: 'value'
#      unit_of_measurement: kWh
