# Sonoff S26 1
# Tasmota integration

# Automations #######################################################
automation:
  - id: tv_board_off
    alias: "TV Board OFF"
    initial_state: false
    trigger:
      platform: state
      entity_id: group.familie_wlan
      to: "not_home"
    action:
      service: switch.turn_off
      entity_id: switch.sonoffs26_1
