# Sonoff S26 1
# Tasmota integration

# Sensors ###########################################################
template:
  - sensor:
      - name: TV Board power
        unique_id: tv_board_power
        state: "{{ 30 if is_state('switch.sonoffs26_1', 'on') else 0 }}"
        unit_of_measurement: "W"
        device_class: power

sensor:
  # Energy sensors
  - platform: integration
    name: TV Board energy
    unique_id: tv_board_energy
    source: sensor.tv_board_power
    method: left
    unit_prefix: k
    round: 2

# Automations #######################################################
automation:
  # TV Board on  -> TV off -> Niemand Zuhause -> TV Board off
  #                           Jemand Zuhause  -> Zeit ist zwischen 23:00 and 11:00 -> TV Board off
  #          off -> Jemand Zuhause -> Zeit ist zwischen 11:00 and 23:00 -> TV Board on
  - id: tv_board_manage
    alias: "TV Board - Verwaltung"
    trigger:
      - platform: state
        entity_id: group.family
        for: "00:04:00"

      - platform: time_pattern
        minutes: "/15"

    condition:
      - condition: or
        conditions:
          - "{{ is_state('media_player.sony_bravia_kd55x8505b', 'off') }}"

    action:
      - alias: "Выбор условий для выключения и включения TV Board"
        choose:
          - conditions:
              - "{{ is_state('switch.sonoffs26_1', 'on')
                and is_state('group.family', 'not_home') }}"
            sequence:
              - service: switch.turn_off
                target:
                  entity_id: switch.sonoffs26_1
          - conditions:
              - "{{ is_state('switch.sonoffs26_1', 'on')
                and (now().hour < 11 or now().hour > 22) }}"
            sequence:
              - service: switch.turn_off
                target:
                  entity_id: switch.sonoffs26_1
          - conditions:
              - "{{ is_state('switch.sonoffs26_1', 'off')
                and is_state('group.family', 'home')
                and (now().hour > 10 and now().hour < 23) }}"
            sequence:
              - service: switch.turn_on
                target:
                  entity_id: switch.sonoffs26_1
