# Sonoff BN-SZ01 LED Light
# Tasmota

homeassistant:
  customization:
    light.sonoffbnsz01:
      friendly_name: Garage LED
      icon: mdi:wall-sconce-flat-outline

automation:
  - id: garagenlicht_einschalten
    alias: Garagenlicht einschalten
    description: Garagenlicht einschalten nach der Sonnenunregang oder wenn es dunkel
      ist
    trigger:
    - type: value
      platform: device
      device_id: db8b13c767d84865a607aca77975a221
      entity_id: sensor.torposition
      domain: sensor
      above: 50
      for:
        hours: 0
        minutes: 0
        seconds: 5
        milliseconds: 0
    condition:
    # - condition: or
    #   conditions:
    - condition: sun
      before: sunrise
      before_offset: 00:15:00
      after: sunset
      after_offset: -00:15:00
      # - condition: and
      #   conditions:
      #   - condition: numeric_state
      #     entity_id: sensor.camgarage_light_level
      #     below: '1'
      #   - condition: device
      #     device_id: 1a37c06013019437b55ec0e4fbd8279e
      #     domain: device_tracker
      #     entity_id: device_tracker.kristina_s6
      #     type: is_home
    action:
    - type: turn_on
      device_id: 63713a671de1472e84d5832bcb399f0e
      entity_id: light.sonoffbnsz01
      domain: light
      brightness_pct: 100
    - delay:
        hours: 0
        minutes: 10
        seconds: 0
        milliseconds: 0
    - type: turn_off
      device_id: 63713a671de1472e84d5832bcb399f0e
      entity_id: light.sonoffbnsz01
      domain: light
    mode: restart
  - id: garagenlicht_ausschalten
    alias: Garagenlicht ausschalten
    description: 'Garagenlicht ausschalten wenn das Garagentor geschlossen wurde '
    mode: restart
    trigger:
    - platform: state
      entity_id: binary_sensor.tor_offen
      to: 'off'
      for:
        hours: 0
        minutes: 0
        seconds: 5
        milliseconds: 0
    - platform: state
      entity_id: input_boolean.torteil
      to: 'on'
      for:
        hours: 0
        minutes: 0
        seconds: 5
        milliseconds: 0
    condition: []
    action:
    - type: turn_off
      device_id: 63713a671de1472e84d5832bcb399f0e
      entity_id: light.sonoffbnsz01
      domain: light
