# Sonoff_RF_R2_Power
# Tasmota

# Customize #########################################################
homeassistant:
  customize:
    # Switch ##########
    switch.sonoffrf1:
      friendly_name: Kristinas Leiste
      icon: mdi:led-strip-variant
    # Light ###########
    light.sonoffrf1:
      friendly_name: Kristinas Leiste
      icon: mdi:led-strip-variant
