# Sonoff POW R2
# Tasmota Integration

# Utility meter #####################################################
utility_meter:
  sonoffpow_04_energy_d:
    source: sensor.sonoffpow_04_energy_total
    cycle: daily

  sonoffpow_04_energy_m:
    source: sensor.sonoffpow_04_energy_total
    cycle: monthly

  sonoffpow_04_energy_y:
    source: sensor.sonoffpow_04_energy_total
    cycle: yearly

# Automation ########################################################
automation:
- id: telegram_sonoffpow_04
  alias: "Telegram sonoffpow_04"
  mode: parallel
  trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: "/ambiente_kueche"

  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/ambiente_kueche'

  action:
    - service: light.toggle
      data:
        entity_id: light.sonoffpow_04

    - wait_for_trigger:
      - platform: state
        entity_id: light.sonoffpow_04
      timeout: 5
      continue_on_timeout: true

    - service: telegram_bot.send_message
      data:
        target: "{{ trigger.event.data.user_id }}"
        message: "💡 {{ state_attr('light.sonoffpow_04', 'friendly_name') }} ist {{ states('light.sonoffpow_04') }}"

# Customize #########################################################
homeassistant:
  customize:

# Sensor ##########
    sensor.sonoffpow_04_energy_d:
      friendly_name: Verbrauch pro Tag (Ambiente Küche)

    sensor.sonoffpow_04_energy_m:
      friendly_name: Verbrauch pro Monat (Ambiente Küche)

    sensor.sonoffpow_04_energy_y:
      friendly_name: Verbrauch pro Jahr (Ambiente Küche)
