# Sonoff S26 1
# Tasmota integration

# Sensors ###########################################################
template:
  - sensor:
      - name: TV Board power
        unique_id: tv_board_power
        state: "{{ 30 if is_state('switch.sonoffs26_1', 'on') else 0 }}"
        unit_of_measurement: "W"
        device_class: power

sensor:
  # Energy sensors
  - platform: integration
    name: TV Board energy
    unique_id: tv_board_energy
    source: sensor.tv_board_power
    method: left
    unit_prefix: k
    round: 2

# Automations #######################################################
automation:
  # - id: tv_board_off
  #   alias: "TV Board OFF"
  #   initial_state: false
  #   trigger:
  #     platform: state
  #     entity_id: group.family_wlan
  #     to: "not_home"
  #   action:
  #     service: switch.turn_off
  #     entity_id: switch.sonoffs26_1

  - id: tv_board_manage
    alias: "TV Board - Verwaltung"
    trigger:
      - platform: state
        entity_id: group.family
        for: "00:04:00"

      # - platform: state
      #   entity_id: group.family_wlan
      #   for: "00:05:00"

    # Two groups
    # action:
    #   - choose:
    #       - conditions:
    #           - condition: or
    #             conditions:
    #               - condition: state
    #                 entity_id: group.family
    #                 state: home
    #               - condition: state
    #                 entity_id: group.familie_wlan
    #                 state: home
    #         sequence:
    #           - service: switch.turn_on
    #             target:
    #               entity_id: switch.sonoffs26_1

    #       - conditions:
    #           - condition: or
    #             conditions:
    #               - condition: state
    #                 entity_id: group.family
    #                 state: not_home
    #               - condition: state
    #                 entity_id: group.familie_wlan
    #                 state: not_home
    #         sequence:
    #           - service: switch.turn_off
    #             target:
    #               entity_id: switch.sonoffs26_1

    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: group.family
                state: home
            sequence:
              - service: switch.turn_on
                target:
                  entity_id: switch.sonoffs26_1

          - conditions:
              - condition: state
                entity_id: group.family
                state: not_home
            sequence:
              - service: switch.turn_off
                target:
                  entity_id: switch.sonoffs26_1
