# Sonoff POW R2
# Tasmota Integration

# Utility meter #####################################################
utility_meter:
  sonoffpow_03_energy_d:
    source: sensor.sonoffpow_03_energy_total
    cycle: daily

  sonoffpow_03_energy_m:
    source: sensor.sonoffpow_03_energy_total
    cycle: monthly

  sonoffpow_03_energy_y:
    source: sensor.sonoffpow_03_energy_total
    cycle: yearly

# Automation ########################################################
automation:
- id: telegram_sonoffpow_03
  alias: "Telegram sonoffpow_03"
  mode: parallel
  trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: "/kuechenlicht"

  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/kuechenlicht'

  action:
    - service: light.toggle
      data:
        entity_id: light.sonoffpow_03

    - wait_for_trigger:
      - platform: state
        entity_id: light.sonoffpow_03
      timeout: 5
      continue_on_timeout: true

    - service: telegram_bot.send_message
      data:
        target: "{{ trigger.event.data.user_id }}"
        message: "💡 {{ state_attr('light.sonoffpow_03', 'friendly_name') }} ist {{ states('light.sonoffpow_03') }}"

# Customize #########################################################
homeassistant:
  customize:

# Sensor ##########
    sensor.sonoffpow_03_energy_d:
      friendly_name: Verbrauch pro Tag (Küchenlicht)

    sensor.sonoffpow_03_energy_m:
      friendly_name: Verbrauch pro Monat (Küchenlicht)

    sensor.sonoffpow_03_energy_y:
      friendly_name: Verbrauch pro Jahr (Küchenlicht)
