# Sonoff S26 2
# Tasmota

# Switch ############################################################
switch:
  - platform: mqtt
    name: "Sonoffs26 2"
    state_topic: "sonoffs26-2/stat/RESULT"
    value_template: "{{ value_json.POWER }}"
    command_topic: "sonoffs26-2/cmnd/POWER"
    availability_topic: "sonoffs26-2/tele/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false
    json_attributes_topic: "sonoffs26-2/tele/STATE"

# Sensor ############################################################
sensor:
  - platform: mqtt
    name: "Sonoffs26 2 Status"
    state_topic: "sonoffs26-2/tele/STATE"
    value_template: '{{ value_json["Wifi"]["RSSI"] }}'
    unit_of_measurement: "%"
    json_attributes_topic: "sonoffs26-2/tele/STATE"

## Light #############################################################
#light:
#  - platform: switch
#    name: "SonoffS26 2"
#    entity_id: switch.sonoffs26_2

automation:
- id: telegram_sonoffs26_2
  alias: "Telegram sonoffs26_2"
  trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: "/test"

  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/test'

  action:
    - service: switch.toggle
      data:
        entity_id: switch.sonoffs26_2

    - wait_for_trigger:
      - platform: state
        entity_id: switch.sonoffs26_2
      timeout: 5
      continue_on_timeout: true

    - service: telegram_bot.send_message
      data:
        target: "{{ trigger.event.data.user_id }}"
        message: "{{ state_attr('switch.sonoffs26_2', 'friendly_name') }} ist {{ states('switch.sonoffs26_2') }}"

# Customize #########################################################
homeassistant:
  customize:
# Switch ##########
    switch.sonoffs26_2:
      friendly_name: Sonoff S26 2
#      icon: mdi:track-light
## Light ###########
#    light.sonoffs26_2:
#      friendly_name: Wandlicht
#      icon: mdi:track-light
# Sensor ##########
    sensor.sonoffs26_2_status:
      friendly_name: Sonoff S26 2 Status
      icon: mdi:information
      unit_of_measurement: "%"
