# Sonoff POW R2
# Tasmota Integration

# Sensor ############################################################
utility_meter:
#  sonoffpow_02_energy_d:
#    source: sensor.sonoffpow_02_energy_total
#    cycle: daily

  sonoffpow_02_energy_m:
    source: sensor.sonoffpow_02_energy_total
    cycle: monthly

  sonoffpow_02_energy_y:
    source: sensor.sonoffpow_02_energy_total
    cycle: yearly

# Automation ########################################################
automation:
- id: telegram_sonoffpow_02
  alias: "Telegram sonoffpow_02"
  mode: parallel
  trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: "/ambiente_wohnen"

  - platform: event
    event_type: telegram_callback
    event_data:
      command: "/ambiente_wohnen"

  action:
    - service: light.toggle
      data:
        entity_id: light.sonoffpow_02

    - wait_for_trigger:
      - platform: state
        entity_id: light.sonoffpow_02
      timeout: 5
      continue_on_timeout: true

    - service: telegram_bot.send_message
      data:
        target: "{{ trigger.event.data.user_id }}"
        message: "💡 {{ state_attr('light.sonoffpow_02', 'friendly_name') }} ist {{ states('light.sonoffpow_02') }}"

# Customize #########################################################
homeassistant:
  customize:
# Sensor ##########
    sensor.sonoffpow_02_energy_total:
      friendly_name: Verbrauch Total (Ambiente Wohnen)
      icon: mdi:lightning-bolt

    sensor.sonoffpow_02_energy_power:
      friendly_name: Leistung (Ambiente Wohnen)
      icon: hass:gauge
      device_class: power

    sensor.sonoffpow_02_energy_today:
      friendly_name: Verbrauch Heute (Ambiente Wohnen)
      icon: mdi:lightning-bolt

#    sensor.sonoffpow_02_energy_d:
#      friendly_name: Verbrauch Heute (Ambiente Wohnen)
#      icon: mdi:lightning-bolt

    sensor.sonoffpow_02_energy_m:
      friendly_name: Verbrauch im Monat (Ambiente Wohnen)
      icon: mdi:lightning-bolt

    sensor.sonoffpow_02_energy_y:
      friendly_name: Verbrauch im Jahr (Ambiente Wohnen)
      icon: mdi:lightning-bolt
