# Sonoff BN-SZ01 LED Light
# Tasmota

# Customize #########################################################
homeassistant:
  customize:
    light.sonoffbnsz01:
      friendly_name: Garage LED
      icon: mdi:wall-sconce-flat-outline
