# Sonoff POW R2
# Tasmota Integration

# Sensor ####################
utility_meter:
  #  sonoffpow_04_energy_d:
  #    source: sensor.sonoffpow_04_energy_total
  #    cycle: daily

  sonoffpow_04_energy_m:
    unique_id: sonoffpow_04_energy_m
    source: sensor.sonoffpow_04_energy_total
    cycle: monthly

  sonoffpow_04_energy_y:
    unique_id: sonoffpow_04_energy_y
    source: sensor.sonoffpow_04_energy_total
    cycle: yearly

# Automation ################
automation:
  - id: telegram_sonoffpow_04
    alias: "Telegram - Sonoffpow_04"
    mode: parallel
    triggers:
      - trigger: event
        event_type: telegram_command
        event_data:
          command: "/ambiente_kueche"

      - trigger: event
        event_type: telegram_callback
        event_data:
          command: "/ambiente_kueche"

    actions:
      - action: light.toggle
        data:
          entity_id: light.sonoffpow_04

      - wait_for_trigger:
          - trigger: state
            entity_id: light.sonoffpow_04
        timeout: "00:00:05"
        continue_on_timeout: true

      - action: script.telegram_callback
        data:
          target: "{{ trigger.event.data.chat_id }}"
          message_id: "{{ trigger.event.data.message.message_id if trigger.event.event_type == 'telegram_callback' else 1000 }}"
          message: "💡 {{ state_attr('light.sonoffpow_04', 'friendly_name') }} - {{ states('light.sonoffpow_04') }}"

# Customize #################
homeassistant:
  customize:
    light.sonoffpow_04:
      friendly_name: Ambiente Küche
      icon: hass:television-ambient-light

    sensor.sonoffpow_04_energy_total:
      friendly_name: Verbrauch (Ambiente Küche)
      icon: mdi:lightning-bolt
    sensor.sonoffpow_04_energy_power:
      friendly_name: Leistung (Ambiente Küche)
      icon: hass:gauge
      device_class: power
    sensor.sonoffpow_04_energy_today:
      friendly_name: Verbrauch Heute (Ambiente Küche)
      icon: mdi:lightning-bolt
    sensor.sonoffpow_04_energy_m:
      friendly_name: Verbrauch im Monat (Ambiente Küche)
      icon: mdi:lightning-bolt
    sensor.sonoffpow_04_energy_y:
      friendly_name: Verbrauch im Jahr (Ambiente Küche)
      icon: mdi:lightning-bolt
