# Sonoff POW R2
# Tasmota integration

# Sensor ############################################################
sensor:
  - platform: integration
    source: sensor.sonoffpow_01_energy_power
    name: sonoffpow_01_energy_spent
    unit_prefix: k
    round: 2

# Utility meter #####################################################
utility_meter:
  sonoffpow_01_energy_d:
    source: sensor.sonoffpow_01_energy_total
    cycle: daily

  sonoffpow_01_energy_m:
    source: sensor.sonoffpow_01_energy_total
    cycle: monthly

  sonoffpow_01_energy_y:
    source: sensor.sonoffpow_01_energy_total
    cycle: yearly

# Automation ########################################################
automation:
- id: telegram_sonoffpow_01
  alias: "Telegram sonoffpow_01"
  mode: parallel
  trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: "/wandlicht"

  - platform: event
    event_type: telegram_callback
    event_data:
      command: "/wandlicht"

  action:
    - service: light.toggle
      data:
        entity_id: light.sonoffpow_01

    - wait_for_trigger:
      - platform: state
        entity_id: light.sonoffpow_01
      timeout: 5
      continue_on_timeout: true

    - service: telegram_bot.send_message
      data:
        target: "{{ trigger.event.data.user_id }}"
        message: "💡 {{ state_attr('light.sonoffpow_01', 'friendly_name') }} ist {{ states('light.sonoffpow_01') }}"

#  Service ist {{ trigger.event }}"

# Customize #########################################################
homeassistant:
  customize:

# Sensor ##########
    sensor.sonoffpow_01_energy_spent:
      friendly_name: Verbrauch (Wandlicht), kWh

    sensor.sonoffpow_01_energy_d:
      friendly_name: Verbrauch pro Tag (Wandlicht)

    sensor.sonoffpow_01_energy_m:
      friendly_name: Verbrauch pro Monat (Wandlicht)

    sensor.sonoffpow_01_energy_y:
      friendly_name: Verbrauch pro Jahr (Wandlicht)
