# Telegram Bot configuration
telegram_bot:
  - platform: polling
    # - platform: broadcast
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_channel
      - !secret telegram_bot_familie
      - !secret telegram_bot_anatolij
      - !secret telegram_bot_natalja
      - !secret telegram_bot_kristina
      - !secret telegram_bot_veronika

# Notify ############################################################
notify:
  - name: telegram_schick_home
    platform: telegram
    chat_id: !secret telegram_channel

  - name: telegram_bot_familie
    platform: telegram
    chat_id: !secret telegram_bot_familie

  - name: telegram_bot_anatolij
    platform: telegram
    chat_id: !secret telegram_bot_anatolij

  - name: telegram_bot_natalja
    platform: telegram
    chat_id: !secret telegram_bot_natalja

  - name: telegram_bot_kristina
    platform: telegram
    chat_id: !secret telegram_bot_kristina

  - name: telegram_bot_veronika
    platform: telegram
    chat_id: !secret telegram_bot_veronika

# Automation ########################################################
automation:
  # Manage queries of telegram
  - id: telegram_control
    alias: "Telegram - Control"
    trigger:
      - platform: event
        event_type: telegram_callback
        event_data: {}
      - platform: event
        event_type: telegram_command
        event_data: {}

    action:
      - choose:
          # Start
          - conditions:
              - condition: template
                value_template: "{{ trigger.event.data.command == '/start' }}"
            sequence:
              - service: telegram_bot.send_message
                data:
                  target: "{{ trigger.event.data.chat_id }}"
                  message: "Tastatur aktiviert"
                  keyboard:
                    # - "/wandlicht, /wohnlicht, /kuechenlicht"
                    # - "/essecke, /ambiente_wohnen, /ambiente_kueche"
                    # - "/rollade_1, /rollade_2, /rollade_3, /rollade_4"
                    - "/alarm, /tor, /start, /help"

              - service: script.telegram_callback
                data:
                  target: "{{ trigger.event.data.chat_id }}"
                  message_id: "{{ trigger.event.data.message.message_id if trigger.event.event_type == 'telegram_callback' else 1000 }}"
                  message: |
                    Wähle das Symbol [/] unten und dann eine Aktion aus.
                    /start - Zeigt diese Nachricht
                    /help - Zeigt eine Nachricht mit Befehlen an
          # Help
          - conditions:
              - condition: template
                value_template: "{{ trigger.event.data.command == '/help' }}"
            sequence:
              - service: script.telegram_callback
                data:
                  target: "{{ trigger.event.data.chat_id }}"
                  message_id: "{{ trigger.event.data.message.message_id if trigger.event.event_type == 'telegram_callback' else 1000 }}"
                  message: |
                    *Tor öffnen/schliessen:*
                    - /tor - Garage öffnen/schliessen
                    - /torteil - Garage teilweise öffnen/schliessen

                    *Licht ein/aus:*
                    - /wandlicht - Wandlicht
                    - /wohnlicht - Wohnlicht
                    - /kuechenlicht - Küchenlicht
                    - /essecke - Esseckenlicht
                    - /ambiente\_wohnen - Ambiente Wohnzimmer
                    - /ambiente\_kueche - Ambiente Küche

                    *Rollade öffnen/schliessen:*
                    - /rollade\_1 - Rollade 1
                    - /rollade\_2 - Rollade 2
                    - /rollade\_3 - Rollade 3
                    - /rollade\_4 - Rollade Terrasse

                    *Allgemein:*
                    - /start - Zeigt die Begrüßungsnachricht
                    - /help - Zeigt eine Nachricht mit Befehlen an

# Scripts ###########################################################
script:
  telegram_callback:
    alias: Telegram - Callback
    icon: mdi:send
    mode: parallel
    sequence:
      - service: telegram_bot.send_message
        data:
          target: "{{ target }}"
          message: "{{ message }}"
          inline_keyboard:
            - "{{ (states('light.sonoffpow_01') == 'on') | iif('🟢', '🔴') }} Wandlicht:/wandlicht,
              {{ (states('light.shellyswitch25_10c7c3_channel_1') == 'on') | iif('🟢', '🔴') }} Wohnen:/wohnlicht,
              {{ (states('light.shellyswitch25_10a36d_channel_1') == 'on') | iif('🟢', '🔴') }} Küche:/kuechenlicht"
            - "{{ (states('light.shellyswitch25_10a36d_channel_2') == 'on') | iif('🟢', '🔴') }} Essecke:/essecke,
              {{ (states('light.sonoffpow_02') == 'on') | iif('🟢', '🔴') }} Ambiwohnen:/ambiente_wohnen,
              {{ (states('light.sonoffpow_04') == 'on') | iif('🟢', '🔴') }} Ambiküche:/ambiente_kueche"
            - "{% set r1 = state_attr('cover.shellyswitch25_f37a8c', 'current_position') | int %}
              {% set r2 = state_attr('cover.shellyswitch25_f37b28', 'current_position') | int %}
              {% set r3 = state_attr('cover.shellyswitch25_10eaa4', 'current_position') | int %}
              {{ (r1 < 95) | iif((r1 < 20) | iif('🔒', '🟢'~r1~'%'), '🟢') }} Rollade 1:/rollade_1,
              {{ (r2 < 95) | iif((r2 < 20) | iif('🔒', '🟢'~r2~'%'), '🟢') }} Rollade 2:/rollade_2,
              {{ (r3 < 95) | iif((r3 < 20) | iif('🔒', '🟢'~r3~'%'), '🟢') }} Rollade 3:/rollade_3"
            - "{% set r4 = state_attr('cover.shellyswitch25_10d315', 'current_position') | int %}
              {{ (r4 < 95) | iif((r4 < 20) | iif('🔒', '🟢'~r4~'%'), '🟢') }} Terrasse:/rollade_4,
              {{ ( states('sensor.torposition') | int > 0 ) | iif( '🟢' ~ states('sensor.torposition') ~ '%' , '🔒' ) }} Tor:/tor,
              {{ ( states('sensor.torposition') | int > 0 ) | iif( '🟢' ~ states('sensor.torposition') ~ '%' , '🔒' ) }} Tortel:/torteil"
            - "{{ (states('input_boolean.alarm_indoor') == 'on') | iif('🚨', '🔒') }} Alarm:/alarm,
              Home:/start,
              Hilfe:/help"

      - condition: template
        value_template: "{{ (message_id is defined) and (message_id != 1000) }}"

      - service: telegram_bot.delete_message
        data:
          message_id: "{{ message_id }}"
          chat_id: "{{ target }}"

      # 🔴🟢🔓🔒⚪
# wandlicht - Wandlicht ein/aus
# wohnlicht - Wohnlicht ein/aus
# kuechenlicht - Küchenlicht ein/aus
# essecke - Esseckenlicht ein/aus
# ambiente_wohnen - Ambiente Wohnzimmer ein/aus
# ambiente_kueche - Ambiente Küche ein/aus
# rollade_1 - Rollade 1 öffnen/schliessen
# rollade_2 - Rollade 2 öffnen/schliessen
# rollade_3 - Rollade 3 öffnen/schliessen
# rollade_4 - Rollade Hinten öffnen/schliessen
# tor - Garage öffnen/schliessen
# torteil - Garage teilweise öffnen/schliessen
# start - Zeigt die Begrüßungsnachricht
# help - Zeigt eine Nachricht mit Befehlen an

