# Tuya
# https://github.com/rospogrigio/localtuya/issues/1148
#

# Sensors #######################################
sensor:
  - platform: integration
    unique_id: tuyaplug8_energy
    source: sensor.tuyaplug8_power
    name: Tuyaplug8 Energy
    unit_prefix: k
    round: 2

utility_meter:
  tuyaplug8_energy_daily:
    unique_id: tuyaplug8_energy_daily
    source: sensor.tuyaplug8_energy
    name: Tuyaplug8 Energy Daily
    cycle: daily
  tuyaplug8_energy_monthly:
    unique_id: tuyaplug8_energy_monthly
    source: sensor.tuyaplug8_energy
    name: Tuyaplug8 Energy Monthly
    cycle: monthly
  tuyaplug8_energy_yearly:
    unique_id: tuyaplug8_energy_yearly
    source: sensor.tuyaplug8_energy
    name: Tuyaplug8 Energy Yearly
    cycle: yearly

# Customize #####################################
homeassistant:
  customize:
    # Switch ##########
    switch.tuyaplug8:
      friendly_name: Tuyaplug8
      icon: mdi:desktop-tower-monitor
    switch.tuyaplug8_childlock:
      friendly_name: Kindersicherung (Tuyaplug8)
      icon: mdi:account-lock
    switch.tuyaplug8_overcharge:
      friendly_name: Überladung (Tuyaplug8)
      icon: mdi:battery-alert-variant

    # Sensor ##########
    sensor.tuyaplug8_current:
      friendly_name: Stromstärke (Tuyaplug8)
      # icon: mdi:current-ac

    sensor.tuyaplug8_power:
      friendly_name: Leistung (Tuyaplug8)
      # icon: mdi:lightning-bolt

    sensor.tuyaplug8_energy:
      friendly_name: Verbrauch (Tuyaplug8)
      # icon: mdi:counter

    sensor.tuyaplug8_energy_daily:
      friendly_name: Verbrauch Täglich (Tuyaplug8)
      # icon: mdi:counter

    sensor.tuyaplug8_energy_monthly:
      friendly_name: Verbrauch Monatlich (Tuyaplug8)
      # icon: mdi:counter

    sensor.tuyaplug8_energy_yearly:
      friendly_name: Verbrauch Jahrlich (Tuyaplug8)
      # icon: mdi:counter
