# Tuya
# https://github.com/rospogrigio/localtuya/issues/1148
#

# Sensors #######################################
sensor:
  - platform: integration
    unique_id: tuyaplug2_energy
    source: sensor.tuyaplug2_power
    name: Tuyaplug2 Energy
    unit_prefix: k
    round: 2

utility_meter:
  tuyaplug2_energy_daily:
    unique_id: tuyaplug2_energy_daily
    source: sensor.tuyaplug2_energy
    name: Tuyaplug2 Energy Daily
    cycle: daily
  tuyaplug2_energy_monthly:
    unique_id: tuyaplug2_energy_monthly
    source: sensor.tuyaplug2_energy
    name: Tuyaplug2 Energy Monthly
    cycle: monthly
  tuyaplug2_energy_yearly:
    unique_id: tuyaplug2_energy_yearly
    source: sensor.tuyaplug2_energy
    name: Tuyaplug2 Energy Yearly
    cycle: yearly

# Automations ###################################
# automation:
#   # TV Board on  -> TV off -> Niemand Zuhause -> TV Board off
#   #                           Jemand Zuhause  -> Zeit ist zwischen 23:00 and 11:00 -> TV Board off
#   #          off -> Jemand Zuhause -> Zeit ist zwischen 11:00 and 23:00 -> TV Board on
#   - id: tv_board_manage
#     alias: "TV Board - Verwaltung"
#     trigger:
#       - platform: state
#         entity_id: group.family
#         for: "00:04:00"

#       - platform: time_pattern
#         minutes: "/15"

#     condition:
#       - condition: or
#         conditions:
#           - "{{ is_state('media_player.sony_kd_55x8505b', 'off') }}"

#     action:
#       - alias: "Выбор условий для выключения и включения TV Board"
#         choose:
#           - conditions:
#               - "{{ is_state('switch.tuyaplug2', 'on')
#                 and is_state('group.family', 'not_home') }}"
#             sequence:
#               - service: switch.turn_off
#                 target:
#                   entity_id: switch.tuyaplug2
#           - conditions:
#               - "{{ is_state('switch.tuyaplug2', 'on')
#                 and (now().hour < 12 or now().hour > 22) }}"
#             sequence:
#               - service: switch.turn_off
#                 target:
#                   entity_id: switch.tuyaplug2
#           - conditions:
#               - "{{ is_state('switch.tuyaplug2', 'off')
#                 and is_state('group.family', 'home')
#                 and (now().hour > 11 and now().hour < 23) }}"
#             sequence:
#               - service: switch.turn_on
#                 target:
#                   entity_id: switch.tuyaplug2

# Customize #####################################
homeassistant:
  customize:
    # Switch ##########
    switch.tuyaplug2:
      friendly_name: TV Board
      icon: mdi:television
    switch.tuyaplug2_childlock:
      friendly_name: Kindersicherung (TV Board)
      icon: mdi:account-lock
    switch.tuyaplug2_overcharge:
      friendly_name: Überladung (TV Board)
      icon: mdi:battery-alert-variant

    # Sensor ##########
    sensor.tuyaplug2_current:
      friendly_name: Stromstärke (TV Board)
      # icon: mdi:current-ac

    sensor.tuyaplug2_power:
      friendly_name: Leistung (TV Board)
      # icon: mdi:lightning-bolt

    sensor.tuyaplug2_energy:
      friendly_name: Verbrauch (TV Board)
      # icon: mdi:counter

    sensor.tuyaplug2_energy_daily:
      friendly_name: Verbrauch Täglich (TV Board)
      # icon: mdi:counter

    sensor.tuyaplug2_energy_monthly:
      friendly_name: Verbrauch Monatlich (TV Board)
      # icon: mdi:counter

    sensor.tuyaplug2_energy_yearly:
      friendly_name: Verbrauch Jahrlich (TV Board)
      # icon: mdi:counter
