# Tuya
# https://github.com/rospogrigio/localtuya/issues/1148
#

# Sensors ###################
sensor:
  - platform: integration
    unique_id: tuyaplug9_energy
    source: sensor.tuyaplug9_power
    name: Tuyaplug9 Energy
    unit_prefix: k
    round: 2

utility_meter:
  tuyaplug9_energy_daily:
    unique_id: tuyaplug9_energy_daily
    source: sensor.tuyaplug9_energy
    name: Tuyaplug9 Energy Daily
    cycle: daily
  tuyaplug9_energy_monthly:
    unique_id: tuyaplug9_energy_monthly
    source: sensor.tuyaplug9_energy
    name: Tuyaplug9 Energy Monthly
    cycle: monthly
  tuyaplug9_energy_yearly:
    unique_id: tuyaplug9_energy_yearly
    source: sensor.tuyaplug9_energy
    name: Tuyaplug9 Energy Yearly
    cycle: yearly

# Customize #################
homeassistant:
  customize:
    switch.tuyaplug9:
      friendly_name: Terrasse Kamera
      icon: mdi:cctv-off
    switch.tuyaplug9_childlock:
      friendly_name: Kindersicherung (Terrasse Kamera)
      icon: mdi:account-lock
    switch.tuyaplug9_overcharge:
      friendly_name: Überladung (Terrasse Kamera)
      icon: mdi:battery-alert-variant

    sensor.tuyaplug9_current:
      friendly_name: Stromstärke (Terrasse Kamera)
      # icon: mdi:current-ac
    sensor.tuyaplug9_power:
      friendly_name: Leistung (Terrasse Kamera)
      # icon: mdi:lightning-bolt
    sensor.tuyaplug9_energy:
      friendly_name: Verbrauch (Terrasse Kamera)
      # icon: mdi:counter
    sensor.tuyaplug9_energy_daily:
      friendly_name: Verbrauch Täglich (Terrasse Kamera)
      # icon: mdi:counter
    sensor.tuyaplug9_energy_monthly:
      friendly_name: Verbrauch Monatlich (Terrasse Kamera)
      # icon: mdi:counter
    sensor.tuyaplug9_energy_yearly:
      friendly_name: Verbrauch Jahrlich (Terrasse Kamera)
      # icon: mdi:counter
