switch:
  - platform: wake_on_lan
    name: !secret pc1_name
    mac: !secret pc1_mac
    host: !secret pc1_host
    turn_off:
      service: shell_command.turn_off_pc1

  - platform: wake_on_lan
    name: !secret nas1_name
    mac: !secret nas1_mac
    host: !secret nas1_host
    turn_off:
      service: shell_command.turn_off_nas1

  - platform: wake_on_lan
    name: !secret nas2_name
    mac: !secret nas2_mac
    host: !secret nas2_host
    turn_off:
      service: shell_command.turn_off_nas2

shell_command:
  turn_off_pc1: !secret pc1_shutdown
  # turn_off_nas1: !secret pc2_shutdown
  # turn_off_nas2: !secret pc2_shutdown

# Customize #########################################################
homeassistant:
  customize:
    switch.anatolij_pc:
      icon: hass:desktop-tower-monitor
    # switch.schick_nb:
    #   icon: hass:laptop
    # switch.schick_nb_wlan:
    #   icon: hass:laptop
    # switch.kristina_nb:
    #   icon: hass:laptop
    # switch.kristina_nb_de79b3m13:
    #   icon: hass:laptop
    # switch.veronika_nb:
    #   icon: hass:laptop
    # switch.meister_pc:
    #   icon: hass:desktop-tower-monitor
    # switch.sergej_pc:
    #   icon: hass:desktop-tower-monitor
    # switch.larissa_aej_1024:
    #   icon: hass:desktop-tower-monitor
    # switch.beastly_v2:
    #   icon: hass:desktop-tower-monitor
    # switch.beastlynb_pc:
    #   icon: hass:laptop
    # switch.beastly_nb2:
    #   icon: hass:laptop
    switch.schick_nas:
      icon: hass:nas
    switch.q119_nas:
      icon: hass:nas
