homeassistant:
  customize:
    sensor.ble_humidity_temperatur_gt:
      unit_of_measurement: "%"
    sensor.ble_battery_temperatur_gt:
      unit_of_measurement: "%"
    sensor.ble_voltage_temperatur_gt:
      unit_of_measurement: V
    sensor.ble_rssi_temperatur_gt:
      unit_of_measurement: dBm

    sensor.ble_humidity_temperatur_og:
      unit_of_measurement: "%"
    sensor.ble_battery_temperatur_og:
      unit_of_measurement: "%"
    sensor.ble_voltage_temperatur_og:
      unit_of_measurement: V
    sensor.ble_rssi_temperatur_og:
      unit_of_measurement: dBm

    sensor.ble_humidity_temperatur_wz:
      unit_of_measurement: "%"
    sensor.ble_battery_temperatur_wz:
      unit_of_measurement: "%"
    sensor.ble_voltage_temperatur_wz:
      unit_of_measurement: V
    sensor.ble_rssi_temperatur_wz:
      unit_of_measurement: dBm
