# Customize #########################################################
homeassistant:
  customize:
# Switches ########
    switch.mower_mowing:
      friendly_name: Mähen

    switch.mower_home:
      friendly_name: 
      icon: Fahren nach Hause

    switch.mower_edgecut:
      friendly_name: 
      icon: Stop & Nach Hause fahren

    switch.mower_partymode:
      friendly_name: Partymodus

    switch.mower_lock:
      friendly_name: Sperren

#    switch.mower_mowing:
#      friendly_name: 
#      icon: 

# Sensor ##########
    sensor.landroid_mower_battery:
      friendly_name: Akkuladung
      device_class: battery
    sensor.landroid_mower_error:
      friendly_name: Fehler
    sensor.landroid_mower_status:
      friendly_name: Status

    sensor.mower_ip:
      friendly_name: IP-Adresse

    sensor.mower_bladetime:
      friendly_name: Klingenarbeitszeit
    sensor.mower_current_bladetime:
      friendly_name: Aktuelle Klingenarbeitszeit
    sensor.mower_totaltime:
      friendly_name: Arbeitszeit
    sensor.mower_distance:
      friendly_name: Ges. Distanz
    sensor.mower_lastupdate:
      friendly_name: Aktualisiert seit
      icon: mdi:update
    sensor.mower_wifi:
      friendly_name: WLAN Qualität
    sensor.mower_yaw:
      friendly_name: Gieren/Рысканье
    sensor.mower_roll:
      friendly_name: Rollen/Крен
    sensor.mower_pitch:
      friendly_name: Nicken/Тангаж

# Input Number ####
    input_number.mower_raindelay:
      friendly_name: Regenverzögerung
    input_number.mower_timeextension:
      friendly_name: Dauer anpassen

# Input Boolean ###
#    input_boolean.mower_0_sched_enable:
#      friendly_name: Sonntag
#    input_boolean.mower_1_sched_enable:
#      friendly_name: Montag
#    input_boolean.mower_2_sched_enable:
#      friendly_name: Dienstag
#    input_boolean.mower_3_sched_enable:
#      friendly_name: Mittwoch
#    input_boolean.mower_4_sched_enable:
#      friendly_name: Donnerstag
#    input_boolean.mower_5_sched_enable:
#      friendly_name: Freitag
#    input_boolean.mower_6_sched_enable:
#      friendly_name: Samstag
#
#    input_boolean.mower_0_cuttoedge:
#      friendly_name: Cut to edge
#    input_boolean.mower_1_cuttoedge:
#      friendly_name: Cut to edge
#    input_boolean.mower_2_cuttoedge:
#      friendly_name: Cut to edge
#    input_boolean.mower_3_cuttoedge:
#      friendly_name: Cut to edge
#    input_boolean.mower_4_cuttoedge:
#      friendly_name: Cut to edge
#    input_boolean.mower_5_cuttoedge:
#      friendly_name: Cut to edge
#    input_boolean.mower_6_cuttoedge:
#      friendly_name: Cut to edge

    input_boolean.mower_sched_settings:
      friendly_name: Mähplan
    input_boolean.mower_info_toggle:
      friendly_name: Information
#    input_boolean.mower_view_0:
#      friendly_name: So.
#    input_boolean.mower_view_1:
#      friendly_name: Mo.
#    input_boolean.mower_view_2:
#      friendly_name: Di.
#    input_boolean.mower_view_3:
#      friendly_name: Mi.
#    input_boolean.mower_view_4:
#      friendly_name: Do.
#    input_boolean.mower_view_5:
#      friendly_name: Fr.
#    input_boolean.mower_view_6:
#      friendly_name: Sa.
#    input_boolean.mower_view_config:
#      friendly_name: Konf.

# Automation ######
    automation.mower_notify_status:
      friendly_name: Mower Status Benachrichtigung
      icon: mdi:bell
    automation.mower_notify_error:
      friendly_name: Mower Fehler Benachrichtigung
      icon: mdi:bell

    automation.mower_sync_values:
      friendly_name: Mower Datenaktualisierung
      icon: mdi:sync
# Scripts #########
    script.mower_start:
      friendly_name: Mähen
      icon: mdi:play
    script.mower_pause:
      friendly_name: Mähen pausieren
      icon: mdi:home
    script.mower_stop:
      friendly_name: Mähen beenden
      icon: mdi:stop
    script.mower_set_config:
      friendly_name: Konfiguration speichern
      icon: mdi:content-save-settings
#    script.mower_views_toggle:
#      friendly_name: Tabs umschalten
#      icon: mdi:tab
