# Garage
# Control

# Template Sensors
template:
  - binary_sensor:
      - name: "Garage Open Too Long"
        unique_id: garage_open_too_long # Unique ID for Home Assistant
        state: >
          {{ states('cover.tor_tor') == 'open' and 
            state_attr('cover.tor_tor', 'current_position') | int(0) > 13 }}
        delay_on:
          minutes: 30 # Turns on after the condition is true for 30 minutes
        # Turns off as soon as the condition is false

# Automations
automation:
  - id: telegram_tor
    alias: "Telegram - Tor"
    mode: restart
    triggers:
      - trigger: event
        event_type: telegram_command
        event_data:
          command: "/tor"
      - trigger: event
        event_type: telegram_command
        event_data:
          command: "/torteil"

      - trigger: event
        event_type: telegram_callback
        event_data:
          command: "/tor"
      - trigger: event
        event_type: telegram_callback
        event_data:
          command: "/torteil"

    actions:
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ trigger.event.data.command == '/tor' }}"
            sequence:
              - action: button.press
                target:
                  entity_id: button.tor_tor

              - wait_for_trigger:
                  - trigger: state
                    entity_id: cover.tor_tor
                timeout: "00:00:05"
                continue_on_timeout: true

              - action: script.telegram_callback
                data:
                  target: "{{ trigger.event.data.chat_id }}"
                  message_id: "{{ trigger.event.data.message.message_id if trigger.event.event_type == 'telegram_callback' else 1000 }}"
                  message: "{{ state_attr('button.tor_tor', 'friendly_name') }} - {{ state_attr('cover.tor_tor', 'current_position') }}%"

          - conditions:
              - condition: template
                value_template: "{{ trigger.event.data.command == '/torteil' }}"
            sequence:
              - action: button.press
                target:
                  entity_id: button.tor_luftung

              - wait_for_trigger:
                  - trigger: state
                    entity_id: cover.tor_tor
                timeout: "00:00:05"
                continue_on_timeout: true

              - action: script.telegram_callback
                data:
                  target: "{{ trigger.event.data.chat_id }}"
                  message_id: "{{ trigger.event.data.message.message_id if trigger.event.event_type == 'telegram_callback' else 1000 }}"
                  message: "{{ state_attr('button.tor_luftung', 'friendly_name') }} - {{ state_attr('cover.tor_tor', 'current_position') }}%"

  - id: garage_auto_close
    alias: "Garage - Autoschließen"
    description: "Гараж - Автоматическое закрытие (открыт >13% более 30 мин, темно, свет выкл)"
    mode: single # Предотвращает одновременный запуск нескольких экземпляров

    # Triggers when any of the key conditions might lead to an auto-close scenario
    triggers:
      - trigger: state
        entity_id: binary_sensor.garage_open_too_long # Helper sensor turns on
        to: "on"
      - trigger: state
        entity_id: sun.sun
        to: "below_horizon" # It becomes dark
      - trigger: state
        entity_id: binary_sensor.all_lights_off
        to: "on" # All relevant lights turn off
      - trigger: homeassistant
        event: start # Check conditions when Home Assistant starts

    condition:
      # All these conditions must be true for the actions to run
      - condition: state
        entity_id: sun.sun
        state: "below_horizon" # Условие "темно"
      - condition: state
        entity_id: binary_sensor.all_lights_off # Условие "везде выключен свет"
        state: "on" # 'on' означает, что все светильники выключены
      - condition: state
        entity_id: binary_sensor.garage_open_too_long # Garage has been open >13% for over 30 mins
        state: "on"

    actions:
      - variables:
          initial_pos: "{{ state_attr('cover.tor_tor', 'current_position') | int }}"

      - action: telegram_bot.send_message
        data:
          target: !secret telegram_channel
          message: "🚗Гараж открыт уже 30 минут, сейчас темно и свет везде выключен. Планирую закрыть через 1 минуту. Свет будет мигать. Если ворота сдвинутся более чем на 10%, закрытие отменится."
      # Минутное ожидание с миганием света и проверкой отмены
      - alias: "Минутное ожидание с миганием и проверкой отмены"
        repeat:
          count: 12 # 12 циклов * 5 секунд = 60 секунд
          sequence:
            # Проверка отмены перед каждым миганием
            - choose:
                - conditions:
                    - condition: template
                      value_template: >
                        {% set current_pos = state_attr('cover.tor_tor', 'current_position') | int(0) %}
                        {{ (current_pos - initial_pos) | abs > 10 }}
                  sequence:
                    - action: telegram_bot.send_message
                      data:
                        target: !secret telegram_channel
                        message: "🚗Гараж - Автоматическое закрытие гаража отменено, так как положение ворот изменилось более чем на 10%."
                    - stop: "Закрытие отменено из-за изменения положения ворот"
            # Мигание светом
            - action: light.turn_on
              target:
                entity_id: light.sonoffbnsz01
              data: {} # Добавлено для явности, если light.turn_on требует
            - delay:
                seconds: 2.5 # Свет включен
            - action: light.turn_off
              target:
                entity_id: light.sonoffbnsz01
              data: {} # Добавлено для явности
            - delay:
                seconds: 2.5 # Свет выключен (общий цикл 5 секунд)

      # Финальная проверка перед закрытием (на случай, если состояние изменилось или отмена сработала в последний момент)
      - condition: template
        value_template: >
          {% set current_pos = state_attr('cover.tor_tor', 'current_position') | int(0) %}
          {{ (current_pos - initial_pos) | abs <= 10 }}
      - condition: template # Убедимся, что ворота все еще открыты и соответствуют условию
        value_template: "{{ states('cover.tor_tor') == 'open' and state_attr('cover.tor_tor', 'current_position') | int(0) > 13 }}"

      - action: telegram_bot.send_message
        data:
          target: !secret telegram_channel
          message: "🚗Гараж - Начинаю процедуру автоматического закрытия гаража..."

      # Попытка 1
      - alias: "Закрытие гаража - Попытка 1"
        action: button.press
        target:
          entity_id: button.tor_tor

      - delay:
          seconds: 3 # Дать время на реакцию и обновление состояния

      - choose:
          # Успех: ворота закрываются или уже закрыты
          - conditions:
              - "{{ states('cover.tor_tor') == 'closing' or states('cover.tor_tor') == 'closed' }}"
            sequence:
              - action: telegram_bot.send_message
                data:
                  target: !secret telegram_channel
                  message: "🚗Гараж - Ворота закрываются/закрыты после 1-й команды."
          # Неудача: ворота открываются или все еще открыты (остановлены)
          - conditions:
              - "{{ states('cover.tor_tor') == 'opening' or states('cover.tor_tor') == 'open' }}"
            sequence:
              - action: telegram_bot.send_message
                data:
                  target: !secret telegram_channel
                  message: "🚗Гараж - После 1-й команды, ворота {{ states('cover.tor_tor') }}. Отправляю 2-ю команду..."
              # Попытка 2:
              # Если было 'opening', это будет 'stop'.
              # Если было 'open' (stopped), это должно быть 'close'.
              - alias: "Закрытие гаража - Попытка 2"
                action: button.press
                target:
                  entity_id: button.tor_tor
              - delay:
                  seconds: 3

              - choose:
                  # Успех со 2-й попытки
                  - conditions:
                      - "{{ states('cover.tor_tor') == 'closing' or states('cover.tor_tor') == 'closed' }}"
                    sequence:
                      - action: telegram_bot.send_message
                        data:
                          target: !secret telegram_channel
                          message: "🚗Гараж - Ворота закрываются/закрыты после 2-й команды."
                  # Неудача: ворота все еще открываются, или открыты (остановлены) после 2-й попытки
                  - conditions:
                      - "{{ states('cover.tor_tor') == 'opening' or states('cover.tor_tor') == 'open' }}"
                    sequence:
                      - action: telegram_bot.send_message
                        data:
                          target: !secret telegram_channel
                          message: "🚗Гараж - После 2-й команды, ворота {{ states('cover.tor_tor') }}. Отправляю 3-ю команду..."
                      # Попытка 3:
                      # Если последовательность была: open -> stop -> (эта команда должна быть close)
                      - alias: "Закрытие гаража - Попытка 3"
                        action: button.press
                        target:
                          entity_id: button.tor_tor
                      - delay:
                          seconds: 3 # Дать время на реакцию
                      - action: telegram_bot.send_message
                        data:
                          target: !secret telegram_channel
                          message: "🚗Гараж - 3-я команда отправлена. Текущее состояние: {{ states('cover.tor_tor') }}. Ожидаю полного закрытия."
                default: # Неожиданное состояние после 2-й попытки
                  - action: telegram_bot.send_message
                    data:
                      target: !secret telegram_channel
                      message: "🚗Гараж - Неожиданное состояние ворот {{ states('cover.tor_tor') }} после 2-й попытки закрытия."
        default: # Неожиданное состояние после 1-й попытки
          - action: telegram_bot.send_message
            data:
              target: !secret telegram_channel
              message: "🚗Гараж - Неожиданное состояние ворот {{ states('cover.tor_tor') }} после 1-й попытки закрытия."

      # Ожидание закрытия ворот (мониторим cover.tor_tor)
      - wait_for_trigger:
          - trigger: state
            entity_id: cover.tor_tor
            to: "closed"
        timeout:
          minutes: 2 # Таймаут ожидания закрытия (настройте под свои ворота)
        continue_on_timeout: true # Продолжить выполнение, даже если таймаут

      # Уведомление о результате
      - variables:
          garage_closed_successfully: "{{ wait.trigger is not none and states('cover.tor_tor') == 'closed' }}"
      - action: telegram_bot.send_message
        data:
          target: !secret telegram_channel
          message: >
            {% if garage_closed_successfully %}
              🚗Гараж успешно закрыт автоматически.
            {% else %}
              🚗Гараж не закрылся (состояние: {{ states('cover.tor_tor') }}, позиция: {{ state_attr('cover.tor_tor', 'current_position') }}%) в течение 2 минут после команды автоматического закрытия.
            {% endif %}
