# Garage
# Teiloffnung
#
# itead 1channel
# ESPURNA 1.14.0
#

# Switch ############################################################
switch:
  - platform: mqtt
    name: TorTeil
    state_topic: itead1ch1/relay/0
    command_topic: itead1ch1/relay/0/set
    payload_on: 1
    payload_off: 0
    availability_topic: itead1ch1/status
    payload_available: 1
    payload_not_available: 0

# Automation ########################################################
automation:
  - id: itead1ch1_state_on_startup
    alias: itead1ch1 state on HA start-up
    trigger:
    - event: start
      platform: homeassistant
    action:
    - data:
        payload: '1'
        topic: itead1ch1/state
      service: mqtt.publish
